### ISSUE TITLE
When copying a vector_map to another vector_map, sends entire pair to key's constructor if it can accept it

### ISSUE THREAD

**Issue by xaxxon** [electronicarts/EASTL#100]
https://github.com/electronicarts/EASTL/blob/master/include/EASTL/utility.h#L407

If your key type has a templated constructor that can take a pair, this constructor is selected.   For example a constructor like:

```
template<class T>
MyKeyType(T&&t);

```
I don't see why (off the top of my head) you'd ever want this constructor to be called. 

```

/Users/xaxxon/apb/include/field_string.h:15:9: note: in instantiation of function template specialization 'AlignedString<16>::AlignedString<eastl::pair<FieldString, std::__1::function<bool (Thing &)> > >' requested here
        SUPER(std::forward<Strings>(strings)...)
        ^
/usr/local/include/EASTL/utility.h:407:7: note: in instantiation of function template specialization 'FieldString::FieldString<eastl::pair<FieldString, std::__1::function<bool (Thing &)> > >' requested here
                                : first(eastl::move(x)),
                                  ^
/usr/local/include/EASTL/memory.h:605:34: note: in instantiation of function template specialization 'eastl::pair<FieldString, std::__1::function<bool (Thing &)> >::pair<eastl::pair<FieldString, std::__1::function<bool (Thing &)> > &, void>' requested here
                                        ::new((void*)&*currentDest) value_type(*first);
                                                                    ^
/usr/local/include/EASTL/memory.h:705:52: note: in instantiation of function template specialization 'eastl::Internal::uninitialized_copy_impl<eastl::generic_iterator<eastl::pair<FieldString, std::__1::function<bool (Thing &)> > *, void>, eastl::generic_iterator<eastl::pair<FieldString, std::__1::function<bool (Thing &)> > *, void> >' requested here
                const generic_iterator<Result, void> i(Internal::uninitialized_copy_impl(eastl::generic_iterator<First, void>(first), // generic_iterator makes a pointer act like an iterator.
                                                                 ^
/usr/local/include/EASTL/vector.h:578:18: note: in instantiation of function template specialization 'eastl::uninitialized_copy_ptr<eastl::pair<FieldString, std::__1::function<bool (Thing &)> > *, eastl::pair<FieldString, std::__1::function<bool (Thing &)> > *, eastl::pair<FieldString, std::__1::function<bool (Thing &)> > *>' requested here
                mpEnd = eastl::uninitialized_copy_ptr(x.mpBegin, x.mpEnd, mpBegin);
                               ^
/usr/local/include/EASTL/vector_map.h:326:5: note: in instantiation of member function 'eastl::vector<eastl::pair<FieldString, std::__1::function<bool (Thing &)> >, eastl::allocator>::vector' requested here
                : base_type(x), mValueCompare(x.mValueCompare)
                  ^
/Users/xaxxon/apb/src/game_data.cpp:30:9: note: in instantiation of member function 'eastl::vector_map<FieldString, std::__1::function<bool (Thing &)>, eastl::less<FieldString>, eastl::allocator, eastl::vector<eastl::pair<FieldString, std::__1::function<bool (Thing &)> >, eastl::allocator> >::vector_map' requested here
        insertion_filters(other.insertion_filters) {

```

**Comment by xaxxon** [comment]
As a workaround I have removed that constructor from my utility.h with no apparent adverse affects, though I don't have any rigorous tests...

**Comment by xaxxon** [comment]
I'm having trouble making a small reproduction case, but I can confirm that the full code works with std::map instead of std::vector_map

**Comment by xaxxon** [comment]
adding a check to the pair constructor to verify that it's not constructing itself seems to work ok - eastl will build with that:

            template <typename U, typename = typename eastl::enable_if<eastl::is_convertible<U&&,typename eastl::remove_reference<T1>::type&&>::value **&& !is_same<remove_reference_t<U>, this_type>::value**>::type>

**Comment by xaxxon** [comment]
The problem, I believe, is that this function is taking precedence over the copy constructor for `this_type&` since it's a perfect match instead of it falling back to `this_type const &`.   So maybe some sort of check

**Comment by theryee** [comment]
I'm having trouble following this thread without a concrete example. I can comment on the use case for this constructor tho. This kind of single arg pair constructor is necessary because it implements operator[] for map structures: i.e. Copy or move Construction of the key and default construction of the value.

**Comment by xaxxon** [comment]
There is a concrete example now.

**Comment by theryee** [comment]
I think it's selecting this specific Pair move constructor because Foo's move constructor hasn't been marked as explicit: i.e. it satisfies the is_convertible checks.

**Comment by xaxxon** [comment]
But we are agreed that eastls behavior is clearly wrong right?

**Comment by theryee** [comment]
hmm.... probably wrong... but I'm still researching the stack.

**Comment by rparolin** [comment]
can you post an example of your key type that is implicitly convertible from a pair?  that behaviour feels like a corner-case in this context of a map and maybe should just be made explicit.  but i'm not sure i understand whats going on here.

**Comment by xaxxon** [comment]
I posted an example a while ago (it was an edit so it probably didn't
email).

Let me know if you need more.

Regardless of the "goodness" of my code, the behavior seems broken -
there's no way it should be turning a pair the type of the map entry into a
key.   That should be impossible.  It must maintain the context of the
types.

**Comment by xaxxon** [comment]
Talking to someone who works on libc++:

me: the constructor is there as a convenience for making map entries when accessing a map with [] on a key that doesn’t exist, from what I gather

him: Do they have tuple? You can do they exact same optimization with the std::piecewise_construct_t constructor.   That's how I implement the operator[] optimization I think you're describing.  Here's the entry point: https://github.com/llvm-mirror/libcxx/blob/master/include/map#L1319

**Comment by xaxxon** [comment]
him: there is no reason they can't call some different constructor here as to not break their pair implementation

https://github.com/electronicarts/EASTL/blob/master/include/EASTL/internal/red_black_tree.h#L2088

**Comment by rparolin** [comment]
I believe I resolved this issue when I refactored the pair single element ctors.
https://godbolt.org/z/cNOW8q
