### ISSUE TITLE
Some of the member in red_black_tree could be declared as protected?

### ISSUE THREAD

**Issue by HenryRLee** [electronicarts/EASTL#103]
Some of the members in the red_black_tree file could be declared as protected, in my opinion.

These members include:

1. [mpNode](https://github.com/electronicarts/EASTL/blob/master/include/EASTL/internal/red_black_tree.h#L171)  in class rbtree_iterator
2. [the explicit constructor](https://github.com/electronicarts/EASTL/blob/master/include/EASTL/internal/red_black_tree.h#L175) of class rbtree_iterator
3. [mCompare](https://github.com/electronicarts/EASTL/blob/master/include/EASTL/internal/red_black_tree.h#L220) in class rb_base
4. [mAnchor, mnSize and mAllocator](https://github.com/electronicarts/EASTL/blob/master/include/EASTL/internal/red_black_tree.h#L367) in class rbtree

There is no failing code of this issue, but just some undesirable issues, that users can access variables that they shouldn't.
```
    eastl::set<int> myset;
    eastl::set<int>::iterator it;

    auto a0 = it.mpNode;
    auto a1 = myset.mCompare;
    auto a2 = myset.mAnchor;

```

**Comment by rparolin** [comment]
the internal members you've highlighted I'd agree should have been protected.

i'm not sure the reasoning for the explicit constructor.

**Comment by HenryRLee** [comment]
I think because the explicit constructor was using a type, which shouldn't be known by the user, as a parameter, so we shall keep the function protected.
