### ISSUE TITLE
A couple of issues with the allocator

### ISSUE THREAD

**Issue by HenryRLee** [electronicarts/EASTL#105]
Hi, I just found a couple of issues related to the allocator.

1. The first issue is that some containers cannot use std::allocator. For example, these two lines cannot be compiled.
```
    eastl::vector<int, std::allocator<int>> myvector;
    eastl::set<int, eastl::less<int>, std::allocator<int>> myset;
```

2. Another issue is that, some essential member functions and typedef are missing in the template class eastl::allocator, especially the construct() and destroy() functions are missing. As a result, the containers and eastl::allocator_traits are directly calling new(ptr)T(), instead of calling the allocator<T>::construct() function.

If you also believe these are issues, I can work on the solutions. Personally, I would recommend implementing the missing members in eastl::allocator first, making it fit in an allocator_trait. After that, we can fix the codes in the containers, probably having some using the allocator_traits.

**Comment by rparolin** [comment]
eastl::allocator api is different from the std::allocator so it follows that they are not interchangeable.  please look at the eastl documentation it talks about the allocator choices in detail there.

I don't its a huge issue... the eastl::allocator_traits implementation already supports construct / destroy if they exist.  eastl hasn't done a pass of the allocator_traits support in our containers as the need hasn't come up and in my opinion it doesn't get you an huge benefit other calling wrapper functions.

don't get me wrong, its work that needs to happen at some point but i'm not seeing a pressing need to change all the containers over to use it yet.
