### ISSUE TITLE
Typo in type_traits.h

### ISSUE THREAD

**Issue by BobbyAnguelov** [electronicarts/EASTL#107]
on line 910 in type_traits.h, you have the following set of preprocessor conditions:

	#if defined(EA_COMPILER_NO_VARIADIC_TEMPLATES) || defined(EA_COMPILER_MSVC) || (defined(EA_PLATFORM_MINGW) && (defined(EA_COMPILER_CLANG) || defined(EA_COMPILER_GNUC)))

I think there might be a typo in requiring both clang and mingw to be defined simultaneously. I'm currently compiling clang 4.0.0 and and ending up in the else case which fails to compile. Pulling out the EA_COMPILER_CLANG on its own fixes the issue and I can compile EASTL with no issue.

I'm not sure if this is simply a typo or something that changed with clang 4, but maybe we can get it fixed in the next release?

**Comment by theryee** [comment]
This comment on line 909 indicates this is deliberate:
// Also mingw's clang and gcc fail to compile the code on windows.

Are you compiling with clang 4.0 in mingw or are you using clang 4.0 in a different environment?

**Comment by BobbyAnguelov** [comment]
Using Clang 4.0.0 on Windows using the MSVC std lib. Technically, I'm using libclang to do c++ reflection, but it is compiling the code using the MSVC 140 toolset. In my case, clang 4.0.0 seems to have the same issues as noted in the comment, but I am not using mingw, hence that define doesnt exist for me. I would assume clang would fail to compile that code in any situation where mingw is not present, so perhaps I am wrong in calling it a typo but rather it's an omision?

**Comment by rparolin** [comment]
Are you using the new Clang support in MSVC described here? 
https://blogs.msdn.microsoft.com/vcblog/2015/12/04/clang-with-microsoft-codegen-in-vs-2015-update-1/

I was anticipating problems because the macro table describe complicates how EABase/EASTL detects feature support.  What I'm suspecting is that fallback support is being enabled because EABase has enabled the the "EA_COMPILER_MSVC" define.

**Comment by BobbyAnguelov** [comment]
No I'm not. I downloaded the clang 4.0 release and built it locally, then used libclang to parse certain code files. As far as I can tell, it is parsing the files using clang but with the MSVC stdlibs, I think that implies the fms-extensions flag. In my case, only the EA_COMPILER_CLANG define is set. 

Maybe I've hit an edge case but given that clang has support for compiling the windows headers, it is not unreasonable to expect someone to try to compile EASTL on windows using clang but against the windows SDK stdlib.

Is there any problem you can think of with adding the standalone clang define there?

**Comment by rparolin** [comment]
Sorry, just circling back and review the open bugs.

The issue that I see is historically, clang wasn't used to build windows binaries - only msvc.  We would need to do a pass on the feature define code to ensure that there is no assumptions about non-msvc compilers implying the compiler isn't running on windows.  So the short answer is, using clang on windows isn't currently supported in EASTL.  Internally to EA, we run clang on windows but its always cross-compiling binaries for another platform.  ie. running clang to compile elf binaries to run on linux. 
I'd be interested in pull requests that running clang to generate windows binaries. As clang improves this is something we will want to do.

**Comment by BobbyAnguelov** [comment]
Makes sense, I cant imagine it would be a difficult change to make. I'd offer to help but my current contract doesn't allow me to :( 

Let's hope someone with some free time can do it :)

**Comment by rparolin** [comment]
I understand.  I got to come up with something better than keeping the "todo items" like this in the bugs list.

**Comment by Leandros** [comment]
Using clang 5.0.0 on win32 with EASTL works perfectly fine for me. The only fixed required was: https://github.com/electronicarts/EASTL/pull/123

**Comment by rparolin** [comment]
Interesting.  We should add an explicit test for on the CI to convince ourselves its working and so we don't regress behaviour.

**Comment by rparolin** [comment]
I'm going to close this issue as its been inactive for a while.
