### ISSUE TITLE
eastl::fixed_allocator_with_overflow always allocating new memory even if not full

### ISSUE THREAD

**Issue by gjaegy** [electronicarts/EASTL#109]
Hi,

I am facing a weird issue, where I am using a map with a fixed_allocator_with_overflow:

`typedef eastl::map<imSElevationRetrievalBlockKey, imSElevationRetrievalBlockData*, eastl::less<imSElevationRetrievalBlockKey>, eastl::fixed_allocator> MapCache;`
`typedef MapCache::node_type MapCacheNode;`

I am successfully initializing the allocator using the following code:
`imSizeT nBufferSize = _nCacheSize * sizeof(MapCacheNode);`
`m_pMapCacheMemory = new imU8[nBufferSize];`
`m_mapCache.get_allocator().init(m_pMapCacheMemory, nBufferSize, sizeof(MapCacheNode), EA_ALIGN_OF(MapCacheNode));`

Now, each time I insert an element in the map, the allocator allocates new memory by calling new[], while I would expect it to first reuse the memory buffer passed down through the init() method.

Replacing the "fixed_allocator_with_overflow" with "fixed_allocator" works and reuse the memory buffer created initially.

Am I doing anything wrong or is that a bug ?

Thanks a lot.

**Comment by rparolin** [comment]
Can you produce a broken unit test that highlights this behavior?

**Comment by gjaegy** [comment]
If I am not mistaken the following code should let you reproduce my issue:


```
struct SKey
{
	int i0, i1, i2;
	
	SKey() : i0(0), i1(0), i2(0) {}
	
	inline imBool operator< (const SKey& rhs) const
	{
		if (i0 != rhs.i0) return i0 < rhs.i0;
		if (i1 != rhs.i1) return i1 < rhs.i1;
		if (i2 != rhs.i2) return i2 < rhs.i2;
		return imFALSE;
	}
};
	
typedef eastl::map<SKey, void*, eastl::less<SKey>, eastl::fixed_allocator_with_overflow> MapCache;
typedef MapCache::node_type MapCacheNode;

const size_t nCacheSize = 1024;
size_t nBufferSize = nCacheSize * sizeof(MapCacheNode);
unsigned char* pBuffer = new unsigned char[nBufferSize];

MapCache m_mapCache;
m_mapCache.get_allocator().init(pBuffer, nBufferSize, sizeof(MapCacheNode), EA_ALIGN_OF(MapCacheNode));

SKey oKey;
m_mapCache[oKey] = 0;
```

**Comment by rparolin** [comment]
This definitely appears to be a bug in the fixed_allocator_with_overflow.  The head pointer in the linked list is set to nullptr in the ctor which forces an allocation from the overflow allocator for every insert.  

Thanks for reporting this.

**Comment by Jonathan-Weinstein** [comment]
Hi rparolin, I am looking for a project to contribute to. I see that you've self assigned this but I think I could be of help if you want.

A quick fix could be to just bump the "mpNext" member of `fixed_pool_base` (if there is room) after the call to `fixed_pool_base::init` in `fixed_allocator_with_overflow::init`, then set the freelist head to the start of the aligned buffer (also I think those 3 assigments at the end of that function aren't needed after fixed_pool_base::init). This would be the same as doing a free after an allocate (refering to fixed_pool_base) but leaving "mnCurrentSize" and "mnPeakSize" zero (if tracking is enabled).

Another approach that has advantages such as simpler code for checking if there is a free slot and reducing the base class to one pointer is to have a loop in init(). The loop would put everything in the freelist right then, setting each pointer to the slot on its right, except for the last witch would be to nullptr. Init() would be slower though, but I think for most use cases the trade may be better.

Here's an example I made showcasing the above: https://gist.github.com/Jonathan-Weinstein/f43de9d61880cd64b254fb6c661fc0ea

If you want me to make a PR even for just a minor change please let me know.

Thank you for reading.

**Comment by rparolin** [comment]
Sorry for delay.  Feel free to prepare a PR.   Thanks in advance for your work.

**Comment by rparolin** [comment]
I started looking into this issue again.  I wasn't able to reproduce the issue given the supplied test.  I'm going to close the issue.   Please reopen the ticket if there are more details.
