### ISSUE TITLE
eastl::remove() and remove_if() use copy assignment

### ISSUE THREAD

**Issue by Vuhdo** [electronicarts/EASTL#113]
Hi! While trying to adapt our codebase to use this great library, I came across one specific issue: `eastl::remove_if()` uses copy assignment operator when swapping values. Looks like a little bit ineffective. I checked two major STL implementations and they both use `std::move()` inside `std::remove_if()`.

**Comment by rparolin** [comment]
thanks for reporting

**Comment by rparolin** [comment]
The fix for this should be in the next EASTL release.
