### ISSUE TITLE
FYI: .Natvis file no longer matches implementation.

### ISSUE THREAD

**Issue by CodedByATool** [electronicarts/EASTL#116]
Changes to rbtree_node (the new base has to be cast to rbtree_node before fetching mValue etc), and accessing various fields though intermediate structures (mPair.mFirst.mpEnd etc).

Visual Studio users may think EASTL is much less usable than regular STL when comparing debug views. 

Would also be good to mention adding the .Natvis directly to the vcproj for VS2017 users in the doc.

**Comment by rparolin** [comment]
I recently fixed eastl::vector and eastl::string natvis code... but I'll look into the rbtree_node bugs.

Also, good point about adding documentation.  Our internal buildsystem automatically adds the natvis file to vcxproj so I overlooked that.

**Comment by bleachkitty** [comment]
Is the fix for eastl::vector and eastl::string checked in?  They're not displaying correctly for me, though other data structures are (tested eastl::deque and eastl::hash_map).

**Comment by rparolin** [comment]
Not yet, I'm targeting to have the 3.05.08 release (which contains the fix) up by mid next week.

**Comment by rparolin** [comment]
3.05.08 is released.

**Comment by bleachkitty** [comment]
Awesome, thanks!  I'll sync up on Monday and post again if I have any issues.  :)
