### ISSUE TITLE
deque::shrink_to_fit clears all data

### ISSUE THREAD

**Issue by Buracula** [electronicarts/EASTL#119]
```
template <typename T, typename Allocator, unsigned kDequeSubarraySize>
inline void deque<T, Allocator, kDequeSubarraySize>::shrink_to_fit()
{		
	return set_capacity(0);
}
```
If we use shrink_to_fit on deque it clears all items instead of deallocating unnecessary memory.

**Comment by rparolin** [comment]
Sorry for the delay.  Thanks for reporting this issue.

**Comment by theryee** [comment]
Does shrink_to_fit need to do anything for the EASTL implementation?

pop_back seems to free the subarray's when no longer required:
```
			// This is executed only when we are popping the first item off the last subarray.
			// In this case we need to free the subarray and point mItEnd to the previous subarray.
```

**Comment by rparolin** [comment]
I implemented this and it will be in the next EASTL release.
