### ISSUE TITLE
Problem with building correctly using the cmake build method

### ISSUE THREAD

**Issue by RobertHue** [electronicarts/EASTL#120]
I built EASTL with:
```
mkdir build
cd build
cmake .. -DEASTL_BUILD_TESTS:BOOL=ON
cmake --build . --config Release
cmake --build . --config Debug
cmake --build . --config RelWithDebInfo
cmake --build . --config MinSizeRel
cd test
ctest -C Release
ctest -C Debug
ctest -C RelWithDebInfo
ctest -C MinSizeRel
```

> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for include file pthread.h
> -- Looking for include file pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Check if compiler accepts -pthread
> -- Check if compiler accepts -pthread - yes
> -- Found Threads: TRUE  
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/huem_ro/EASTL/build
> 
> EASTL/build/test
>     Start 1: EASTLTestRuns
> 1/1 Test Nr. 1: EASTLTestRuns ....................   Passed   12.06 sec
> 
> 100% tests passed, 0 tests failed out of 1
> 
> Total Test time (real) =  12.08 sec

All the tests passed.
After writing some simple program including EASTL/list.h I receive the following compile error inside EASTL/internal/config.h that EABase/eahave.h is missing:

> Building file: ../src/main.cpp
> Invoking: GCC C++ Compiler
> g++ -std=c++0x -DEASTL_EABASE_DISABLED -I/home/huem_ro/EASTL/include -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/main.d" -MT"src/main.o" -o "src/main.o" "../src/main.cpp"
> In file included from /home/huem_ro/EASTL/include/EASTL/list.h:38:0,
>                  from ../src/main.cpp:17:
> /home/huem_ro/EASTL/include/EASTL/internal/config.h:63:27: fatal error: EABase/eahave.h: No such file or directory
>  #include <EABase/eahave.h>
> src/subdir.mk:18: recipe for target 'src/main.o' failed
>                            ^
> compilation terminated.
> make: *** [src/main.o] Error 1

EABase/eahave.h is not in the include directory of the pulled git repository
What am I missing here?

**Comment by rparolin** [comment]
The dependencies are in the test folder under packages.  It's not the most clear setup.  You have to include the include dir for the eabase package.
