### ISSUE TITLE
Natvis error triggered by eastl::VectorBase (VS 2015)

### ISSUE THREAD

**Issue by jlaumon** [electronicarts/EASTL#128]
Hello,

I sometimes get this error when debugging around code using eastl::vectors (and the debugger becomes terribly slow because of it):

	Error: The number of times a <DisplayString> or <ExpandedItem> element is needed to visualize a single object exceeds the maximum supported limit of 1000.  Please simplify your visualizations.

It happens frequently when an object inside the vector contains a pointer back to the vector (or to an object containing the vector.)

For example, let's say you have an entity-component-system and the entity has a vector of components. If the components also have a pointer to the entity, you will probably see this problem.

The origin of the problem seems to be the `DisplayStrings` in VectorBase that try to display the first 6 elements. The debugger stops trying to display the variables after a certain depth, but if there are more than one element in the vector, it's usually enough to trigger the error.

Here is a minimal/silly test that reproduces the problem:

```c++
struct A;

eastl::vector<A> global;

struct A
{
	A() : vector(&global) {}
	eastl::vector<A>* vector;
};

int main(int argc, char* argv[])
{
	global = { A(),A() }; // inspecting global after this point triggers the error
	return 0;
}
```

I'm not sure what the best solution is.
 - Remove the display of the elements in the `DisplayStrings` ? (It would be like the natvis for std::vector.)
 - Only show the elements if they are basic types? eg. int, float (But is that possible?)
 - Work around the problem by adding a custom view for the Entity class with a DisplayString that doesn't show the vector of components? (It's my current solution, but it's not easy to track all the classes that have this problem.)

What do you think? Has anyone else encountered this problem?

**Comment by rparolin** [comment]
I haven't seen any bug reports on this previously.  I'd hate to lose that natvis functionality for an (arguably) pathological use case.  Is that error you are experiencing fatal (ie. crashes visual studio)?  Or does the natvis simply fail to load?

**Comment by jlaumon** [comment]
No it doesn't crash, and the natvis even loads and works correctly, but stepping or clicking on variables in the debugger becomes very slow as soon as one of the problematic variables becomes visible (it freezes for a couple of seconds at every step/click).

I had to enable the natvis diagnostic messages to find the cause of the freezes. I'm guessing maybe other people have had the problem but never figured out the cause (especially since it's intermittent, the debugger becomes fast again as soon as the variable goes out of scope).

Anyway, I understand if you prefer to keep the functionality. At least now there's one report somewhere 😀

**Comment by rparolin** [comment]
For sure.  We could use as an example for MS.  Maybe they can provide more functionality to natvis to help fix this problem.

**Comment by rparolin** [comment]
I intend to close this issue as there is no action required.  Cool?

**Comment by jlaumon** [comment]
Yup.

**Comment by rparolin** [comment]
Thanks.
