### ISSUE TITLE
eastl::make_move_iterator name clash

### ISSUE THREAD

**Issue by eigenbom** [electronicarts/EASTL#130]
eastl::make_move_iterator name clashes with std::make_move_iterator, resulting in an ambiguous name lookup (ADL). compiler: VS2017 (v140), source: fixed_vector.h.

**Comment by rparolin** [comment]
What is your proposed fix?  If you are in an environment where you must use both std and eastl you will have to explicitly provide the namespace of the function you wish to call rather then relying on ADL or other name lookup rules as they will be correctly ambiguous.

**Comment by eigenbom** [comment]
I have no idea. Was hoping to use fixed_vector<std::pair>, for instance,
but it's a shame if I can't. Thanks anyway.

**Comment by rparolin** [comment]
Yeah, ADL works on function arguments not template arguments.
