### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [electronicarts/EASTL#132]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by rparolin** [comment]
I'm not familiar with conan, but ideally if someone wishes to have EASTL be distributed via conan it shouldn't impact the repo.  Unfortunately, I don't personally have the bandwidth to commit that it will updated with every release.
