### ISSUE TITLE
Buckaroo Package Manager Support

### ISSUE THREAD

**Issue by draygera** [electronicarts/EASTL#136]
Buckaroo is a C++ manager for Buck that makes it easier to install external libraries and headers into the current project. Why isn't it being used here?

**Comment by rparolin** [comment]
Nothing something I have experience with and there is a need to keep the amount of dependencies to a minimum.

**Comment by draygera** [comment]
Fair enough. If I or someone else were to get that setup for EASTL, would you be willing to merge it into the main branch? The main benefit would be to allow users to install EASTL into their external projects without having to worry about keeping this up to date.

**Comment by rparolin** [comment]
I've had similar requests (ie. buck build support) and what I've found is that it rots since no one is able to maintain it even with CI support.  I plan to remove the buck build files soon for that reason.  I'd prefer to not introduce anything that further complicates the maintenance of EASTL for other/future maintainers.

**Comment by draygera** [comment]
That makes so much sense. Thanks for the quick and well-thought out response. CMake is the de facto standard when it comes to build systems. I mainly have been looking at buck since I'm currently building my own game engine and wanted to try and use a different build system since, for me, CMake takes way too long to setup for my build structure.

**Comment by rparolin** [comment]
Agreed. We use a different build system internally so it is already 1 extra step for me to translate it to cmake.  Thanks for reaching out though.

**Comment by draygera** [comment]
No problem. Since you are planning on removing Buck anyways, if I do that for you, would you be willing to merge my commit?

**Comment by rparolin** [comment]
To remove buck?  Sure, but the CI step will have to be removed as well.

**Comment by draygera** [comment]
I've got two commits being pushed. The second one removed the CI steps too

**Comment by njlr** [comment]
For those who stumble on this, EASTL package for Buckaroo is now maintained here: https://github.com/buckaroo-pm/electronicarts-EASTL/
