### ISSUE TITLE
Use std::recursive_mutex when EASTL_CPP11_MUTEX_ENABLED is defined

### ISSUE THREAD

**Issue by Jasper-Bekkers** [electronicarts/EASTL#14]
Hi,

This tweet  https://twitter.com/jdryg/status/698042963604144128 and this one https://twitter.com/jdryg/status/698043020046921730 from Jim Drygiannakis seem to suggest it might be a good idea / preferable to use std::recursive_mutex instead of std::mutex as a fallback for eastl::mutex, since the implementations (both Windows & pthreads) of eastl::mutex seems to use recusive locking. 

I can't recall off the top of my head if eastl::mutex was always recursive, but I think it is / was on other platforms. What do you guys think?

**Comment by rparolin** [comment]
EASTL doesn't implement the any of the std::concurrency in the standard.  It implements enough for an internal API that drives features like eastl::shared_ptr.  Using a std::recursive_mutex would be preferable as long its available for use on all compilers.
