### ISSUE TITLE
EASTL for Windows

### ISSUE THREAD

**Issue by losnat** [electronicarts/EASTL#141]
Hello,
I have a question regarding building and using EASTL on Windows.
I ran cmake without modifying config.h and then tried to build it with Visual Studio 2013.
The build resulted with several compilation errors.
So, my questions:
1. Which Visual Studio versions are supported?
2. I saw the config.h file had several defines that suggest it may be possible to use older compilers, for example EASTL_STD_CPP_ONLY, EASTL_MOVE_SEMANTICS_ENABLED. However, defining those constants doesn't seem to eliminate the errors. Is there a set of defines that I can use with Visual Studio 2013?

**Comment by rparolin** [comment]
VS2013 support was not explicitly removed but we no longer test against it;
internally or on the public CI.

Currently, VS2015 and VS2017 are supported.

**Comment by losnat** [comment]
ok. Thank you!
