### ISSUE TITLE
FAQ is out of date regarding C++-Features

### ISSUE THREAD

**Issue by fkorak** [electronicarts/EASTL#148]
The FAQ is a little out of date regarding some changes to the C++-Standard in recent years. 

> <p class="faq-answer">With respect to item 3, there are a number of facilities that EASTL has that STL doesn't have, such as intrusive_list and slist containers, smart pointers, and type traits. All of these are facilities that assist in making more efficient game code and data.</p>

> Of these, the last two (smart pointers and type traits) do not have analogs in standard C++.

As far as I can tell type_traits were [added to the standard in C++11 and extended in C++17](http://en.cppreference.com/w/cpp/header/type_traits).  Also there is [shared_ptr](http://en.cppreference.com/w/cpp/memory/shared_ptr) as a language feature in C++11.

The compiler support section might also need some cleanup. The supported versions are listed as MSVC 7+ from 2002 and GCC 3+ neither of which are really supported by vendors anymore.

**Comment by rparolin** [comment]
I've made the relevant edits and they will be included in the next EASTL release.  In future please consider submitting a PR.
