### ISSUE TITLE
don't have a function corresponding to InterlockedExchangeAdd.

### ISSUE THREAD

**Issue by chena1982** [electronicarts/EASTL#150]
EASTL have atomic function, for example, atomic_increment(), but don't have a atomic function corresponding to InterlockedExchangeAdd.

ps, also don't have some function support thread local storage.
Has some plane to support these?
Thanks.

**Comment by rparolin** [comment]
EASTL doesn't implement the std::atomic API.  We just implement enough atomics to provide a portable implementation of eastl::shared_ptr.  This atomics API is not intended to be an internal implementation detail of EASTL.  

In the future, we may provide an atomics API within EASTL or another seperate library but we haven't thought about it to a significant amount of detail yet.
