### ISSUE TITLE
Do the fixed size maps even work ?

### ISSUE THREAD

**Issue by RaviBeagle** [electronicarts/EASTL#166]
I am trying to use the fixed size maps in an application. But they seem to be using the default allocator instead of the fixed size allocator. So I get these linker errors'

C:/Users/ravredd/workspace/EASTL_Testing2/include/EASTL/internal/red_black_tree.h:1994: undefined reference to `eastl::allocator::deallocate(void*, unsigned int)'
Av3Reconstructor.o: In function `ZN5eastl15allocate_memoryINS_9allocatorEEEPvRT_jjj':
C:/Users/ravredd/workspace/EASTL_Testing2/include/EASTL/allocator.h:370: undefined reference to `eastl::allocator::allocate(unsigned int, int)'
C:/Users/ravredd/workspace/EASTL_Testing2/include/EASTL/allocator.h:378: undefined reference to `eastl::allocator

And if in config.h

#ifndef EASTLAllocatorType
	#define EASTLAllocatorType eastl::allocator
#endif

If changed to eastl::fixed_allocator, it gives me a compilation error:

C:\Users\ravredd\workspace\EASTL_Testing2\include/EASTL/internal/config.h:1708:36: error: 'fixed_allocator' in namespace 'eastl' does not name a type
  #define EASTLAllocatorType eastl::fixed_allocator

I have to build an application where there will be ABSOLUTELY NO dynamic memory allocation.

**Comment by billyquith** [comment]
> If changed to eastl::fixed_allocator, it gives me a compilation error:

It sounds like you didn't include the fixed_allocator header, so when used, the compiler hasn't seen that type before.

**Comment by RaviBeagle** [comment]
Nope. Even when I include #include <EASTL\fixed_allocator.h> in all places where #Include <EASTL\alloctaor.h> is there still this problem occurs

**Comment by RaviBeagle** [comment]
Any one else using the EASTL without ANY dynamic memory allocation ?

**Comment by rparolin** [comment]
I guess it depends on what you mean.  There are custom EASTL containers that will not dynamically allocate memory based on config.  We don't go as far to ensure that calls to memory allocation functions are not compiled.

**Comment by RaviBeagle** [comment]
Ok. Then this issue can be closed. Thank you.
