### ISSUE TITLE
EASTL failed with error C3861 when build with permissive- by msvc on Windows

### ISSUE THREAD

**Issue by QuellaZhang** [electronicarts/EASTL#171]
EASTL failed with error C3861 when build with permissive- by msvc on Windows, I use latest source on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior. Thanks in advance!

**You can repro this issue as the steps below:**

1. git clone  https://github.com/electronicarts/EASTL  D:\EASTL\src
2. open a VS 2017 x86 command prompt as admin and browse to D:\EASTL\src
3. set _CL_=/permissive-
4. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.16299.0 -DEASTL_BUILD_TESTS:BOOL=ON ..\src\

**Error info:**
D:\EASTL\src\test\..\include\EASTL/internal/fill_help.h(444): error C3861: '__stosd': identifier not found
D:\EASTL\src\test\..\include\EASTL/internal/fill_help.h(444): note: '__stosd': function was not declared in the template definition context and can be found only via argument-dependent lookup in the instantiation context
D:\EASTL\src\test\..\include\EASTL/array.h(146): note: see reference to function template instantiation 'int32_t *eastl::fill_n<size_t,int>(int32_t *,Size,Value)' being compiled
        with
        [
            Size=size_t,
            Value=int
        ]
D:\EASTL\src\test\..\include\EASTL/array.h(145): note: while compiling class template member function 'void eastl::array<int,1>::fill(const int &)'
D:\EASTL\src\test\source\TestArray.cpp(18): note: see reference to class template instantiation 'eastl::array<int,1>' being compiled

**Comment by PhoebeHui** [comment]
Any updates?

**Comment by QuellaZhang** [comment]
Any updates?

**Comment by rparolin** [comment]
Sorry for the delay in response.

Permissive is a high priority for me because prevents code compiling via MS extensions that hurt portability.

**Comment by rparolin** [comment]
I enabled /permissive- on the CI and I submitted fixes.
