### ISSUE TITLE
Host docs

### ISSUE THREAD

**Issue by morenoh149** [electronicarts/EASTL#18]
Could the docs be hosted on github pages or somewhere accessible? https://github.com/electronicarts/EASTL/tree/master/doc

**Comment by rparolin** [comment]
It's something I'm looking into.  I have to maintain this documentation standard internally so something that automatically converts to markdown would have to be done.  I'd be interested to hear ideas but it hasn't been a priority to fix yet.

**Comment by morenoh149** [comment]
the github pages route you don't have to convert to markdown. It's essentially static file hosting.

You probably want to make an index.html file at that directory or rename the introduction to index. Then pull the files in the `doc` directory into a separate branch. https://help.github.com/articles/creating-project-pages-manually/

**Comment by mgiuffrida** [comment]
meantime, you can just use rawgit.com, e.g.:

https://rawgit.com/electronicarts/EASTL/master/doc/EASTL%20FAQ.html

**Comment by rparolin** [comment]
I added a rawgit link to the readme.
