### ISSUE TITLE
Benchmark source files don't compile

### ISSUE THREAD

**Issue by guykogus** [electronicarts/EASTL#19]
They are using an old API: `EA::StdC::Stopwatch::Restart`
and **main.cpp** is trying to include `PPMalloc/EAGeneralAllocatorDebug.h`, which doesn't exist.

**Comment by jpark37** [comment]
I tried to run the benchmarks too and saw the same issues. I think EASTL_OPENSOURCE needs to be 1. That and a trivial Stopwatch implementation seems to do the trick.

**Comment by rparolin** [comment]
The benchmarks haven't been ported to cmake yet.  The simple stopwatch
implementation is in EAStdc in the test/packages folder.

**Comment by rparolin** [comment]
Linux/OSX needs clock frequency code but other than that the benchmarks project is building.

**Comment by swardle** [comment]
Nice work. 

Scott

**Comment by rparolin** [comment]
Cheers, Scott.
