### ISSUE TITLE
eastl::vector::resize() debug build performance for PODs is slow

### ISSUE THREAD

**Issue by Vuhdo** [electronicarts/EASTL#200]
Hi,

I was using a vector as a temp buffer and noticed pretty hard performance hit in a *debug build*:
```
eastl::vetor<uint8_t> temp;
for (...) {
    size_t dataSize = GetDataSize();
    temp.resize(dataSize);   <--- SLOW when dataSize is high enough
    process(temp.data());
}
```
Actually the cost of `resize()` in my debug build was sometimes even higher than the cost of `process()`.
I guess the reason is that `vector::resize()` calls to `uninitialized_default_fill_n()` which is not specialized for PODs and therefore might get very slow when compiler optimizations are disabled.

**Comment by rparolin** [comment]
```	template <typename ForwardIterator, typename Count>
	inline void uninitialized_default_fill_n(ForwardIterator first, Count n)
	{
		typedef typename eastl::iterator_traits<ForwardIterator>::value_type value_type;
		Internal::uninitialized_default_fill_n_impl(first, n, **is_scalar**<value_type>());
	}
```
There is an optimized path but it branches on if the type is a scalar type.
https://howardhinnant.github.io/TypeHiearchy.pdf

That should be sufficient for your example of eastl::vector<uint8_t>.  Is the issue that is_scalar is return false on uint8_t and therefore picking the wrong implementation?

**Comment by rparolin** [comment]
Reopen this ticket or submit another issue if its an issue with is_scalar type_trait.
