### ISSUE TITLE
Implement initializer_list support for tuple_vector

### ISSUE THREAD

**Issue by CypherSignal** [electronicarts/EASTL#204]
Expected support should mimic std::vector's interface. That is, the following functions should be added to tuple_vector:

```
tuple_vector<Ts...>(std::initializer_list<value_tuple> iList)
operator=(std::initializer_list<value_tuple> iList)
void assign(std::initializer_list<value_tuple> iList)
const_iterator insert(const_iterator pos, std::initializer_list<value_tuple> iList)
```

**Comment by CypherSignal** [comment]
Work on this is proceeding in https://github.com/CypherSignal/EASTL/tree/tuple_vec-initlist 

A first interface implementation and test-cases are committed already: https://github.com/CypherSignal/EASTL/commit/5facb9b307c2d3292e6ef41f3fbc07edfbf7c818

Besides the functions above, the following have been added as a corollary, since they probably make some sense to have anyway:

```
tuple_vector<Ts...>(const value_tuple* begin, const value_tuple* end)
void assign(const value_tuple* begin, const value_tuple* end)
const_iterator insert(const_iterator pos, const value_tuple* begin, const value_tuple* end)
```

These would allow a developer to more easily insert/assign an array of tuples into tuple_vector instead of doing so one-at-a-time w/ insert or push_back.

There is one issue seen early on, though, with the setup of the initializer_list: because tuple's construction via copy-list-initialization requires explicit use of the constructor, resulting in the init-lists looking like this, more-or-less:

```
			tuple_vector<bool, TestObject, float> testVec;
			tuple<bool, TestObject, float> testTup;

			testTup = tuple<bool, TestObject, float>(true, TestObject(3), 3.0f);
			testVec.insert(testVec.begin(), { 
				tuple<bool, TestObject, float>{true, TestObject(3), 3.0f},
				tuple<bool, TestObject, float>{true, TestObject(3), 3.0f}
				testTup,
				});
```

...that is, for any statically defined tuple, the type of the tuple has to be provided for each initializer. I haven't thought too much about it so far, and maybe there's a way out of this that would involve changing exactly what the initializer_list that is accepted is, but nothing's leaping to mind yet.

**Comment by CypherSignal** [comment]
Updated https://github.com/CypherSignal/EASTL/tree/tuple_vec-initlist to https://github.com/CypherSignal/EASTL/commit/53abf7f5476cc563c4f366243ac82bd80c9ad2a3 s.t. it now passes all test cases. I'll wait until https://github.com/electronicarts/EASTL/pull/203 is filed before I submit this as a PR, both because tuple_vec-initlist will need to be updated with the content from https://github.com/electronicarts/EASTL/pull/203, but also to stew on the initializer_list interface a bit.

**Comment by CypherSignal** [comment]
Okay, so apparently tuple in cpp17 was updated to be _conditionally_ explicit: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4387.html

If there's no objection, I will prepare a pair of constructors for eastl::tuple that includes this functionality. It would allow the init-list to look like this (and fix some other similarly awkward cases of not being able to easily return an init-list for functions that return tuples).

**Comment by CypherSignal** [comment]
https://github.com/electronicarts/EASTL/commit/90bb518b017edc18f0ee74d305ee6cbccea2cd8e now includes support for tuples to be constructed implicitly if the types are an exact match.

For example, this will now compile:
```
			tuple_vector<bool, TestObject, float> testVec;
			tuple<bool, TestObject, float> testTup;

			// test insert on empty vector that doesn't cause growth
			testTup = tuple<bool, TestObject, float>(true, TestObject(3), 3.0f);
			testVec.insert(testVec.begin(), { 
				{true, TestObject(3), 3.0f},
				{true, TestObject(3), 3.0f}
				testTup,
				});
```

BUT, thankfully, this will not:
```
			tuple_vector<bool, TestObject, float> testVec;
			tuple<bool, TestObject, float> testTup;

			// test insert on empty vector that doesn't cause growth
			testTup = tuple<bool, TestObject, float>(true, TestObject(3), 3.0f);
			testVec.insert(testVec.begin(), { 
				{true, 3, 3.0f},
				{true, 3, 3.0f}
				testTup,
				});
```

**Comment by rparolin** [comment]
Cpp17 allows class template deduction so that should simplify these
examples.  We may need to include template deduction guides for that.

**Comment by CypherSignal** [comment]
Refreshed the PR. Seems to be compile on gcc/clang now, but there's a couple issues with MSVC 2015 that needs some investigation, it looks like.

**Comment by CypherSignal** [comment]
The crux of the exact compilation failures being encountered is around the MSVC 2015 compiler trying to instantiate the is_constructible type-trait, and as a part of that, creates a function that requires a parameter with an aligned type. The immediate patch to fix the unit-tests could just be "dump the current is_constructible impl, and instead rely on the compiler intrinsic", but a quick sanity check of other problems where this compilation error comes up suggests that MSVC 2015 just can't handle things in this regard as well as MSVC 2017, or clang/gcc. For example, if you tack "EA_ALIGN(16)" onto a common type such as TestObject in EASTLTest.h, or basic_string, there are many other, similar, compilation errors that will arise, independent of any changes I've been doing to tuple or tuple_vector. Ultimately, the test-cases as they are would be resolved, but a user could run into problems as they use the container through no fault of their own. Though, it seems fixing is_constructible seems to suffice.

So, since this would be an even deeper change, I would like to request a specific thumbs up or down on this before I go ahead and push an update: the PR could, as a final note, also include a fixup to is_constructible in https://github.com/electronicarts/EASTL/blob/master/include/EASTL/internal/type_pod.h#L768 to basically just be:
```
	// is_constructible
	template<typename T, typename... Args>
	struct is_constructible : public bool_constant<__is_constructible(T, Args...) > {};
```
...under appropriate circumstances (MSVC since at least VS2013) and clang (`__has_feature(__is_constructible)`). Other compilers can fallback to the hand-rolled implementation, no problem, and don't have an issue with the aligned types anyway. It's just VS2015 and earlier, it seems.

Otherwise, I'll have to cordon off the offending test case for when on VS2015 or lower, and say "the eastl impl of tuple_vector (and tuple's I guess) don't support aligned data types".

**Comment by rparolin** [comment]
Sure.  That's exactly how I would have gone about doing it.
