### ISSUE TITLE
Please have an option to build the shared library

### ISSUE THREAD

**Issue by yurivict** [electronicarts/EASTL#210]
On many systems shared libraries are preferred, and it should be possible to build using a cmake option.

**Comment by rparolin** [comment]
The few cpps in the project you could build as a DLL.  If you want to write a PR I'd be interested in seeing it.

**Comment by yurivict** [comment]
https://github.com/electronicarts/EASTL/pull/226

**Comment by rparolin** [comment]
Closing because #226 was closed.
