### ISSUE TITLE
Create function from lambda

### ISSUE THREAD

**Issue by nickclark2016** [electronicarts/EASTL#214]
I'm trying to create a function from a lambda like so:

```cpp
template <typename Type>
struct EventCallback
{
	explicit EventCallback(eastl::function<void(const Type&)> aCallback)
		: callback(aCallback)
	{			
	}

	eastl::function<void(const Type&)> callback;
};
...
auto func = [aReceiver, receive](const EventType & aEvent) mutable { 
    aReceiver.receive(aEvent)
}; 
EventCallback<EventType> wrapper(func);
```

However, when `func` gets cleaned up, the destructor throws an error.  Is there another way that I should be going to construct this function, or is this a bug?

**EDIT:** This seems to not be the case when I am doing this in the main function.  Is there some nuanced thing I am missing with `eastl::function`?

**Comment by rparolin** [comment]
I'm not following your test case.  Can you provide an example that shows the object lifetime of the instance "wrapper"?

**Comment by nickclark2016** [comment]
I would be using wrapper like:
```cpp
subscribe(...) {
    ...
    auto func = [aReceiver, receive](const EventType & aEvent) mutable { 
        aReceiver.receive(aEvent)
    }; 
    EventCallback<EventType> wrapper(func);
    ...
}
```

**Comment by rparolin** [comment]
What error are you seeing?  What dtor is generating the error?  the dtor from the lambda? or the dtor from the EventCallback type?

**Comment by nickclark2016** [comment]
No error message of interest.  I found a way around this, but I wanted to bring it up.  The error was caused on destruction of the lambda.

**Comment by rparolin** [comment]
K.  I'll close it for now.  If you can provide a test case that shows the
error then I'll look at it again .
