### ISSUE TITLE
eastl::any pointer to stored value

### ISSUE THREAD

**Issue by martty** [electronicarts/EASTL#219]
Although this feature was not standardised, `boost::any` has a way to acquire a pointer to the stored value. Admittedly, this operation is somewhat unsafe, but I think it removes an impedance mismatch, where one has functions that operate on type-erased `void*` pointers, which could also source their arguments from `any`. I think of this operation as the analogue of acquiring the `T*` of the `unique_ptr<T>`.

The implementation is quite trivial, but maybe there are arguments against this feature. It would also be a strict addition to the C++ standard STL.

Would there be support for adding this feature?

**Comment by rparolin** [comment]
If want to a pointer to the contained object I believe you can achieve via:

```    // pointer to contained data
    eastl::any a = 1;
    int* i = eastl::any_cast<int>(&a);
    std::cout << *i << "\n";```

I took the example from cppreference: https://en.cppreference.com/w/cpp/utility/any

**Comment by martty** [comment]
True, but I can't get this pointer if I don't know the contained type (I can't even get a `void*`). Getting the pointer during construction and keeping it around is both dangerous and cumbersome (apart from needing to put the `any` on the heap).

**Comment by rparolin** [comment]
Can you point me to the boost documentation for this?  I took a look at https://www.boost.org/doc/libs/1_68_0/doc/html/boost/any.html but I didn't see what you are refering to.

**Comment by martty** [comment]
It is not part of the (documented) public interface, but available here: https://github.com/boostorg/any/blob/develop/include/boost/any.hpp#L317

**Comment by rparolin** [comment]
Ah, I see.  Sure I'd be open to this change.

**Comment by rparolin** [comment]
Are you interested in submitting a PR?

**Comment by martty** [comment]
Sorry, I did not have time recently to work on this. Thank you @jatinx for submitting the PR, it is what I had in mind.
