### ISSUE TITLE
Is Cmake 3.4 really required?

### ISSUE THREAD

**Issue by philix** [electronicarts/EASTL#22]
I'm running Cmake 3.1.3 on my Mac OS X and the latest version available on homebrew for easy installation is 3.3.

Latest version on [Ubuntu launchpad](https://launchpad.net/ubuntu/+source/cmake) is 3.3.2.

Requiring an older version would make EASTL pain-free to build if no v3.4-specific feature is being used.

**Comment by rparolin** [comment]
It was simply that I used CMake 3.4 to prep the code that went on github.  I haven't tested it with any other version.  Patches welcome. :)
