### ISSUE TITLE
malloc.h is obsolete

### ISSUE THREAD

**Issue by yurivict** [electronicarts/EASTL#229]
```
In file included from /usr/ports/devel/eastl/work/EASTL-3.12.04/test/source/TestAllocator.cpp:8:
In file included from /usr/ports/devel/eastl/work/EASTL-3.12.04/test/../include/EASTL/allocator_malloc.h:39:
/usr/include/malloc.h:3:2: error: "<malloc.h> has been replaced by <stdlib.h>"
#error "<malloc.h> has been replaced by <stdlib.h>"
 ^
```

You may want to change ```include/EASTL/allocator_malloc.h``` because ```malloc.h``` is obsolete.

FreeBSD 11.2 amd64

**Comment by rparolin** [comment]
Sure.  Feel free to submit a PR.

**Comment by rparolin** [comment]
Would you like to submit a PR for this issue?

**Comment by rparolin** [comment]
Reopen issue if you are interested in submitting a PR.

**Comment by yurivict** [comment]
Normally, project maintainers are supposed to make such changes. I only have resources to maintain the port, and can't be fixing issues for upstreams.
