### ISSUE TITLE
Possible memory leak on string's size constructor

### ISSUE THREAD

**Issue by muit** [electronicarts/EASTL#234]
Hi!
I think I have found a possible memory leak which I am sure you are able to confirm or show me what I am doing wrong.

```c++
template <typename T, typename Allocator>
inline basic_string<T, Allocator>::basic_string(size_type n, value_type c, const allocator_type& allocator)
		: mPair(allocator)
{
	SizeInitialize(n, c);
}
```
SizeInitialize seems to initialize with size n but not free the memory on destruction.

This issue seems to be reproduced with just:
```c++
{
    eastl::string s = eastl::string(512, 'c');
}
```
PD: Just in case, I use a custom allocator for all the application that points to eastl's malloc allocator. The profiler on my allocator indicates this memory leak.

**Comment by muit** [comment]
Having a similar issue with:
```c++
template <typename T, typename Allocator>
basic_string<T, Allocator>& basic_string<T, Allocator>::append(const value_type* pBegin, const value_type* pEnd)
```
and
```c++
template <typename T, typename Allocator>
void basic_string<T, Allocator>::resize(size_type n, value_type c)
```

Its very strange that a common feature like this can have such a problem, but the version of EASTL I am using is 3.12.04 non modified. (Previous version had the same problem)

**Comment by muit** [comment]
Hi @rparolin,

Yes, it allocates the desired memory, but when destroyed (out of scope) it doesnt get freed.

You can reproduce it with:
```c++
{
    eastl::string s = eastl::string(512, 'c');
}
```

If you want to have a test environment, you can:
- Download branch: https://github.com/muit/fecoengine/tree/hotfix/StringLeak
- Run Generate.bat
- You now have the sln and can compile and run the program
- On this branch the memory leak is enabled on tick and you can see how memory starts going up.
- Exact line is *Source/Engine/Engine.h:84*
- You can also run "Programs/profiler/Tracy.exe" for more details

I've been thinking it may be because of my new and delete overrides, so to make sure I put them here:
```c++
// EASTL News
void* operator new[](size_t size, const char* /*name*/, int flags,
	unsigned /*debugFlags*/, const char* /*file*/, int /*line*/)
{
	return Memory::GetAllocator()->Allocate(size, flags);
}

void* operator new[](size_t size, size_t alignment, size_t alignmentOffset, const char* /*name*/,
	int flags, unsigned /*debugFlags*/, const char* /*file*/, int /*line*/)
{
	return Memory::GetAllocator()->Allocate(size, alignment, alignmentOffset, flags);
}


// Native News
void* operator new(size_t size)
{
	return Memory::GetAllocator()->Allocate(size);
}

void* operator new[](size_t size)
{
	return Memory::GetAllocator()->Allocate(size);
}


// Deletes
void operator delete(void* p, std::size_t size)
{
	Memory::GetAllocator()->Deallocate(p, size);
}

void operator delete[](void* p, std::size_t size)
{
	Memory::GetAllocator()->Deallocate(p, size);
}
```

Thanks for the help!
muit

**Comment by rparolin** [comment]
Sorry.  I can't debug your project.  Can you please create a test case that shows this bug as part of the EASTL unit tests?

**Comment by muit** [comment]
Well I guess I can.
Do you have any built-in tool for checking memory leaks on tests? Like an allocator.

I can do one, just want to make sure I don't duplicate stuff.

**Comment by rparolin** [comment]
I'm going to close this issue.  Please reopen it when you have a test case that shows the memory leak.

**Comment by muit** [comment]
I added 3 tests on the PR. All 3 seem to share the same problem.

**Comment by rparolin** [comment]
See my comments on the PR.  We can re-open the issue if there is more information but as far as I can tell there isn't a memory leak here.
