### ISSUE TITLE
wstring_convert & codecvt support

### ISSUE THREAD

**Issue by muit** [electronicarts/EASTL#245]
Hi guys,

I was wondering why EASTL didn't have **wstring_convert** and **codecvt** features.
I just realized this tool wasn't unfortunately there when trying to convert wide to utf8 eastl strings.

Is it because of any particular reason?
Otherwise, if I can ask, do you know any other alternative?

Thanks,
muit

**Comment by rparolin** [comment]
https://en.cppreference.com/w/cpp/locale

EASTL never aimed to replace the localization libraries provided by the platform.  eastl::basic_string does provide some non-standard APIs inorder to convert from various character widths.  Namely, assign_convert, append_convert, and ctor overloads that require you to pass the "CtorConvert" tag type.
