### ISSUE TITLE
Can I specify default allocator per EASTL type?

### ISSUE THREAD

**Issue by Vuhdo** [electronicarts/EASTL#247]
Hi,

Is it possible to change default allocator for a specific container type? Say, for example, I want to make all eastl::strings to use an allocator different to what all eastl::vectors use by default (i.e. I want to use an isolated memory heap for all strings).

There is `EASTL_BASIC_STRING_DEFAULT_ALLOCATOR` macro that looks like it might be what I need. But then eastl::string's default ctor (`basic_string::basic_string()`) does not use the macro, so I'm a bit confused.

**Comment by rparolin** [comment]
That is a convenience macro for the string implementation so that the allocator name is passed.  Its not intended to be a user customization point.  Currently, the recommend usage is similar to the std library is use a template alias for basic_string.

```
using my_string_tyype = eastl::basic_string<char, my_allocator_type>;
```
