### ISSUE TITLE
string_view/wstring_view from string literal

### ISSUE THREAD

**Issue by JohanEffektfabriken** [electronicarts/EASTL#250]
Hello,
It is impossible create a constexpr string_view from a string literal without providing the length. Using MSVC

```c++
struct SomeConstants
{
    // C2131: expression did not evaluate to a constant
    static constexpr const eastl::wstring_view kTest = L"kTest"; 

    // Ok
    static constexpr const eastl::wstring_view kTest = eastl::wstring_view(L"kTest", 5); 
}
```

The reason is calling non-constexpr function _CharStrlen_
```c++
EA_CONSTEXPR basic_string_view(const T* s) : mpBegin(s), mnCount(s != nullptr ? CharStrlen(s) : 0) {}
```

**Comment by Alan5142** [comment]
You can fix that adding `EA_CONSTEXPR` to `CharStrlen`
![fix](https://user-images.githubusercontent.com/13205973/50732041-dec77d80-1137-11e9-90bd-0110998aaa32.png)
Also i think that a lot of functions from char_traits must be constexpr

**Comment by rparolin** [comment]
Would you like to submit a PR?
