### ISSUE TITLE
False C4100 warning in internal_destroy when compiling under MS VS2015

### ISSUE THREAD

**Issue by davepoo** [electronicarts/EASTL#251]
The following false error can occur when compiling on VS2015 with "/W4 /WX" parameters.
It claims the parameter is not used (even though it is).

_internal/allocator_traits.h(382): warning C4100: 'p': unreferenced formal parameter (compiling source file ...)_

`
internal/allocator_traits.h

	    template <class T>
	    static void internal_destroy(eastl::false_type, allocator_type&, T* p) { p->~T(); }
`
This appears to be a known issue with the compiler, and requires the same fix "EA_UNUSED(p);" that is already in use in _destruct(T* p)_ in _memory.h_

`
	    template <class T>
	    static void internal_destroy(eastl::false_type, allocator_type&, T* p) { EA_UNUSED(p); p->~T(); }
`

**Comment by rparolin** [comment]
I've resolved this issue.  It will be included in the next EASTL release.  Thanks.

**Comment by davepoo** [comment]
Thank you.
