### ISSUE TITLE
Variant requires copyable types even when never copied

### ISSUE THREAD

**Issue by Const-me** [electronicarts/EASTL#253]
In `variant.h` you have following method:

		template<typename T>
		static void DoOpImpl(StorageOp op, T* pThis, T* pOther)

You instantiate that method for each type and store the function pointer in the `mpHandler` field of the variant.

In that method, there’s a line that says 

				case StorageOp::COPY:
				{
					new (pThis) T(*pOther);
				}
				break;

This doesn’t compile if class T says “T( const T& ) = delete;” At least not in VC2017.

Here’s an essence of the compiler output:

eastl\variant.h(233): error C2280: 'C2::'C2(const C &)': attempting to reference a deleted function
c.hpp(18): note: see declaration of ''C2::'C2'
c.hpp(18): note: ''C2::'C2(const C &)': function was explicitly deleted
eastl\variant.h(282): note: see reference to function template instantiation 'void eastl::variant_storage<false,C1,C2,C3>::DoOpImpl<RT>(eastl::variant_storage<false,C1,C2,C3>::StorageOp,T *,T *)' being compiled
eastl\variant.h(292): note: see reference to function template instantiation 'void eastl::variant_storage<false,C1,C2,C3>::DoOpImpl<RT>(eastl::variant_storage<false,false,C1,C2,C3>::StorageOp,T *,T *)' being compiled
eastl\variant.h(737): note: see reference to function template instantiation 'void eastl::variant_storage<false,C1,C2,C3>::set_as<T,>(void)' being compiled
eastl\variant.h(742): note: see reference to function template instantiation 'void eastl::variant_storage<false,C1,C2,C3>::set_as<T,>(void)' being compiled
eastl\variant.h(707): note: see reference to function template instantiation 'C2 &eastl::variant<C1,C2,C3>::emplace<1,,C2,void>(void)' being compiled
eastl\variant.h(708): note: see reference to function template instantiation 'C2 &eastl::variant<C1,C2,C3>::emplace<1,,C2,void>(void)' being compiled

**Comment by rparolin** [comment]
Sorry for the delay in response.  Would you like to contribute a PR?

**Comment by rparolin** [comment]
I resolved this.  It will be included in the next release of EASTL.
