### ISSUE TITLE
Benchmark comparasion, libstdc++ is shared obj, while EASTL is staticaly link.

### ISSUE THREAD

**Issue by stayprivate** [electronicarts/EASTL#255]
Hello,
In the benchmark, the comparison is done with libstdc++ which is a shared library.  But the EASTL is linked statically. Since the bulk of the code is in header file most of the benchmark are unaffected.  But for some it seems to make a significant difference.

**Comment by rparolin** [comment]
Can you provide more details?  I'm not sure what change you are proposing.

**Comment by stayprivate** [comment]
In root CMakefile I added SHARED to the add_library(EASTL ${EASTL_SOURCES}) to make the benchmark use a shared library. I could have set libstdc++ to be link statically, but I did not know how to do that on top of my head so went the easy route.

That's major nitpicking though, probably not worth worrying about, sorry for the trouble.
