### ISSUE TITLE
Can't compile with gcc 4.8

### ISSUE THREAD

**Issue by stayprivate** [electronicarts/EASTL#259]
Hi,

I can't find any official statement about supported compiler version, but it does not compile with gcc 4.8.5. Is it worth giving the details of the problem or 4.8 is too old to supported?

Regards,
- Mario

**Comment by rparolin** [comment]
https://gcc.gnu.org/gcc-4.8/
Given the 4.8.5 was released in 2015, I'd lean towards saying its too old; however its hard to say without knowing the specifics of the error.  Because it could potentially warrant taking the fix if its generally applicable.

**Comment by stayprivate** [comment]
Seems like the last version of EASTL that build with 4.8.5 is 3.07.01 (.02 does not)

Ok I got more detail, the issue seems not directly related to the version gcc, but usage of C++11.  If I use gcc8 but modify CommonCppFlags to force C++11 I get the same problem. 

With 3.12.08, in type_fundamental_h line 38
```
	#if EASTL_VARIABLE_TEMPLATES_ENABLED
		template <class T>
		EA_CONSTEXPR bool is_void_v = is_void<T>::value;
	#endif
```
Because of C++11 EASTL_VARIABLE_TEMPLATES_ENABLE ends up not defined, hence is_void_v is not created.  Yet at line 224 there is template that used is_void_v which is nowhere to be found since it's C++17, resulting in compiler error. 

```

template <typename T>
	struct is_fundamental
		: public bool_constant<is_void_v<T> || is_integral_v<T> || is_floating_point_v<T> || is_null_pointer_v<T>> {};

```

Thanks.

**Comment by rparolin** [comment]
EASTL requires C++14 currently.  We don't intentionally break C++11 but we don't test against it or provide any guarantees that we build in C++11 mode.

**Comment by stayprivate** [comment]
Thanks.
