### ISSUE TITLE
#define EASTL_STRING_OPT_CHAR_INIT 0 leads to compilation error

### ISSUE THREAD

**Issue by xzn** [electronicarts/EASTL#261]
It seems there isn't a `this_type& append(size_type n);` for string.h

**Comment by rparolin** [comment]
Odd.  There is such overload defined by the standard.  I'd imagine that feature define hasn't been used for a while.  I'd be inclined to remove that code from eastl::string.

**Comment by rparolin** [comment]
This will be included in the next release.
