### ISSUE TITLE
Issue eastl::map with only movable types

### ISSUE THREAD

**Issue by JohanEffektfabriken** [electronicarts/EASTL#262]
Hello,

Discovered a issue with eastl::map when using types which are not copyable but movable. Issue is with a branch in the swap-function of the red_black_tree class (case: when the allocators are not equal). However the compiler (MSVC) consider this branch eventhough the allocators are the same and produces:

_eastl::pair<const Key,T>::pair(const eastl::pair<const Key,T> &)': attempting to reference a deleted function_ 

This example highlights the problem (the code just have to exist and must not be used to produce the prolem), 
```c++
struct OnlyMovable
{
    OnlyMovable() = default;

    OnlyMovable(OnlyMovable&&) = default;
    OnlyMovable(const OnlyMovable&) = delete;
    OnlyMovable& operator=(const OnlyMovable&) = delete;
    OnlyMovable& operator=(OnlyMovable&&) = default;

    ~OnlyMovable() = default;
};

class Container
{
public:
    Container(eastl::map<eastl::wstring, OnlyMovable> pOnlyMovables)
        : mOnlyMovables(eastl::move(pOnlyMovables))
    {
    }

private:
    eastl::map<eastl::wstring, OnlyMovable> mOnlyMovables;
};
```

Problematic part:

```c++
template <typename K, typename V, typename C, typename A, typename E, bool bM, bool bU>
void rbtree<K, V, C, A, E, bM, bU>::swap(this_type& x)
{
    if(mAllocator == x.mAllocator) // If allocators are equivalent...
    {
       // ... 
    }
    else
    {
        *// This wil call the deleted copy constructor
        const this_type temp(*this); // Can't call eastl::swap because that would
        *this = x;                   // itself call this member swap function.
         x    = temp;
   }
}
```

**Comment by rparolin** [comment]
Thanks for reporting this.

**Comment by rparolin** [comment]
This will be fixed in the next release version of EASTL.

**Comment by jeremyong** [comment]
FYI I'm seeing this on the latest MSVC builds with hash_map and vector types (compiling with C++20)
