### ISSUE TITLE
eastl::tuple_cat works only on movable tuples

### ISSUE THREAD

**Issue by ArcadesSaboth** [electronicarts/EASTL#263]
Hello,
I was working with a combination of tuples and **eastl::apply** and since this one accepts only one tuple I used **eastl::tuple_cat**. However it seems the **eastl::tuple_cat** works only on movable tuples.

Consider the following code:
```
struct Empty
{};

int main()
{
	Empty* empty = nullptr;
	auto tuple = eastl::make_tuple(empty, true);
	auto tuple_cat = eastl::tuple_cat(eastl::make_tuple("asd", 1), tuple);

}
```
won't compile with an incredible long list of errors, mostly because tuple_cat2 is private.
I found out that if you move the last tuple, it works:
```
auto tuple_cat = eastl::tuple_cat(eastl::make_tuple("asd", 1), eastl::move(tuple));
````
Note that **std::tuple_cat** has no problems with the above and will copy the elements as expected, while moving the tuple will instead move the elements (tested with Clang and MSVC).
This also means that your **TestTuple.cpp** is incomplete (in fact it will pass its tests but not the above one).

Sorry, I don't have the time to find the actual issue but I hope the above information help.

**Comment by rparolin** [comment]
The compiler error doesn't have anything to do with moveable types.  It was the lvalue reference support for 'tuple_cat'.  We only had tests that pass rvalue references to tuple_cat.  

Thanks for reporting.  This will be fixed in the next release.
