### ISSUE TITLE
-Wconversion GCC flag causes compilation errors in bitset.h and unique_ptr.h

### ISSUE THREAD

**Issue by MarkLivsc** [electronicarts/EASTL#265]
Hi,

I'm working on compiling a project with the -Wconversion flag to prevent accidental integer truncation, and I'm hitting compilation errors in the EASTL. E.g.

`[...]/EASTL/unique_ptr.h:552:26: error: conversion to ‘uint16_t {aka short unsigned int}’ from ‘unsigned int’ may alter its value [-Werror=conversion]
   { return unique_ptr<T>(new T(eastl::forward<Args>(args)...)); }`

Is this a known issue/are you opposed to accepting fixes for the issue?

Thanks,
Mark

**Comment by rparolin** [comment]
Can you provide a test case for the issue?

**Comment by rparolin** [comment]
Please re-open with a valid test case.  Thank you.
