### ISSUE TITLE
eastl::is_move_constructible_v<T> returns false when it shouldn't

### ISSUE THREAD

**Issue by DragoonX6** [electronicarts/EASTL#266]
Take the following code:

```cpp
class Foo;

class Bar
{
public:
    Bar() = default;
    Bar(Bar const &) = delete;
    Bar(Bar &&) noexcept = default;

    Bar &operator=(Bar const &) = delete;
    Bar &operator=(Bar &&) = default;

private:
    eastl::vector<Foo*> foo;
};

static_assert(eastl::is_move_constructible_v<Bar>);
```

Here false is returned, but when one uses `eastl::is_move_constructible<Bar>::value` instead, it works just fine.

I haven't had the time to investigate into this issue yet, so I can't really give more details than this sample.

**Comment by rparolin** [comment]
Should be resolved in the 3.13.03 release.
