### ISSUE TITLE
eastl::string_hash_map::insert_or_assign

### ISSUE THREAD

**Issue by dylanwijnen1** [electronicarts/EASTL#269]
Hello,

I ran into a run time error with `eastl::string_hash_map` I started investigating the issue.
I found that the `eastl::string_hash_map::insert` is overloaded but `eastl::string_hash_map::insert_or_assign`
hasn't. 

Using `eastl::string_hash_map::insert_or_assign` currently will try to delete a `(void*)nullptr` as there is no copy of the key being made OR inserting a nullptr element when you step through the first insert. You'll notice that the first time it inserts 2 elements instead of 1.

How to reproduce :

```cpp
#include <EASTL\string_hash_map.h>
int main()
{
	eastl::string_hash_map<int> map;
	map.insert_or_assign("hello", 0);
	map.insert_or_assign("hello2", 0);
	map.clear(); // <-- Runtime error
}
```

**Comment by rparolin** [comment]
I have a fix for that.  This is deferring to the base_type "insert_or_assign" and there is a requirement on the string_hash_map to duplicate the strings into its own allocator.  So the crash is passing a string literal to the string_hash_map allocator to free it.  

Thanks for reporting this.

**Comment by rparolin** [comment]
The fix will be included in the next EASTL release.

**Comment by dylanwijnen1** [comment]
@rparolin I wanted to reopen this as the same issue arises using "emplace" and "try_emplace".
