### ISSUE TITLE
SEGFAULT when running benchmarks

### ISSUE THREAD

**Issue by guykogus** [electronicarts/EASTL#27]
On OSX run the following:
`cmake -Bout -Hbenchmark`
`cd out`
`cmake --build . --config Release`
`ctest -C Release`

There will be a crash due to the format sent to `vprintf` from EASTLBenchmark.cpp (Benchmark::PrintResultLine). On OSX it seems to not understand the "I64" formatter used for the times. I don't know what they're for which is why I'm leaving this in your capable hands.

**Comment by rparolin** [comment]
Should be fixed now.  Plus I hooked up the benchmarks to build and run as part of the CI system so we don't regress in the future.
