### ISSUE TITLE
eastl::function/eastl::fixed_function cannot be declared with noexcept signatures

### ISSUE THREAD

**Issue by jvidziunas** [electronicarts/EASTL#272]
The way `function` and `fixed_function` are specialized will cause problems when declared with a function signature requiring `noexcept`, tested under MSVC 15.9.4 with `/std:c++17`.

Example:
`eastl::function<void () noexcept> test;`

Since the types only have implementations for exception-throwing functions, specialization fails and the compiler falls back to the generic/unimplemented `eastl::function<>` template and causes a compilation error. The same code works under C++11 rules since `noexcept` was not required to be visible to the type system until C++17, and while I have not tested this personally, my understanding is that this behavior is required by standard and should be reproducible with any compiler that implements `noexcept` according to C++17 rules.

**Comment by jvidziunas** [comment]
Further investigation reveals MSVC built-in `std::function` has a similar problem, so this probably isn't high-priority. I'll leave it open for discussion in the mean time.

**Comment by rparolin** [comment]
I prefer to leave issues open that can be actioned on.  I haven't figured out a good way to maintain a todo list seperate from the issues.  If you have suggestions please let me know.  I'm going to close this issue until there is a repo case.

**Comment by FrankHB** [comment]
> I prefer to leave issues open that can be actioned on. I haven't figured out a good way to maintain a todo list seperate from the issues. If you have suggestions please let me know. I'm going to close this issue until there is a repo case.

The open status of the issue does not necessarily mean ready to action. As of the todo list... why not labels?

Moreover, this issue can be pending to wait for the upstream (`std::function`) solution.

**Comment by FrankHB** [comment]
Technically the title is incorrect: the declaration of the type itself is well-formed, but it is an incomplete type, so the definition of the object of that type fails.
