### ISSUE TITLE
Compile failures with char8_t

### ISSUE THREAD

**Issue by CaseyCarter** [electronicarts/EASTL#274]
(Disclaimer: I'm a Microsoft employee on the Visual C++ team.)

We've stumbled across some build failures in EASTL after implementing support for `char8_t` under `/std:c++latest` in the development version of Visual C++. Specifically:

1. [Line 927 of `include/EASTL/string.h`](https://github.com/electronicarts/EASTL/blob/master/include/EASTL/string.h#L927) calls `eastl::CharStrlen` with a `const value_type*`. When `char8_t` is the C++20 fundamental type and `value_type` is `char`, there is no overload of `eastl::CharStrlen` that accepts `const char*`. (There are four overloads defined [in `include/EASTL/internal/char_traits.h`](https://github.com/electronicarts/EASTL/blob/master/include/EASTL/internal/char_traits.h#L235-L266) accepting pointer-to-`const` `char8_t`, `char16_t`, `char32_t`, and `wchar_t`, but no `char`.)

2. [Line 16 of `test/packages/EAStdC/source/EASprintf.cpp`](https://github.com/electronicarts/EASTL/blob/master/test/packages/EAStdC/source/EASprintf.cpp#L16) wants to call `vsnprintf` with a `char8_t*`, but there's no such overload of `vsnprintf`.

**Comment by rparolin** [comment]
Thanks for the heads up.  I'll look at preparing EASTL for that change.  Is there a prefered method to detect when char8_t is a unique type in the type system?  Or is checking ```__cpp_char8_t``` sufficient?

**Comment by CaseyCarter** [comment]
> Or is checking `__cpp_char8_t` sufficient?

Yes, you want to check `__cpp_char8_t`. Note that its value is somewhat orthogonal to the language mode: there are `/Zc:char8_t` and `/Zc:char8_t-` flags that can be used to enable `char8_t` in sub-`c++latest` modes or disable it in `c++latest`.

**Comment by rparolin** [comment]
Excellent.  I will enable overloads based on that feature then.  Thanks for the info.

**Comment by rparolin** [comment]
@CaseyCarter I'm picking this up again but it appears on VS 16.1.4 __cpp_char8_t isn't enabled when I'm passing /Zc:char8_t explicitly to the compiler.

**Comment by CaseyCarter** [comment]
This is the behavior I observe:
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.1.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>cd \Users\cacarter\Desktop

C:\Users\cacarter\Desktop>type repro.cpp
#ifdef __cpp_char8_t
#pragma message("__cpp_char8_t is defined")
#else
#pragma message("__cpp_char8_t is not defined")
#endif

C:\Users\cacarter\Desktop>cl repro.cpp /Zs
Microsoft (R) C/C++ Optimizing Compiler Version 19.21.27702.2 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
__cpp_char8_t is not defined

C:\Users\cacarter\Desktop>cl repro.cpp /Zs /Zc:char8_t
Microsoft (R) C/C++ Optimizing Compiler Version 19.21.27702.2 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

repro.cpp
__cpp_char8_t is defined
```
`__cpp_char8_t` is only defined - and `char8_t` support enabled - when compiling with `/Zc:char8_t` on VS2019 version 16.1. This changes in VS2019 version 16.2: `/std:c++latest` implies `/Zc:char8_t` on 16.2 (although it can still be suppressed with `/Zc:char8_t-`).

**Comment by rparolin** [comment]
OK.  I don't know what I was doing wrong before... but I've sorted it out and its working now.

This change is pretty impactful and it pretty much breaks all our EAStdC string functions b/c the overloads where char8_t, char16_t, and char32_t.  Assuming that char8_t aliased char.  :(

**Comment by tahonermann** [comment]
@rparolin, [P1423](http://wg21.link/p1423) discusses remediation approaches and options that were considered to reduce backward compatibility impact.  I know none of what is discussed is a silver bullet, but I hope there is something helpful for you in there.  I would appreciate hearing any feedback on it.

I'm curious how helpful it might be if compilers supported an option to allow `char8_t` to alias `char`.  The `char8_t` support in gcc and Clang doesn't permit aliasing in that direction.  I'm not sure if the Microsoft compiler does or does not.  @CaseyCarter, do you know?

**Comment by CaseyCarter** [comment]
> I'm curious how helpful it might be if compilers supported an option to allow `char8_t` to alias `char`. The `char8_t` support in gcc and Clang doesn't permit aliasing in that direction. I'm not sure if the Microsoft compiler does or does not. @CaseyCarter, do you know?

From what I understand, we eschew type-based-alias-analysis completely; casting pointers-to-`char` to pointers-to-`char8_t` should work just fine.

**Comment by tahonermann** [comment]
@rparolin, if the ability to alias `char` and `char8_t` is important, at least for the short term, you could take the approach that ICU does to defeat type based alias analysis.  See ICU's `U_ALIASING_BARRIER` macro and various uses here:
- https://github.com/unicode-org/icu/blob/master/icu4c/source/common/unicode/char16ptr.h

**Comment by rparolin** [comment]
Hi @tahonermann.  Thanks for the input.  Yeah, I was reading P1423, and as you stated, there is no silver bullet unfortunately.  I was thinking about some mechanism where overload resolution would look at the available overloads and if only 8-bit character type overload was present it would allow the implicit conversion and make the call.  But it has the same short comings as the other proposed solutions; namely it doesn't prevent functions being called with mismatch string encoding passed to it.

Microsoft allows char8_t keyword to be disabled  (/Zc:char8_t); a few engineers are using that locally here.

**Comment by rparolin** [comment]
I recently added explicit char8_t test in the EASTL CI.  Let me know if you encounter any further issues.  Thanks!

**Comment by DBJDBJ** [comment]
Hint 1: one char8_t can not store any UTF8 glyph.  
Hint 2: AFAIK everywhere but on Windows, char * is UTF8
Hint 3: Windows + top performance  = wchar_t

I do not envy you guys ...
