### ISSUE TITLE
Circular header dependency

### ISSUE THREAD

**Issue by hamzasood** [electronicarts/EASTL#275]
The two headers `internal/function.h` and `internal/function_detail.h` end up including each other.

The cycle is:
1. `<EASTL/internal/function_detail.h>`
2. `<EASTL/utility.h>`
3. `<EASTL/functional.h>`
4. `<EASTL/internal/function.h>`
5. `<EASTL/internal/function_detail.h>`

This simple one line program fails to compile with lots of errors:

    #include <EASTL/fixed_function.h>

If `internal/function_detail.h` is first included from any file other than `internal/function.h` (e.g. from `fixed_function.h`), then the build will fail.

**Comment by rparolin** [comment]
Sorry for the delay. Can you confirm you are on the latest release version of EASTL? I introduced the "functional_base.h" to break the cycle in this case.

**Comment by rparolin** [comment]
I'll close the issue for now.  If this is still an issue for you on versions with the new base header we can re-open the ticket.  Thank you.

**Comment by hamzasood** [comment]
Just had a go with the latest release (3.13.06), and it’s still an issue.
