### ISSUE TITLE
chrono is not producing correct results on mingw-w64

### ISSUE THREAD

**Issue by Zoodinger** [electronicarts/EASTL#278]
I noticed that chrono support is wrong in two ways:
- The time is always approximately 100 times larger than the std equivalent
- Even taking that into account, the time seems to be inaccurate.

This is true for mingw-w64 x64 8.1 posix seh (on both Windows machines that I tried), but it works perfectly on gcc on Ubuntu.

Taking this example:
```
using TimePoint_eastl = eastl::chrono::time_point<eastl::chrono::system_clock,
eastl::chrono::duration<long long int, eastl::ratio<1, 1000000000>>>;

TimePoint_eastl get_time_point_eastl() {
    return eastl::chrono::high_resolution_clock::now();
}

double get_elapsed_seconds_eastl(const TimePoint_eastl &time) {
    return eastl::chrono::duration_cast<eastl::chrono::nanoseconds>
                   (get_time_point_eastl() - time).count() / 1000000000.;
}

using TimePoint_std = std::chrono::time_point<std::chrono::system_clock,
std::chrono::duration<long long int, std::ratio<1, 1000000000>>>;

TimePoint_std get_time_point_std() {
    return std::chrono::high_resolution_clock::now();
}

double get_elapsed_seconds_std(const TimePoint_std &time) {
    return std::chrono::duration_cast<std::chrono::nanoseconds>
                   (get_time_point_std() - time).count() / 1000000000.;
}

int main() {
    auto start_std = get_time_point_std();
    auto start_eastl = get_time_point_eastl();

    std::this_thread::sleep_for(std::chrono::seconds(1));

    auto end_std = get_elapsed_seconds_std(start_std);
    auto end_eastl = get_elapsed_seconds_eastl(start_eastl);

    std::cout << "STD: " << end_std << std::endl;
    std::cout << "EASTL: " << end_eastl << std::endl;

    return 0;
}
```

I get the sample output of:
```
STD: 1.00026
EASTL: 99.983
```

As far as I know, std::this_thread::sleep_for is guaranteed to be at least the time specified. So even assuming EASTL's time is 100 larger, it should never be below 100 like it is in this output.

**Comment by rparolin** [comment]
We don't explicitly test mingw internally or on the open source CI.  If you would like to propose a fix I'd be happy to look at it.  But since the platform is not explicitly tested I'm tempted to close this issue as it will never force a fix to be applied.
