### ISSUE TITLE
Path class

### ISSUE THREAD

**Issue by redorav** [electronicarts/EASTL#279]
Hello,

Are there any plans to create a path object such as the one being proposed by the standard library, but that uses eastl::string and other eastl internals? As far as I can tell there isn't one yet here.

Thanks!

**Comment by rparolin** [comment]
We don't have any concrete plans to support the std::filesystem at this time.

**Comment by rparolin** [comment]
I'm to close the issue but if people feel strongly that this should be supported we can have that discussion.

**Comment by redorav** [comment]
Sorry for not replying earlier, I also completely missed the last comment. Thank you for considering it, currently what I'm finding is that interacting between eastl and filesystem there's a lot of coming and going of c_str() and it would definitely be nice to have better integration. It of course depends on the level of demand.

**Comment by Souvenal** [comment]
Hi, after 6 years, I wonder if there is any plan for EASTL to support filesystem operations?
