### ISSUE TITLE
INTMAX_MAX not defined

### ISSUE THREAD

**Issue by dxpke** [electronicarts/EASTL#282]
Hi!

EASTL uses `intmax_t` and `INTMAX_MAX` here: https://github.com/electronicarts/EASTL/blob/3.13.06/include/EASTL/ratio.h#L89-L101

`intmax_t` is defined in `eabase.h` (if not already present), but `INTMAX_MAX` is not. So when the platform does not provide it (e.g. if `EA_COMPILER_HAS_INTTYPES` is false), `ratio.h` fails to compile. I guess it would be nice to add that definition in `eabase.h` along the other ones like `INT64_MAX`.

**Comment by rparolin** [comment]
I'll include this fix in the next release of EASTL.
