### ISSUE TITLE
EASTL failed to cmake due to does not contain a CMakeLists.txt file with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [electronicarts/EASTL#285]
Environment:
Windows Server 2016 + VS2017 + EASTL master branch latest srouce code.

EASTL failed to cmake due to does not contain a CMakeLists.txt file with MSVC on windows. It can be first reproduced on master revision 376bcdc . Could you help have a look about this issue? Thanks in advance!

1. git clone  https://github.com/electronicarts/EASTL  D:\EASTL\src
2. Open a VS 2017 x86 command prompt as admin and browse to D:\EASTL
3. mkdir build_x86 && pushd build_x86
4. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DEASTL_BUILD_TESTS:BOOL=ON ..\src\

[CMakeError.log](https://github.com/electronicarts/EASTL/files/3305020/CMakeError.log)
[CMakeOutput.log](https://github.com/electronicarts/EASTL/files/3305021/CMakeOutput.log)
[log_x86_cmake.log](https://github.com/electronicarts/EASTL/files/3305022/log_x86_cmake.log)

Actual result:
[executing command] cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DEASTL_BUILD_TESTS:BOOL=ON ..\src\ 
-- The CXX compiler identification is MSVC 19.23.27818.96
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at test/CMakeLists.txt:55 (add_subdirectory):
  The source directory

    D:/EASTL/src/test/packages/EABase

  does not contain a CMakeLists.txt file.

CMake Error at test/CMakeLists.txt:56 (add_subdirectory):
  The source directory

    D:/EASTL/src/test/packages/EAAssert

  does not contain a CMakeLists.txt file.

CMake Error at test/CMakeLists.txt:57 (add_subdirectory):
  The source directory

    D:/EASTL/src/test/packages/EAStdC

  does not contain a CMakeLists.txt file.

CMake Error at test/CMakeLists.txt:58 (add_subdirectory):
  The source directory

    D:/EASTL/src/test/packages/EAMain

  does not contain a CMakeLists.txt file.

CMake Error at test/CMakeLists.txt:59 (add_subdirectory):
  The source directory

    D:/EASTL/src/test/packages/EATest

  does not contain a CMakeLists.txt file.

CMake Error at test/CMakeLists.txt:60 (add_subdirectory):
  The source directory

    D:/EASTL/src/test/packages/EAThread

  does not contain a CMakeLists.txt file.

-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - not found
-- Found Threads: TRUE  
-- Configuring incomplete, errors occurred!
See also "D:/EASTL/build_x86/CMakeFiles/CMakeOutput.log".
See also "D:/EASTL/build_x86/CMakeFiles/CMakeError.log".
[command took 10 seconds]

**Comment by rparolin** [comment]
The repo was recently converted to use git submodules for its dependencies as we promoted them to full git repos.  Apologies for the inconvenience.

**Comment by spacelg** [comment]
Thanks for your reply!

As you said, i tried to git clone --recursive https://github.com/electronicarts/EASTL  D:\EASTL\src

But we get this as below:

Cloning into 'D:\EASTL\src'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
rRemote: Total 3238 (delta 4), reused 2 (delta 1), pack-reused 3224
Receiving objects: 100% (3238/3238), 2.54 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1965/1965), done.
Checking connectivity... done.
Submodule 'test/packages/EAAssert' (git@github.com:electronicarts/EAAssert.git) registered for path 'test/packages/EAAssert'
Submodule 'test/packages/EABase' (git@github.com:electronicarts/EABase.git) registered for path 'test/packages/EABase'
Submodule 'test/packages/EAMain' (git@github.com:electronicarts/EAMain.git) registered for path 'test/packages/EAMain'
Submodule 'test/packages/EAStdC' (git@github.com:electronicarts/EAStdC.git) registered for path 'test/packages/EAStdC'
Submodule 'test/packages/EATest' (git@github.com:electronicarts/EATest.git) registered for path 'test/packages/EATest'
Submodule 'test/packages/EAThread' (git@github.com:electronicarts/EAThread.git) registered for path 'test/packages/EAThread'
Cloning into 'D:/EASTL/src/test/packages/EAAssert'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:electronicarts/EAAssert.git' into submodule path 'D:/EASTL/src/test/packages/EAAssert' failed

It looks like we could not read from remote repository. Could you help have a look about this issue?

Thanks,
Lin

**Comment by dxpke** [comment]
@spacelg The submodules unfortunately use ssh URLs, so you need to make sure your SSH setup is working correctly and you have created&added an ssh key to your GitHub account. I hope this decision is revisited since it effectively makes it impossible to clone EASTL without an account (or alternatively messing with the submodule URLs).

**Comment by rparolin** [comment]
Is there guidance on how to use submodules?

**Comment by theryee** [comment]
I haven't tried with submodules... but the git command line tool doesn't require keys when cloning via https. Similarly, I would expect submodules configured with https to not require keys.

Cloning via https is definitely slower than via ssh... but it's much more convenient.

**Comment by dxpke** [comment]
@rparolin I don't think there is a list of points to follow in your specific use case, but as I said I would strongly suggest not using SSH urls in a public repository. If you change the URLs in `.gitmodules` to HTTPS, everyone can check out, with or without GitHub account. As you already noticed, you also get problems with CI otherwise and have to work around that. If you or anyone else then want to use SSH for personal development, you can change the remote URLs in your local checkout, as opposed to the other way round of all users having to change the URLs. See also https://stackoverflow.com/questions/6031494/git-submodules-and-ssh-access#6031607 for example.

Also I've seen many people move away from submodules due to their non-intuitive nature and behavior that makes them prone to weird errors. YMMV. I personally think they're OK-ish if the repositories you depend on do not change that often, i.e., you include them as dependencies and don't really intend to work on them in the scope of this project.

**Comment by spacelg** [comment]
Hi dxpke,

Thanks for your reply and information!

We mainly test the VS compiler through open source projects. We don't use EASTL code area development. Is there any way to successfully clone submodules without using ssh key?

Thanks,
Lin

**Comment by spacelg** [comment]
Hi dxpke,

I have created&added an ssh key to my GitHub account. And now submodules can update. so we re-build EASTL and get error C3861:  '_InterlockedExchange64_INLINE': identifier not found.

My repro steps:
1. git clone https://github.com/electronicarts/EASTL D:\EASTL\src
2. cd src
3. git submodule init
4. git submodule update
5. cd ..
6. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DEASTL_BUILD_TESTS:BOOL=ON ..\src\
7. msbuild /m /p:Configuration=Release;Platform=Win32 EASTL.sln /t:Rebuild

[log_x86_build.log](https://github.com/electronicarts/EASTL/files/3345109/log_x86_build.log)

Actual result:
D:\EASTL\src\test\packages\EAThread\include\eathread/internal/eathread_atomic_standalone_msvc.h(201,107): error C3861:  '_InterlockedExchange64_INLINE': identifier not found [D:\EASTL\build_x86\test\packages\EAThread\EAThread.vcxproj]
D:\EASTL\src\test\packages\EAThread\include\eathread/internal/eathread_atomic_standalone_msvc.h(201,107): error C3861: inline long long AtomicSetValue(volatile long long* ptr, long long value) { return static_cast<long long>(_InterlockedExchange64(ptr, value)); } [D:\EASTL\build_x86\test\packages\EAThread\EAThread.vcxproj]
D:\EASTL\src\test\packages\EAThread\include\eathread/internal/eathread_atomic_standalone_msvc.h(201,107): error C3861:                                                                                                           ^ (compiling source file D:\EASTL\src\test\packages\EAThread\source\eathread_futex.cpp)

**Comment by dxpke** [comment]
> We mainly test the VS compiler through open source projects. We don't use EASTL code area development. Is there any way to successfully clone submodules without using ssh key?

You can edit the `.gitmodules` file and replace the ssh with https URLs.

> so we re-build EASTL and get error C3861: '_InterlockedExchange64_INLINE': identifier not found.

I'm afraid I can't help you there, sorry. I have no affiliation with EASTL. Maybe you are using an outdated/wrong Windows SDK?

**Comment by spacelg** [comment]
Hi dxpke, 

Thanks for your info so much! We will re-report this error to the ESTAL team. Thanks again!

Thanks,
Lin
