### ISSUE TITLE
Why is the static_assert in forward commented out?

### ISSUE THREAD

**Issue by tuket** [electronicarts/EASTL#286]
```cpp

template <typename T>
EA_CPP14_CONSTEXPR T&& forward(typename eastl::remove_reference<T>::type&& x) EA_NOEXCEPT
{
	//static_assert(!is_lvalue_reference<T>::value, "forward T isn't lvalue reference");
	return static_cast<T&&>(x);
}
```

**Comment by rparolin** [comment]
I believe this assert is silly.  It will basically never be true as an rvalue once it passed the function call boundary becomes an lvalue.  So this static_assert will never fail, x is always an lvalue at the point its evaluated.  

I'll remove it; and the change will be contained in the next release..  Thanks for the heads up.

**Comment by tuket** [comment]
Gcc's std implementation has that same assert. I was wondering in which situations that assert might be useful.
https://stackoverflow.com/questions/10335916/c11-why-is-static-assert-in-stdforward-necessary
It could be useful when you pass in an rvalue and specify lvalue as template param.
```cpp
foo(forward<T&>(T())
```
But that's a very dumb thing to do :)

**Comment by rparolin** [comment]
:facepalm:  Good point!   I'll renable it and see what code breaks. ;)  If all goes well I'll include it in the next release.
