### ISSUE TITLE
No installation since #284

### ISSUE THREAD

**Issue by dxpke** [electronicarts/EASTL#287]
Besides converting the included packages into submodules, 376bcdc93502208b3e61b88c911fad0f9c9e3f60 also removed the installation of all EASTL headers and the compiled library. This is quite unfortunate since it means everyone must now manually take care of that. Any chance of bringing the `install` commands back?

**Comment by rparolin** [comment]
Sure.  Submit a PR and I'll integrate it.

**Comment by rparolin** [comment]
I'll close this issue and wait for the PR.
