### ISSUE TITLE
EASTL failed to build due to error C3861:  '_InterlockedExchange64_INLINE': identifier not found with MSVC on windows.

### ISSUE THREAD

**Issue by spacelg** [electronicarts/EASTL#290]
Environment:
Windows Server 2016 + VS2017 + EASTL master branch latest srouce code.

We have created&added an ssh key to my GitHub account. And now submodules can update. so we re-build EASTL and get error C3861.

EASTL failed to build due to error C3861:  '_InterlockedExchange64_INLINE': identifier not found with MSVC on windows. It can be first reproduced on latest master revision. Could you help have a look about this issue? Thanks in advance!

1. git clone https://github.com/electronicarts/EASTL D:\EASTL\src
2. Open a VS 2017 x86 command prompt as admin and browse to D:\EASTL\src
3. git submodule init
4. git submodule update
5. cd ..
6. mkdir build_x86 && pushd build_x86
7. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DEASTL_BUILD_TESTS:BOOL=ON ..\src\
8. msbuild /m /p:Configuration=Release;Platform=Win32 EASTL.sln /t:Rebuild

[log_x86_build.log](https://github.com/electronicarts/EASTL/files/3347967/log_x86_build.log)

Actual result:
D:\EASTL\src\test\packages\EAThread\include\eathread/internal/eathread_atomic_standalone_msvc.h(201,107): error C3861: '_InterlockedExchange64_INLINE': identifier not found [D:\EASTL\build_x86\test\packages\EAThread\EAThread.vcxproj]
 D:\EASTL\src\test\packages\EAThread\include\eathread/internal/eathread_atomic_standalone_msvc.h(201,107): error C3861: inline long long AtomicSetValue(volatile long long* ptr, long long value) { return static_cast(_InterlockedExchange64(ptr, value)); } [D:\EASTL\build_x86\test\packages\EAThread\EAThread.vcxproj]
 D:\EASTL\src\test\packages\EAThread\include\eathread/internal/eathread_atomic_standalone_msvc.h(201,107): error C3861: ^ (compiling source file D:\EASTL\src\test\packages\EAThread\source\eathread_futex.cpp)

**Comment by rparolin** [comment]
Interesting.  We appear to be using a compiler intrinsic that MS is wrapping with other defines.   That can be cleaned up.  Thanks for reporting.

**Comment by rparolin** [comment]
I have a fix for this.  It will be included in the next release.
