### ISSUE TITLE
eastl::queue should provide emplace() for STL compatibility

### ISSUE THREAD

**Issue by dxpke** [electronicarts/EASTL#292]
Hi,

I have noticed that `eastl::queue` provides an `emplace_back` function for constructing an element directly in the queue. According to this reference: https://en.cppreference.com/w/cpp/container/queue the function in the STL equivalent `std::queue` is called `emplace` instead (since the container is also using `push` and not `push_back`). So for STL compatibility, it would be cool if the function could be renamed or a new one added.

Thanks a lot for your work!

**Comment by rparolin** [comment]
Thanks for reporting.  This fix will be included in the next release.
