### ISSUE TITLE
std::stack::emplace <> eastl::stack::emplace_back

### ISSUE THREAD

**Issue by matt77hias** [electronicarts/EASTL#293]
In order to be (somewhat more) on par with the std, `eastl::stack::emplace_back` should ideally be renamed to `eastl::stack::emplace` (which is also more consistent to `eastl::stack::push`).

**Comment by rparolin** [comment]
Thanks for reporting this.  Would you like to submit a PR?

**Comment by matt77hias** [comment]
Created a [PR](https://github.com/electronicarts/EASTL/pull/294).

I signed and submitted the CLA as well (_although, technically I am fully employed by Frostbite_).
