### ISSUE TITLE
Question about usage of compressed_pair

### ISSUE THREAD

**Issue by wmamrak** [electronicarts/EASTL#299]
Hello,

why classes such as VectorBase, ListBase etc. are using empty base class optimization to reduce their sizes when allocator is empty using compressed_pair on one of their members instead of something like below, which seems more readable and conceptually straightforward?
```
template <typename T, typename Allocator>
struct VectorBase : public CompressedAllocator<Allocator> //the CompressedAllocator name is a potential subject to change
```

**Comment by rparolin** [comment]
compressed_pair is a pattern that is used in other standard libraries.  Readable is a fairly subjective measure but I'd argue it is a familiar abstraction among standard library maintainers. 

https://www.boost.org/doc/libs/1_65_1/libs/utility/doc/html/compressed_pair.html
https://github.com/llvm-mirror/libcxx/blob/master/include/vector#L344

**Comment by wmamrak** [comment]
I agree that readability is subjective, but is it the case below? :-)
`if(mpEnd == mpCapacity)`
vs
`if(mpEnd == internalCapacityPtr())`

The code is littered with this, and the reason is "compatibility" (of internal code(!)) with some other libraries. If it is the sole reason, it doesn't feel right to me.
