### ISSUE TITLE
Does EASTL work across DLL boundaries?

### ISSUE THREAD

**Issue by ruipacheco** [electronicarts/EASTL#300]
My team currently has a problem where we need to send objects across DLL boundaries where sometimes some code is written in debug mode and other bits of code are written in release mode.  We're currently implementing our own data types since sending STL types across DLL boundaries is not great.

I wonder if the EASTL can be used as a replacement for the STL for those use cases?

**Comment by rparolin** [comment]
EASTL doesn't provide any additional guarantees when types cross DLL boundaries.  I believe its all UB since the standard doesn't define what a DLL is.
