### ISSUE TITLE
3.14.XX releases don't include sub-module code

### ISSUE THREAD

**Issue by jvetter1** [electronicarts/EASTL#304]
The 3.14.XX releases don't include sub-module code and the dependent sub-modules don't have corresponding releases that can be pulled in separately via archives. 

It would be helpful if you could either include the dependent sub-module code with the EASTL release (e.g. by using --recurse-submodules) or create releases for each sub-module when you release EASTL so its easier to update.

Its worth noting that even if you do:
`git clone --branch 3.14.01 --recurse-submodules https://github.com/electronicarts/EASTL.git`
The result is an endless recursive sub-module clone that never ends...

I feel like the sub-modules are maybe done wrong because when you break out of the recursive loop after it looks like it cloned the sub-modules they are still empty, just like your release archive

Thanks!

**Comment by rparolin** [comment]
Duplicate.  https://github.com/electronicarts/EASTL/issues/302
