### ISSUE TITLE
eastl::any does not have natvis

### ISSUE THREAD

**Issue by simplex-fx** [electronicarts/EASTL#306]
Because of the design of any storage_handler_*, we could not get natvis working,
so it makes it cumbersome to debug.

Possible solution:

-storage_handler_* should have virtual functions instead of the handler_func + switch

-storage_handler_*s need to share a template base class (storage_handler_base)

-m_handler should be size_t (so we store the vptr)

-m_handler could be initialized with new (&m_handler) storage_handler_*<T>

This way, eastl::any could be represented in natvis as
*(storage_handler_base*)m_handler

And each storage_handler_*<T>, could be represented as something like
($T1*)(this-1).

So we patch our own address to make it point to the the storage, and then cast it to T.
In case of external storage, we need an extra dereference.

**Comment by rparolin** [comment]
I'd definitely like to avoid virtual dispatch at runtime to enable a natvis solution.

**Comment by simplex-fx** [comment]
Are you sure, that the current switch/case solution, to emulate the same virtual behaviour, is actually faster?

**Comment by rparolin** [comment]
I haven't written benchmarks for eastl::any yet.  Would you be interested in contributing that as a PR?

**Comment by simplex-fx** [comment]
To be honest, I never did performance benchmarks, I just did my own version, as debug readability was far more important for us, than marginal performance gains.

But as I see, as calling the handler is already an indirect function call, so current method compiles either to:

-indirect function call + jump table
-indirect function call + ifs in binary search style (3 compares).

Either 2 reads and 2 calls, or 1 read, 1 call, and 3 branches (3 possible mispredictions).

While the virtual call is 2 reads and an single call. Obviously faster then the first version.
And fits a lot better into the instruction cache, compared to the second version.
(should be around ~4 times smaller, or even less, in case of the most frequently used GET op)

I don't see a clear winner there, and actual results depend heavily on usage patterns / caching. Writing a benchmark that gives clear winner would be tricky.

Also, having a vtable gives us the opportunity, to support reflection functions, like ToString/ToGUI/ToDebugUI/ToJSON, without any extra cost (I just implemented them directly, in my own implementation, but they could be also implemented via a macro configuration for actual needed functions & signatures + template specializations by the user)

**Comment by rparolin** [comment]
Sorry.  I don't want to change the implementation details of eastl::any to include virtual calls just for eastl::any natvis scripting.  I've included a very basic eastl::any natvis which shows the underlying value of the storage if it contains a value (either the value or the pointer to the value) and it will say if the eastl::any is empty or not.  This will be included in the next release.  Maybe we can revisit with an alternate proposal that doesn't include virtual calls or if natvis expands its scripting.
