### ISSUE TITLE
east::any internal type check fix to work without rtti

### ISSUE THREAD

**Issue by simplex-fx** [electronicarts/EASTL#307]
To avoid calls and rtti, but still have internal (or even external) type checks,
we could just compare m_handler with &StorageHandlerT::handler_func
(or address of a virtual function, see #306 )

As the address is unique for every T in storage_handler_*<T>.

Idea comes from: [this paper](https://www.researchgate.net/publication/221307833_Type-preserving_heap_profiler_for_C), page 3:

template<class T>struct TYPE_IDENTIFIER
{
  static char mDummy;
};
struct NewTrick
{
  template<class T>T*operator*(T*Ptr)
  {
    RegisterAllocation(Ptr, &TYPE_IDENTIFIER<T>::mDummy);
    return Ptr;
  }
};

**Comment by rparolin** [comment]
We encountered issues with using the address of the handler in DLL builds as in that situation the address was different for eastl::any containing the same T type.   There are in source comments and unfortunately I couldn't think of a solution so the validation was disabled in non-rtti envrionments.

https://github.com/electronicarts/EASTL/blob/master/include/EASTL/any.h#L595

**Comment by simplex-fx** [comment]
Could you guys add some ifdef, so if it's not a dll build, it would still work?

**Comment by rparolin** [comment]
I'll include this in the next EASTL release.
