### ISSUE TITLE
Move some packages out of the test folder

### ISSUE THREAD

**Issue by philix** [electronicarts/EASTL#31]
Some packages are only required for testing and it makes sense to leave them in the `test` folder but the generic ones could be moved to a `packages` folder in the root folder.

Tell me what you think and I'll send a PR with this change.

**Comment by rparolin** [comment]
In the near future, I wanted to break out EABase and EATest into separate repositories and use git-submodules.  I was planning on tackling the work of reorganizing where the packages live then.  I wasn't entire sure what "most" repos did or what made the most sense in terms of where dependencies lived in the repo.  I guess it makes sense to split the dependencies of EASTL and the EASTLTests into their respective package folders (eg. EASTL/packages and EASTL/test/packages).

I'm curious if there are any other thoughts on this from the community?

**Comment by pzychotic** [comment]
The current project structure is indeed rather strange, especially that the EASTL library is dependent on code located somewhere deep inside the test directory. And a few other things I tried to address already in #32.
I don't have much experience with submodules yet myself, but if you plan to break out EABase and EATest anyways, submodules sound like a good way to go.
The only small problem I can see with that is, because EASTL and EATest both depend on EABase you would end up with pulling in EABase two times into the EASTL repository which could in theory be different if the submodules in EASTL and EATest don't reference the same commit.

**Comment by pmcmorris** [comment]
I don't think that EABase would end up as a submodule of EASTL in this approach. It would simply be a build dependency.

The key point is that the typical usage of EASTL is not as a top level project; it is used as a sub-component when building some other project (e.g. a game).  Similarly, EABase is another such sub-component.

The question of whether component are using git sub-modules would be a decision for the maintainer of the top level project using them.  For example, one common approach is to require the components to be installed on the development machine and allow them to be discovered at build time.

An alternate approach, which has the advantage of not relying on the configuration host development machine. is to use sub-module references in the top level project.  In other words, doing a recursive sync of the top level project would also sync these "external" modules and treat them as part of the game build. So, each of these "packages" should only appear once per top level project on the development machine.

**Comment by rparolin** [comment]
EASTL could have the 'packages' moved out of the 'test' folder and into the EASTL root.  That way they can easily used for both the tests and the benchmarks.

**Comment by philix** [comment]
Yeah! That's my implicitly stated goal with this issue :-)

**Comment by rparolin** [comment]
Great, if there isn't anymore discussion that needs to happen then I'll close this issue.  I'll wait for a PR to be submitted.

**Comment by rparolin** [comment]
Cool.  I change the status and wait for a PR.

**Comment by rparolin** [comment]
Haven't seen an progress on this.  So I'll close it and we an reopen an issue in the future when we want to revisit.
