### ISSUE TITLE
'EABase/eabase.h' file not found (when tests are turned off), even though submodules are updated

### ISSUE THREAD

**Issue by Zoodinger** [electronicarts/EASTL#320]
EASTL can no longer find EABase.h. 

This is unrelated to the new submodule structure, as the submodules ARE updated. Simply adding the line...
```
include_directories(test/packages/EABase/include/Common)
```
...to the CMakeLists.txt of EASTL fixes this issue, but this is something that should be dealt with on the official repository level.

**Comment by rparolin** [comment]
The EABase cmake scripts should export the include directories for you.

**Comment by Zoodinger** [comment]
It's the build itself that fails. My CMake already handled adding the extra includes, and it was working for past versions.

So I did a little investigation and the build fails when I tell CMAKE to not build tests.

If the tests are on it works, but by changing the build.sh file to this (e.g. set EASTL_BUILD_TESTS to OFF)...
```
build_folder=build
mkdir $build_folder
pushd $build_folder
cmake .. -DEASTL_BUILD_TESTS:BOOL=OFF -DEASTL_BUILD_BENCHMARK:BOOL=OFF
cmake --build . --config Release
pushd test
ctest -C Release -V
popd
popd
```
...the build fails.

**Comment by BlurryLight** [comment]
when tests turned off
```
if(EASTL_BUILD_TESTS)
    add_subdirectory(test)
endif()
```
test dir is not included, though  EABase is added as subdirectory in test dir's CMakeLists.
here 
https://github.com/electronicarts/EASTL/blob/1030ad17b2ca3c74fef36df2e4e490817e81b2cf/test/CMakeLists.txt#L55

I guess that's the reason why `EAbase.h` is missing.

**Comment by rparolin** [comment]
Is this issue resolved?

**Comment by Zoodinger** [comment]
The issue is not resolved. The project cannot build when EASTL_BUILD_TESTS is turned off.

**Comment by rparolin** [comment]
https://github.com/electronicarts/EASTL/commit/a8fb05b56e72b035219504329ea6cc8574f991ad
Should resolve this issue.
