### ISSUE TITLE
Compilation error with vector of variant of incomplete type (because of SFINAE)

### ISSUE THREAD

**Issue by tonyriviere88** [electronicarts/EASTL#321]
Hi,
I have compilation errors in the following case with eastl classes while the std counter part is OK.
```
#include <vector>
#include <variant>
#include <EASTL/vector.h>
#include <EASTL/variant.h>

#if 1
using namespace eastl;
#else
using namespace std;
#endif

struct B;

struct A
{
    vector<variant<B>> v;
};

struct B
{
    vector<variant<A>> v;
};
``` 
[See godbolt example](https://godbolt.org/z/Cn06Lm)

The error with `eastl::vector` is because of SFINAE usage for `vector::erase_first` / `vector::erase_last` to know if he type T has comparison operator).
Since there's no possible overload for these functions, SFINAE isn't really necessary, I would make them non-template and use static_assert in the function to explicitly say the reason of the error:
```
iterator erase_first(const T& value)
{
    static_assert(eastl::has_equality_v<T>, "T must be comparable");
}
```

**Comment by rparolin** [comment]
This fix will be included in the next EASTL release.
