### ISSUE TITLE
EASTL headers conflicts with Qt?

### ISSUE THREAD

**Issue by hydexon** [electronicarts/EASTL#328]
Hi, i'm using Kubuntu 19.04 on g++ 8.30 with Qt 5.12.2 64-bit, CMake 3.13.4 with EASTL release 3.14.06

Everytime i try to add any EASTL header, appears hundreds to thousands of syntax errors when the excutable target uses Qt, spurs tons of syntax errors saying some class or class member doesn't exist under eastl namespace and even saying some features are restricted to C++14 (which explicitly i've setup C++14 support in Cmake scripts)

testing on shared/static libraries and executables which doesn't use Qt works just fine, otherwise if you enable CMake to use Qt to your targets will fail spamming hundreds of syntax errors.

[buildfailure.txt](https://github.com/electronicarts/EASTL/files/3889644/buildfailure.txt)

**Comment by rparolin** [comment]
Looks like you are building with a C++14 enabled compiler.  Sorry, I can't comment on your toolchain setup.  Good luck.
