### ISSUE TITLE
set_name is used without EASTL_NAME_ENABLED flag in "vector_xyz" containers

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [electronicarts/EASTL#340]
vector_multimap and other sorted vector based containers use `get_allocator().set_name(...)` in **default constructor only** without `EASTL_NAME_ENABLED` flag. This causes compile errors with custom allocators without name tracking.

Sample usage without flag:
https://github.com/electronicarts/EASTL/blob/1774cb4839a357a2f3a1cc58ec54575a8158b055/include/EASTL/vector_multimap.h#L303-L308

Sample usage with flag:
https://github.com/electronicarts/EASTL/blob/f4fbe0fb35afacd374564fec70faaf5015547ac1/include/EASTL/fixed_set.h#L194-L196

**Comment by rparolin** [comment]
I fixed that internally.  It will be in the next release of EASTL.
