### ISSUE TITLE
span::size() should return unsigned integer size

### ISSUE THREAD

**Issue by eugeneko** [electronicarts/EASTL#347]
Is there any reason for `span::size()` to return signed integer?
C++20 span works with unsigned integers, according to
https://en.cppreference.com/w/cpp/container/span
I can try to make PR if such change is welcome.

**Comment by Meorawr** [comment]
Are you using a version prior to the [tagged 3.15.00 release](https://github.com/electronicarts/EASTL/releases/tag/3.15.00)? It's an unsigned type from that release onwards.

**Comment by eugeneko** [comment]
Oh, I missed this update. Thanks.
I'm using several months old version of EASTL, didn't know that my issue got fixed since then.
