### ISSUE TITLE
Disabling `EASTL_EMPTY_REFERENCE_ASSERT_ENABLED` causes test failure.

### ISSUE THREAD

**Issue by jwdevel** [electronicarts/EASTL#355]
I edited config.h to disable EASTL_EMPTY_REFERENCE_ASSERT_ENABLED (as encouraged by the docs), but then the tests fail:

In TestSort.cpp:

```
merge_sort_buffer(intArray.begin(), intArray.end(), &buffer[0]);
```

This is for the `i=0, j=0` permutation of the test (the very first), where both the buffer and intArray are size 0.

Perhaps the solution here is just a docs update ("the tests assume an untouched config.h")?

**Comment by rparolin** [comment]
The goal is that the tests should compile regardless of the state of the compile-time flags.  With the amount of compile-time switches its not possible to tests all permutations though.  So in this case, if its a matter of this tests requires a particular features be enabled/disabled; we just disable or enable that test.

**Comment by rparolin** [comment]
Please provide a PR if you wish to resolve this issue.

**Comment by jwdevel** [comment]
Sure, I'll take a stab at it.

**Comment by jwdevel** [comment]
Alas, my CLA was rejected, so I won't be sending PRs.

The fix is here, if anyone wants it: https://github.com/jwdevel/EASTL/commit/b0af75ddba27bded738b81d9d066f892b01334bb

I'll close this, based on your last comment.
