### ISSUE TITLE
CMake install overwrites libs of different configs

### ISSUE THREAD

**Issue by pzychotic** [electronicarts/EASTL#36]
@Leandros introduced a CMake install command in 8be33d4ba8ecefadd3bfde95f9f980523f64882b that can't install the EASTL.lib for different configs like Debug and Release in parallel. The last install will always overwrite any other lib because of the same name.

There are a few ways to make this possible in CMake.

One is to use `set(CMAKE_DEBUG_POSTFIX "d")` or `set_property(TARGET EASTL PROPERTY DEBUG_POSTFIX "d")` to change the name of the lib in Debug config to EASTLd.lib. Not a big fan of this and a breaking change for anyone using the Debug version. Beware `set(CMAKE_DEBUG_POSTFIX "d")`would change the postfix for **all** libs.

The other option would be to install the libs into sub-directories like:
lib/Debug
lib/Release

The modern CMake approach would be to use generator expressions like:
`install(TARGETS EASTL DESTINATION lib/$<LOWER_CASE:$<CONFIG>>)`
This would also allow transformations of the directory name to lower case or anything else generator expressions can do. Unfortunately the install(TARGET...) command only supports generator expressions with CMake v3.3+.

If increasing the minimum required CMake version is not an option, passing the BUILD_TYPE escaped to the install script (note the backslash in front of the ${...}) will also work:
`install(TARGETS EASTL DESTINATION lib/\${BUILD_TYPE})`

A trivial change to make yourself in any case, if there are no objections. Or let me know if you prefer a PR for one of the versions.

**Comment by rparolin** [comment]
Does it make sense to install debug libraries in this case?

**Comment by pzychotic** [comment]
Definitely, as I expect the output of the install step to be used as 3rd party dependencies in other projects. Like I would expect other C++ libraries or SDKs to come with debug and release versions.

If you see the install step as something that is not used in a development environment like a *nix system where other production ready software can be build from source, than this might not be appropriate.

**Comment by rparolin** [comment]
I'm just unfamiliar with the concept of installing libraries in this way.  I don't see a problem with adding this functionality to EASTL if its helpful to people.  Feel free to send a PR.

**Comment by DragoonX6** [comment]
This looks like a nightmare on *nix systems, such as linux or BSD, where libraries are expected to be installed to /usr/lib or in rare cases /usr/lib/$pkgname. This honestly seems like a very MSVC centric thing. In the case of MSVC, you can easily configure the output directory yourself.

**Comment by DragoonX6** [comment]
Reopening, I don't understand why this has been merged as the OP didn't test his PR and this is breaking on unix-like systems, like I explained in my previous post.
\${BUILD_TYPE} is wrong, to get the desired behavior, you need to write ${CMAKE_BUILD_TYPE}.
But again, this is not the correct solution, the better solution is the one you explained earlier and that is using a postfix.

**Comment by Leandros** [comment]
Yes, @rparolin has to re-open the issue.
To chip in, as the guy who introduced the install target first, I think it's wrong in general to have multiple versions of the same library installed. The install target is either used as a dependency for another project (the reason why I added the install target), or installed for the whole operating system to use. In the former case, the EASTL should be compiled accordingly to the parent project settings, in the former case, a system wide installed library should never be debug. I think the change doesn't make sense at all.

**Comment by rparolin** [comment]
I'm not sure how installations are used but EASTL doesn't offer binary compatibility between releases.  I didn't a problem with including a feature that people thought was useful.  It isn't great in my opinion that we can't/don't test it though.  The argument could be made that we shouldn't include it in EASTL.

**Comment by DragoonX6** [comment]
On Linux you're expected to do
`pacman -S EASTL`
`g++ -std=c++11 file_that_uses_EASTL.cpp -lEASTL -o executable_using_EASTL`
This breaks the ability to do that, now you need to -L/usr/lib/Release depending on where your distro installs it.
To retain compatibility between releases distros usually change the name of the library to something like EASTL.so.1.0 and then two symlinks which are name EASTL.so.1 and EASTL.so, and the order is EASTL.so->EASTL.so.1->EASTL.so.1.0. The linker will resolve the symlink at link time and will search for EASTL.so.1.0 when it runs.
Or we can simply link EASTL as a static library, so binary compatibility is out of the picture.
Either way, I think this shouldn't be included in EASTL, given the reasons given already.

**Comment by pzychotic** [comment]
Sorry for the trouble this caused!

'...as the OP didn't test his PR and this is breaking on unix-like systems ... \${BUILD_TYPE} is wrong, to get the desired behavior, you need to write ${CMAKE_BUILD_TYPE}.'

Apparently I did test the PR with VS and it does work, been using this for years before generator expressions where a thing. I wasn't aware that this doesn't work on single configuration generators like makefiles.
CMAKE_BUILD_TYPE is not an option since this is only defined on single configuration generators.

'...the better solution is the one you explained earlier and that is using a postfix.'
As stated earlier, I assume that renaming the libs is a breaking change. If this would be ok todo, this would be an option.

One other solution would be to put the install line with that change into an 'if(MSVC)' and keep the original got everything else.

**Comment by rparolin** [comment]
I haven't seen any activity here.  Can I close this issue?
