### ISSUE TITLE
List in EASTL, error:  expected initializer before ‘operator’ void __cdecl operator new[]

### ISSUE THREAD

**Issue by nwlis** [electronicarts/EASTL#361]
I am trying to make a simple example of list using EASTL.  Here is the code I have written:

```

#include <iostream>
#include <EASTL/fixed_list.h>
#include <EASTL/fixed_allocator.h>

using namespace eastl;
// constructing lists


void* __cdecl operator new[](size_t size, const char* name, int flags, unsigned debugFlags, const char* file, int line)
{
	return new uint8_t[size];
}


int main ()
{
  // constructors used in the same order as described above:
  eastl::list<int> first;                                // empty list of ints
  eastl::list<int> second (4,100);                       // four ints with value 100
  eastl::list<int> third (second.begin(),second.end());  // iterating through second
  eastl::list<int> fourth (third);                       // a copy of third

  // the iterator constructor can also be used to construct from arrays:
  int myints[] = {16,2,77,29};
  eastl::list<int> fifth (myints, myints + sizeof(myints) / sizeof(int) );

  std::cout << "The contents of fifth are: ";
  for (eastl::list<int>::iterator it = fifth.begin(); it != fifth.end(); it++)
    std::cout << *it << ' ';

  std::cout << '\n';

  return 0;
}

```

However, when I compile it with the command :

g++ eastl_hello.cpp -I/home/mkatsa/Desktop/NVM_STL/EASTL/include -I/home/mkatsa/Desktop/NVM_STL/EASTL/test/packages/EABase/include/Common /home/mkatsa/Desktop/NVM_STL/EASTL/build/libEASTL.a -o eastl_hello.exe

I get the error:

**eastl_hello.cpp:9:15: error: expected initializer before ‘operator’
 void* __cdecl operator new[](size_t size, const char* name, int flags, unsigned debugFlags, const char* file, int line)**

Can please anyone help me to see what is wrong? I  have an overload for the operator new[] as shown [here](https://github.com/electronicarts/EASTL/blob/master/doc/CMake/EASTL_Project_Integration.md)

**Comment by Meorawr** [comment]
Not an EASTL issue; the `__cdecl` identifier is used by MSVC to specify the calling convention. GCC implements it via an attribute (`__attribute__((__cdecl__))` I believe?) instead.

I don't think you need to specify it at all in this case, so you can just try removing `__cdecl` and I believe it'll all work fine.
