### ISSUE TITLE
EABase empty

### ISSUE THREAD

**Issue by Redee** [electronicarts/EASTL#363]
```
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
Building with char8_t support in tests.
CMake Error at test/CMakeLists.txt:70 (add_subdirectory):
  The source directory

    D:/Downloads/EASTL-3.16.05/test/packages/EABase

  does not contain a CMakeLists.txt file.
```
https://github.com/electronicarts/EASTL/releases >

![Screenshot_2](https://user-images.githubusercontent.com/2652667/80803244-67ceb780-8bba-11ea-95d2-67b6e62d279c.png)

![2020-05-01_143905](https://user-images.githubusercontent.com/2652667/80803266-75843d00-8bba-11ea-9fdd-d481d268d2ca.png)

![Screenshot_1](https://user-images.githubusercontent.com/2652667/80803308-8f258480-8bba-11ea-8268-2deda6928ce6.png)

I understand this submodules in other repositories from electronicarts, but some work around it...
https://github.com/electronicarts/EAAssert
https://github.com/electronicarts/EABase
https://github.com/electronicarts/EAMain
https://github.com/electronicarts/EAStdC
https://github.com/electronicarts/EATest
https://github.com/electronicarts/EAThread

Better like in past, where was All in One until version EASTL-3.13.06
Anyways thanks at all !)

**Comment by OfekShilon** [comment]
I'm guessing EABase recently changed from source to header-only. I had to manually fix the CMake files to build (on Ubuntu), some pull requests are here: https://github.com/electronicarts/EASTL/pull/366

Can you please try my fork and say if it solves it?  https://github.com/OfekShilon/EASTL
(note you'd need my forks of the submodules too)

**Comment by Zephilinox** [comment]
I'm having an issue building EASTL through cmake, and I think this is related. It seems to be wanting EABase.lib and is missing the include directory for EABase.

**Comment by rparolin** [comment]
Are instructions to fetch the repo in the documentation for how to contribute to the repository.
https://github.com/electronicarts/EASTL/blob/master/CONTRIBUTING.md#getting-the-repository

**Comment by jacmoe** [comment]
It would help a lot if 

1) The submodules weren't dead - see https://github.com/electronicarts/EASTL/tree/master/test/packages
2) The source release contained the contents of the submodules. They are incomplete, and thus not very useful.
