### ISSUE TITLE
eastl::tuple_vector::emplace -- Template Arguments?

### ISSUE THREAD

**Issue by maxattack** [electronicarts/EASTL#369]
**Background**: `std::vector<T>`'s [emplace functions](https://en.cppreference.com/w/cpp/container/vector/emplace_back) template their arguments, because they often differ from T itself. A common use case is emplacing a` T*` into a `std::vector<std::unique_ptr<T>>` so the vector can "take ownership" of it, in-place.

**Problem**: tuple_vector::emplace uses the same templates types (Ts...) as the tuple_vector template itself, as opposed to declaring its own template types.  Therefore, this isn't possible. A `T*` is constructed into `unique_ptr<T>` at the call-site before being forwarded, rather than after.

I don't know if there's an apples-to-apples translation (how do you have a list of variable-arg lists??) But we could at least template the emplace functions with their own argument types and forward them 1-1. `¯\_(ツ)_/¯`

**Comment by maxattack** [comment]
Thinking it over, I suppose you could use a tuple for each arg-list? Something like...

`tvec.emplace_back(tie(1,2,3), tie(), tie("hello", nullptr))`

**Comment by rparolin** [comment]
Yes, or 'forward_as_tuple' would also work in this use case.
