### ISSUE TITLE
EASTL CMAKE

### ISSUE THREAD

**Issue by nwlis** [electronicarts/EASTL#370]
Hello, I am trying to embed EASTL library in an existing project. I have modified a little bit EASTL and i have added a temp.h file which is included in EASTL/vector.h and contains just some variables.
My project has a structure like:
     main.c  --> a.h --> EASTL/vector.h -->temp.h
My main file includes a.h which includes EASTL/vector.h. I can make the link between a.h and EASTL/vector.h, however I get an error in main.c link that mentions that the vaviables in temp.h have been included twice.
Can anyone please help?

That's what I added in the CMakeLists.txt:
`
set(EASTL_ROOT_DIR /home/manolis/Desktop/EASTL)
include_directories (${EASTL_ROOT_DIR}/include)
include_directories (${EASTL_ROOT_DIR}/test/packages/EAAssert/include)
include_directories (${EASTL_ROOT_DIR}/test/packages/EABase/include/Common)
include_directories (${EASTL_ROOT_DIR}/test/packages/EAMain/include)
include_directories (${EASTL_ROOT_DIR}/test/packages/EAStdC/include)
include_directories (${EASTL_ROOT_DIR}/test/packages/EATest/include)
include_directories (${EASTL_ROOT_DIR}/test/packages/EAThread/include)
set(EASTL_LIBRARY debug ${EASTL_ROOT_DIR}/build/Debug/EASTL.lib optimized ${EASTL_ROOT_DIR}/build/Release/EASTL.lib)
add_custom_target(NatVis SOURCES ${EASTL_ROOT_DIR}/doc/EASTL.natvis)
link_directories (${EASTL_ROOT_DIR}/include)
link_directories (${EASTL_ROOT_DIR}/include/test/packages/EABase/include/Common)
link_directories (${EASTL_ROOT_DIR}/build/libEASTL.a)
`

**Comment by rparolin** [comment]
Have you look at this documentation?
https://github.com/electronicarts/EASTL/blob/master/doc/CMake/EASTL_Project_Integration.md

**Comment by rparolin** [comment]
I'll close this issue and we re-open if you discover an issue.
