### ISSUE TITLE
Is expected behavior?

### ISSUE THREAD

**Issue by n2468** [electronicarts/EASTL#385]
As an junior amateur programmer, I took a look at this library(cause is from EA), and tried to use it. 
In class array.h, the method validate_iterator is implemented like that:
template <typename T, size_t N>
	inline int array<T, N>::validate_iterator(const_iterator i) const
	{
		if(i >= mValue)
		{
			if(i < (mValue + N))
				return (isf_valid | isf_current | isf_can_dereference);

			if(i <= (mValue + N))
				return (isf_valid | isf_current);
		}

		return isf_none;
	}
and in class iterator.h we have:
enum iterator_status_flag
	{
		isf_none            = 0x00, /// This is called none and not called invalid because it is not strictly the opposite of invalid.
		isf_valid           = 0x01, /// The iterator is valid, which means it is in the range of [begin, end].
		isf_current         = 0x02, /// The iterator is valid and points to the same element it did when created. For example, if an iterator points to vector::begin() but an element is inserted at the front, the iterator is valid but not current. Modification of elements in place do not make iterators non-current.
		isf_can_dereference = 0x04  /// The iterator is dereferencable, which means it is in the range of [begin, end). It may or may not be current.
	};

I expected that method validate_iterator to return an int which is only from enum iterator_status_flag, but considering how it is implemented it returns 7 (cause 1 | 2 | 4 = 3 | 4 = 7 ), or 3 ( cause 1 | 2 =  3),  if first branch is true. This numbers are not iterator_status_flag.
What are the meaning of  7 and 3? Is this method expected to work like that, or it is incorrectly implemented?

**Comment by DBJDBJ** [comment]
[Scoped enumerations](https://en.cppreference.com/w/cpp/language/enum)  are a "good thing".

EASTL covers a lot of platforms and tries to cover a lot of compilers and a lot of C++ standards. Thus it can not do scoped enumerators.
```cpp
// spot the class keyword 
enum class iterator_status_flag
```
```cpp
template <typename T, size_t N>
inline 
iterator_status_flag  /* not an int any  more*/
array<T, N>::validate_iterator(const_iterator i) const
{
if(i >= mValue)
{
 
if(i < (mValue + N))
return 
( iterator_status_flag::isf_valid | iterator_status_flag::isf_current |  iterator_status_flag::isf_can_dereference);

 if(i <= (mValue + N))
	return (iterator_status_flag::isf_valid | iterator_status_flag::isf_current);
 }
return iterator_status_flag::isf_none;
}
```
All of a sudden it is all clear. But that is a dream. 

In your C++ code always use scoped iterators.

**Comment by n2468** [comment]
Thank you for the answers but i didn't get it. I tried but...
If you don't mind, in which file.h does this statement appear:
> // spot the class keyword 
> enum class iterator_status_flag
?
In iterator. h  we have just:
namespace eastl
{
     enum iterator_status_flag
     {
           isf_none            = 0x00,
           isf_valid           = 0x01,
           isf_current         = 0x02,
           isf_can_dereference = 0x04
     };
}

Inside method       int array<T, N>::validate_iterator(const_iterator i) const      are those (bitwise OR) operations?
And yet how do I actually use the method validate_iterator( ) at first sight (just from definition, without looking at implementation)? 
Let's say we have an array called xArr with 5 int's, and 
auto iter = xArr.begin();
int result = xArr.validate_iterator(iter);
if(WHAT???)
{
    print("Iterator points to an element inside xArr boundary");
}
else
{
   print("Iterator points to an element outside xArr boundary");
}

iter = iter + 10;
reapeat if/ else part (or call a function which do the same if / else part) ;

Can you please complete my example? maybe that's how I understand how to use validate_iterator().

**Comment by DBJDBJ** [comment]
No time + hard work = quick answer.  First please [read this](https://en.cppreference.com/w/cpp/language/enum). 
Scoped enum is a distinctive type, that is the key advantage
```cpp
// iterator_status_flag  is a unique type
enum class iterator_status_flag { isf_none = 0x00, isf_valid = 0x01, isf_current = 0x02, isf_can_dereference = 0x04 } ;
```
It is not possible to compile a mistake made with the above enum
```cpp
// does not compile
int bug1 = isf_none ;
// does not compile
int bug2 = iterator_status_flag ::isf_none ;
```
Legacy aka "old" enums are just `int`. They have no type hence it is easy to make a mistake
```cpp
// legacy_iterator_status_flag  is just an int
enum legacy_iterator_status_flag { isf_none = 0x00, isf_valid = 0x01, isf_current = 0x02, isf_can_dereference = 0x04 } ;
//
int ok_1 = isf_none ;
int ok_2 = isf_valid ;
// does not compile
legacy_iterator_status_flag ::isf_valid ;
```
AFAIK, class enums do not exist in EASTL. Hence the comment "spot the class keyword". There are ISO C++ standard enums as classes, aka "scoped enums". 
```cpp
// spot the class keyword
enum class iterator_status_flag { isf_none = 0x00, isf_valid = 0x01, isf_current = 0x02, isf_can_dereference = 0x04 };
```
That is called "scoped" because we can use the C++ scope operator aka `::` on its elements. Example:
```cpp
if ( iterator_status_flag::isf_valid ) cout << "Iterator is valid" ;
if ( iterator_status_flag::isf_valid &&  iterator_status_flag::isf_current ) cout << "Iterator is valid and current" ;
```
you can not do that on legacy enums. Also coming from C. And in C there is no scope operator at all. 
```cpp
// problem 1: result type is not unique, it is int
int result = xArr.validate_iterator(iter);
if( result  == isf_valid )
print("Iterator is valid, it probably points to an element inside xArr boundary");
else
print("Iterator is not valid, it probably does point to an element outside xArr boundary");
```
Invalid iterator is a big conceptual problem, Please [read about that here](https://thispointer.com/stdvector-and-iterator-invalidation/#:~:text=What%20is%20Iterator%20Invalidation%3F,points%20to%20old%20invalid%20location.).
