### ISSUE TITLE
Where in the design is the alligned deallocation ?

### ISSUE THREAD

**Issue by DBJDBJ** [electronicarts/EASTL#388]
There is no aligned deallocation. EASTL allocator design has allocate and aligned allocate. But only one (non-aligned) deallocate.  Where do we the Windows serfs put the [`_aligned_free'](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/aligned-free?view=vs-2019)?  

A re-design  perhaps:
```cpp
namespace eastl {
struct heap_memory final {
 static void* allocate(size_t n, int flags = 0) noexcept ;
 static void* allocate_aligned(size_t n, size_t alignment, size_t offset, int flags = 0) noexcept ;
 static void  deallocate(void* p, size_t n) noexcept ;
 static void  deallocate_aligned (void* p, size_t n) noexcept ;
} ; // heap_memory
} // eastl
```
With optional locking inside, with default or no default user required implementations.

**Comment by DBJDBJ** [comment]
Of course, this is very unlikely to be completely re-done.  In the comfort of my own little repo I just did it and it works. Files removed though but not that much.  "vector of strings" test is on average 50% faster vs MS STL. 

Back to reality. Probably the easiest thing to do is to do this:

```cpp
 namespace eastl
 {
     // logical allocator
     class allocator
     {
         allocator(const char* pName = NULL);
         void* allocate(size_t n, size_t alignment, size_t offset, int flags = 0);
         void  deallocate(void* p, size_t n);
         const char* get_name() const;
         void        set_name(const char* pName);
     };
}
```
And then have two default allocators one for aligned and one for non aligned allocation. And use them as defaults as required. From containers point of view this might work with no changes whatsoever:
```cpp
basic_string< T, default_allocator > ;
vector< T , default_aligned_allocator > ;
```
Somehow I envisage the endless debate ...

**Comment by Valakor** [comment]
My solution to this was to always use the aligned path in a way that (I think) mimics what plain `malloc` does: my implementation of `allocate(size_t n, int flags = 0)` is simply to call the aligned allocation method with an alignment of `alignof(std::max_align_t)`. In my testing this is 16 on MacOS and 8 on Windows. My deallocate function then always assumes "aligned" deallocation. This is effectively what calls to malloc/free do on Windows (I think they just call _aligned_malloc with an alignment of 8 and _aligned_free respectively).

**Comment by DBJDBJ** [comment]
Noble @Valakor , yes technically you are right. But we/you, are here trying to rectify the design flaw. And that is not good.

In the meantime, I have created [EASTL2020CORE ](https://github.com/DBJDBJ/EASTL2020CORE) were (as far as I can remember) I have implemented what I have presented above. It was "only" 29 days ago, but now it is in a distant galaxy ...I just remember it all works with a lot of stuff taken out, hence the "CORE" suffix.  Ok, let me try and document it ...

**Comment by alecazam** [comment]
Note that x64 is 16-byte alignment.  macOS/iOS are 16-byte as well.  Also libraries like Apple's Accelerate simd library always align to 16-bytes, so no alignment desginators are needed on 64-bit apps.  That holds even for 32-byte and larger types.

**Comment by DBJDBJ** [comment]
may I be so bold as to remind the honourable readership Windows makes a distinctive function out of aligned free? Please see the initial text/comment.

hint: in the case of API **addition** there is no breaking of the existing code.

**Comment by alecazam** [comment]
When we first built eastl, one of the primary alignment uses was 16bytes for simd.  Since Microsoft never provided an override of the 8-byte default on x86, but changed it for x64.   Given the lack of aligned realloc/free elsewhere, except on Windows, I would just skip alignment handling entirely and use the system default.

**Comment by DBJDBJ** [comment]
@alecazam I would too. In the meantime what to do with EASTL and self-inflicted API lack of Windows coverage? 

One can pronounce it as not that important, it seems :)

To be brutally honest, I do not use EASTL anymore. I use MS STL  in its `/D_HAS_EXCEPTIONS=0` form. Hidden in plain sight. Completely non-standard full [SEH](https://docs.microsoft.com/en-us/cpp/cpp/structured-exception-handling-c-cpp?view=msvc-160) enabled fully covered and maintained STL. "My" C++ style I have discovered has a name too. [Orthodox C++](https://gist.github.com/bkaradzic/2e39896bc7d8c34e042b).

That is only if, I am forced to stay within the C++ dead end. Most of my code is C99 or better, these days.
