### ISSUE TITLE
EASTL w/ vcpkg does not work correctly

### ISSUE THREAD

**Issue by xgalaxy** [electronicarts/EASTL#390]
As reported multiple times here:
https://github.com/microsoft/vcpkg/issues/11262
https://github.com/microsoft/vcpkg/issues/12734

Using vcpkg EABase headers are getting installed into Common/EABase but EASTL headers only use EABase not Common/EABase when including headers and thus EASTL headers are unable to properly find the headers when using vcpkg.

Vcpkg claims this is an issue with EASTL and not their fault and so they keep closing tickets.
So I am opening this ticket here hoping this issue can finally be resolved.

EASTL is unusable w/ vcpkg since at least June.

**Comment by gvanem** [comment]
Further, clang-cl bitches about the casing of the files. This is not the fault of VCPKG. Ton of warnings like:
```
In file included from f:/src/CPP/EASTL/include/EASTL\string.h:93:
f:/src/CPP/EASTL/include\EASTL/internal/config.h(61,11): warning: non-portable path to file '<Eabase/eabase.h>';

      specified path differs in case from file name on disk [-Wnonportable-include-path]
        #include <EABase/eabase.h>
 ```

Manually renaming `Eabase` to `EABase` fixed the warning.

**Comment by xgalaxy** [comment]
Honestly, if EA isn’t going to take this issue seriously they need to stop advertising vcpkg in the readme.

**Comment by rparolin** [comment]
Sorry.  We don't have the capacity to support different distribution methods.  We've included mentions of vcpkg in our readme to highlight others work but don't intended to support it.  If this is misleading we can certainly remove vcpkg from the readme.

**Comment by rparolin** [comment]
I'm going to close this issue; but if there changes like the path casing change that we can make vcpkg work again please submit them and we discuss those specific library changes.
