### ISSUE TITLE
Benchmarks crash with optimizations enabled and dynamic runtime on MinGW

### ISSUE THREAD

**Issue by DragoonX6** [electronicarts/EASTL#40]
Both Clang and GCC (MinGW) crash seemingly in the string benchmarks when optimizations are enabled and they link to the dynamic runtime. No crash happens with static runtime, but this could probably be a deeper problem in EASTL or libstdc++, needs investigating.

From my debugging it appears that the libstdc++ deleter calls into EASTL's global allocator deleter, which calls aligned_free, this causes it to crash. I personally have no idea how to fix it, help wanted.

**Comment by DragoonX6** [comment]
GCC 32 bit debug builds also have the tests break. This is a problem with operator delete's resolution, it's probably a bug in the mingw-w64 CRT. I'll be looking to fix that ASAP.

**Comment by DragoonX6** [comment]
Ok, it's not a bug in the MinGW-w64 CRT. The problem lies in libstdc++ calling new internally (in the dll), so runtime symbol resolution doesn't pick up our operator new overrides, or operator delete for that matter.
I'll experiment with some changes soon, I hope that'll fix it. For now we should link to static libstdc++ to stop it from crashing.

**Comment by rparolin** [comment]
I believe this was fixed with your latest PR as well.  Close?

**Comment by DragoonX6** [comment]
Currently we use the -static-libstdc++ flag as a workaround, I'd prefer if we properly fixed this issue if possible. I still have to experiment with some changed that I think might fix the problem, but I'm not too sure if that's something we'd want to use in the actual code. Perhaps if it actually fixes the problem we could put it up as an FAQ entry, might end up being too intrusive.

**Comment by DragoonX6** [comment]
So I did a bit of testing with the wrap functionality of ld, to no avail.
I'm going to investigate a bit in how msvc does it, pretty sure they just make sure no allocation happens outside of headers, in which case I'm going to have to submit patches to libstdc++ to fix that. Or we could write a generic allocator, which will allocate in the executables itself.

I think DLLs could definitely benefit from weak symbols on windows, but I don't know if that's ever going to be a possibility.

Keep the -static-libstdc++ flag for now :/
