### ISSUE TITLE
Submodule cloning error.

### ISSUE THREAD

**Issue by CybernetHacker14** [electronicarts/EASTL#410]
First of all, the effort to establish such a great piece of technology and then to open source it, is a great gesture, much appreciated.

I tried adding this repository as a submodule to an existing project. It got cloned properly. However, the nested submodules inside this repository - EABase, EAStdC, didn't got cloned properly - there was an error during updating the submodules of EASTL.

The messages stated things as - 
```
please make sure you have the correct access rights and the repository exists.
```  
and
```
fatal: clone of 'git@github.com:electronicarts/EAAssert.git' into submodule path '<path-to-EASTL>/test/packages/EAThread/test/packages/EAAssert' failed
``` 
turned up. This was for all submodules of EASTL. 

Does adding EASTL as a submodule require operating the repository through `SSH` only? Is `HTTPS` not supported?

**Comment by ChuckStarchaser** [comment]
I've been having all kinds of problems similar to this, and wasn't using git, or installing as a module.  First I tried to install it using conan, and there were no cpp files anywhere, and no CMakeList.txt files. Could not find a solution.
Then I tried downloading the zip file, but the 6 sub-packages under test/packages are empty folders in the zip.
I was about to try git, but came to look at the issues first, and found yours.

**Comment by ChuckStarchaser** [comment]
UPDATE:  I managed to solve my problem.  I discovered that each of those 6 subpackages, if you go into the folder in github the green Code button lights up and you can download as zip or git the particular library.  Once I did, CMake worked, then Make worked.

**Comment by CybernetHacker14** [comment]
I was trying to add this repo as a submodule, and this repo also has submodules inside it. If someone wants to checkout the latest updates to whatever was done, he/she has to go to great lengths to have all of the submodules checked out on latest version.

**Comment by zkxjzmswkwl** [comment]
This is still fucked.

**Comment by iyadahmed** [comment]
> This is still fucked.

yes

**Comment by iyadahmed** [comment]
> UPDATE: I managed to solve my problem. I discovered that each of those 6 subpackages, if you go into the folder in github the green Code button lights up and you can download as zip or git the particular library. Once I did, CMake worked, then Make worked.

this seems to be a nice workaround for now

**Comment by omartijn** [comment]
The submodules are really messed up, because they are recursive. There is a circular reference between some of the submodules, so the clone never ends, and it'll keep going deeper and deeper into subdirectories with endless copies of submodule repos.
