### ISSUE TITLE
contiguous_iterator_tag is not standard

### ISSUE THREAD

**Issue by csc-at-mp** [electronicarts/EASTL#42]
EASTL adds contiguous_iterator_tag, but then code does not compile with
# define EASTL_STD_ITERATOR_CATEGORY_ENABLED 1

since this iterator tag is not in C++ before 2017.

**Comment by rparolin** [comment]
That's correct.  EASTL had the concept of a contiguous iterator before it was standardized as an optimization.

**Comment by rparolin** [comment]
'contiguous_iterator_tag' was an extension/optimization made before the recent standardization of the tag.  Makes sense that other stdlib implementations don't have that and that compiler switch obviously hasn't been tested recently.  I don't know how important it would be to support interoping eastl::iterator types with std::iterator types moving forward.  

Thoughts?

**Comment by csc-at-mp** [comment]
We are interested in compatibility with STL algorithms, so we're using
std::iterator compatibility.  I don't know how common this use case will
be, however.
