### ISSUE TITLE
warning C4103 with Visual Studio 2019 16.9.2 version

### ISSUE THREAD

**Issue by Alekssasho** [electronicarts/EASTL#420]
Compiling my code which has the following:

#include <EASTL/string.h>
#include <glm/glm.hpp>

Issues a warning
" warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop)". 

If first glm.hpp is included and then string.h it compiles correctly.
#include <glm/glm.hpp>
#include <EASTL/string.h>

**Comment by ljluestc** [comment]
```

#include <glm/glm.hpp>
#pragma pack(push, 8)  // Preserve the current alignment settings
#include <EASTL/string.h>
#pragma pack(pop)      // Restore the original alignment settings
```

**Comment by jhopkins-ea** [comment]
that's an issue with glm, not eastl. they've probably fixed it a long time ago by now.
