### ISSUE TITLE
Question / Proposal: Replace git submodules with CMake FetchContent

### ISSUE THREAD

**Issue by xgalaxy** [electronicarts/EASTL#433]
CMake supports bringing in dependencies via FetchContent. See:
https://cmake.org/cmake/help/v3.19/module/FetchContent.html

FetchContent is supported and works great in Visual Studio (when using Microsoft's built in CMake integration), Visual Studio Code (when using appropriate extensions), as well as in CLion. And obviously works with CMake on command line.

I propose replacing this projects git submodules with FetchContent. And I would be willing to offer my time and support in adding this feature. 

I think this would have a number of benefits:
1. git submodules are a pain in the butt and no one likes them
2. if you aren't careful with how you clone EASTL you can end up downloading EASTL forever because the submodules EASTL bring in recursively depend on each other
3. a side effect of 2 is that if you do happen to use submodules for your project you cant include EASTL as a submodule if another submodule you depend on requires `--recursive`
4. the git submodules have a goofy interaction in some cases where even though the root level is requested w/ HTTPS the subsequent submodule requests end up attempting SSH calls that will fail if SSH isn't properly setup on the system

All of these things added together can be confusing and off putting to new adopters as evidence by the fact that there are numerous tickets that have been opened & closed over the years regarding this.

CMake FetchContent avoids all of that nonsense and still allows for the different projects to be worked on independently from each other. It also allows for improved versioning between the different sub projects as EASTL using FetchContent can request a particular git hash or a particular tagged version.

The negatives:
1. The minimum supported CMake version is 3.11. But realistically you'd want a later version since there are fixes to how FetchContent works in later versions and it's unknown to me if any of those fixes would be necessary to get EASTL converted.
2. Requires updating the CMakeLists.txt file for multiple repos. However I think the minimum viable solution would only require EASTL repo changes.

**Comment by MaverickAl** [comment]
"a side effect of 2 is that if you do happen to use submodules for your project you cant include EASTL as a submodule if another submodule you depend on requires --recursive"

This is causing me issues after updating EASTL on an old repo, to the point where it seems easier to just return to an older version.

**Comment by omartijn** [comment]
I think this is a great idea. I've also run into the issue of endlessly cloning eastl due to recursive submodules. I consider that a bug, which could be nicely fixed this way.

**Comment by jhopkins-ea** [comment]
I have been experimenting with FetchContent and this works for me without any changes to EASTL or any of its dependencies:
```
FetchContent_Declare(
    EASTL
    GIT_REPOSITORY          https://github.com/electronicarts/EASTL.git
    GIT_TAG                 master
    GIT_SUBMODULES_RECURSE  OFF
    GIT_SHALLOW             ON
)

FetchContent_MakeAvailable(
    EASTL
)

add_dependencies(example EASTL)
target_link_libraries(example
    PRIVATE
    EASTL
)
```

They key thing is to use `GIT_SUBMODULE_RECURSE OFF` and `GIT_SHALLOW ON`.
