### ISSUE TITLE
functional.h is missing "typename T" in some template declarations

### ISSUE THREAD

**Issue by csc-at-mp** [electronicarts/EASTL#44]
On lines 105 and 128 in this file, the template does not specify "typename T", only "typename Allocator".  Hence, it does not compile on all platforms.

**Comment by rparolin** [comment]
Can you provide more information?  what compiler/os/compiler errors?

**Comment by csc-at-mp** [comment]
gcc-4.9 and clang-3.5 for Android NDK version r10d.  The compilers correctly identify the symbol T as undeclared in the template.

**Comment by xaxxon** [comment]
What lines are causing the error?  I don't see anything like that in functional.h

**Comment by rparolin** [comment]
I'm not following.  If this continues to be a problem please re-open an issue with more details and PR.
