### ISSUE TITLE
Natvis not parsing {nullptr}

### ISSUE THREAD

**Issue by redorav** [electronicarts/EASTL#448]
In any expression where the natvis wants to evaluate {nullptr} (note how it's in curly brackets), the natvis fails to show it properly. For example shared_ptr:

```
<DisplayString Condition="mpValue != nullptr">({(void*)mpValue} = {*mpValue})</DisplayString>
<DisplayString Condition="mpValue == nullptr">({nullptr})</DisplayString>
```

This is happening in Visual Studio 2019.

Removing the brackets (nullptr) makes it work again. Sounds like an easy fix and makes debugging much easier. Thanks!

**Comment by ljluestc** [comment]
```

<Type Name="std::shared_ptr&lt;*&gt;">
    <DisplayString Condition="mpValue != nullptr">({(void*)mpValue} = {*mpValue})</DisplayString>
    <DisplayString Condition="mpValue == nullptr">nullptr</DisplayString>
</Type>
```
