### ISSUE TITLE
eastl::basic_string::npos should be defined outside of the class

### ISSUE THREAD

**Issue by csc-at-mp** [electronicarts/EASTL#45]
For example, declare but do not define it in the basic_string template, then define it outside:
template <typename T, typename Allocator>
const typename basic_string<T, Allocator>::size_type basic_string<T, Allocator>::npos = (basic_string<T, Allocator>::size_type)(-1);

**Comment by rparolin** [comment]
What's the rational behind this change?

**Comment by csc-at-mp** [comment]
C++ correctness:
http://stackoverflow.com/questions/17056882/c-static-const-member-variable-usage

**Comment by rparolin** [comment]
could provide a test case where this is an issue?  That way we can prevent regressions in the future.

**Comment by csc-at-mp** [comment]
I tried but was not able to reproduce the case in which the code as-is fails.  However, we know linker errors are possible on some compilers when npos is read from outside of eastl::basic_string.

**Comment by rparolin** [comment]
Due to time pressures, I prefer to work on issues that provably broken with a test case.  In the absence of that I'm hesitant apply code changes.  I'm happy to look at PR once a test case is provided.
