### ISSUE TITLE
is_const<T> is broken in MSVC 2022

### ISSUE THREAD

**Issue by BlamKiwi** [electronicarts/EASTL#456]
I am trying to build an existing project in Visual Studio 2022. Trying to use is_const<T> with rvalues is causing compiler issues. The easiest way to reproduce this is to make an eastl::pair that contains an rvalue as a type in C++17 mode. 

`type_traits.h(628): error C2528: 'abstract declarator': pointer to reference is illegal`

A quick fix is to add a template specialization for rvalues, but I don't know if this is correct behaviour according to STL spec.

    template <typename T> struct is_const_value                    : public eastl::false_type{};

    template <typename T> struct is_const_value<const T*>          : public eastl::true_type{};

    template <typename T> struct is_const_value<const volatile T*> : public eastl::true_type{};

    template <typename T> struct is_const : public eastl::is_const_value<T*>{};

    template <typename T> struct is_const<T&> : public eastl::false_type{}; 

    template <typename T> struct is_const<T&&> : public eastl::false_type{};

**Comment by grojo-ea** [comment]
Thanks for bringing this up. We've made some fixes to `is_const` recently which I believe should fix this issue (these changes landed in https://github.com/electronicarts/EASTL/pull/501).
