### ISSUE TITLE
Including inttypes.h after eabase.h produces warnings on VS2015

### ISSUE THREAD

**Issue by JohanKotlinskiAtKing** [electronicarts/EASTL#47]
#include "EABase\eabase.h"
    #include <inttypes.h>

produces warnings on VS2015, update 2:

1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(109): warning C4005: 'PRId8': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(402): note: see previous definition of 'PRId8'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(112): warning C4005: 'PRId64': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(424): note: see previous definition of 'PRId64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(125): warning C4005: 'PRIdPTR': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(432): note: see previous definition of 'PRIdPTR'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(128): warning C4005: 'PRIi8': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(403): note: see previous definition of 'PRIi8'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(131): warning C4005: 'PRIi64': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(425): note: see previous definition of 'PRIi64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(144): warning C4005: 'PRIiPTR': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(433): note: see previous definition of 'PRIiPTR'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(147): warning C4005: 'PRIo8': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(404): note: see previous definition of 'PRIo8'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(150): warning C4005: 'PRIo64': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(426): note: see previous definition of 'PRIo64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(163): warning C4005: 'PRIoPTR': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(434): note: see previous definition of 'PRIoPTR'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(166): warning C4005: 'PRIu8': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(405): note: see previous definition of 'PRIu8'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(169): warning C4005: 'PRIu64': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(427): note: see previous definition of 'PRIu64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(182): warning C4005: 'PRIuPTR': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(435): note: see previous definition of 'PRIuPTR'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(185): warning C4005: 'PRIx8': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(406): note: see previous definition of 'PRIx8'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(188): warning C4005: 'PRIx64': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(428): note: see previous definition of 'PRIx64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(201): warning C4005: 'PRIxPTR': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(436): note: see previous definition of 'PRIxPTR'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(204): warning C4005: 'PRIX8': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(407): note: see previous definition of 'PRIX8'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(207): warning C4005: 'PRIX64': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(429): note: see previous definition of 'PRIX64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(220): warning C4005: 'PRIXPTR': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(437): note: see previous definition of 'PRIXPTR'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(230): warning C4005: 'SCNd8': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(462): note: see previous definition of 'SCNd8'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(233): warning C4005: 'SCNd64': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(481): note: see previous definition of 'SCNd64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(246): warning C4005: 'SCNdPTR': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(488): note: see previous definition of 'SCNdPTR'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(249): warning C4005: 'SCNi8': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(463): note: see previous definition of 'SCNi8'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(252): warning C4005: 'SCNi64': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(482): note: see previous definition of 'SCNi64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(265): warning C4005: 'SCNiPTR': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(489): note: see previous definition of 'SCNiPTR'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(268): warning C4005: 'SCNo8': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(464): note: see previous definition of 'SCNo8'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(271): warning C4005: 'SCNo64': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(483): note: see previous definition of 'SCNo64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(284): warning C4005: 'SCNoPTR': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(490): note: see previous definition of 'SCNoPTR'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(287): warning C4005: 'SCNu8': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(465): note: see previous definition of 'SCNu8'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(290): warning C4005: 'SCNu64': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(484): note: see previous definition of 'SCNu64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(303): warning C4005: 'SCNuPTR': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(491): note: see previous definition of 'SCNuPTR'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(306): warning C4005: 'SCNx8': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(466): note: see previous definition of 'SCNx8'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(309): warning C4005: 'SCNx64': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(485): note: see previous definition of 'SCNx64'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\inttypes.h(322): warning C4005: 'SCNxPTR': macro redefinition
1>  C:\Users\johan.kotlinski\Desktop\EASTL\test\packages\EABase\include\Common\EABase\eabase.h(492): note: see previous definition of 'SCNxPTR'

**Comment by rparolin** [comment]
EABase will include "inttypes.h" directly for you.

**Comment by JohanKotlinskiAtKing** [comment]
In practice it is a problem, because another software package I use includes inttypes.h in its public headers.

**Comment by rparolin** [comment]
You can try defining 'EA_COMPILER_HAS_C99_FORMAT_MACROS' before EABase as it prevents the definition of the C99 format specifiers you cite are causing the problem.  Other than that I don't have any other ideas as the C standard doesn't specify a method to prevent inttypes.h from defining them.

**Comment by JohanKotlinskiAtKing** [comment]
The following changes fix the problem for me, and the test suite still passes. Is it something that could be included main line?

`diff --git a/test/packages/EABase/include/Common/EABase/eabase.h b/test/packages/EABase/include/Common/EABase/eabase.h
index 4fd16e5..089e3bb 100644
--- a/test/packages/EABase/include/Common/EABase/eabase.h
+++ b/test/packages/EABase/include/Common/EABase/eabase.h
@@ -114,8 +114,8 @@
           #define __STDC_FORMAT_MACROS
        #endif
        // The GCC PSP compiler defines standard int types (e.g. uint32_t) but not PRId8, etc.
-       // MSVC doesn't include an inttypes.h header.
-       #if !defined(EA_COMPILER_MSVC)
+       // Old MSVC versions do not include an inttypes.h header.
+       #if !defined(EA_COMPILER_MSVC) || _MSC_VER >= 1900
                #include <inttypes.h> // PRId8, SCNd8, etc.
        #endif
        #if defined(_MSC_VER)
@@ -355,7 +355,7 @@
        typedef double              double_t;
 #endif

-#if defined(EA_COMPILER_HAS_INTTYPES) && !defined(EA_COMPILER_MSVC)
+#if defined(EA_COMPILER_HAS_INTTYPES) && (!defined(EA_COMPILER_MSVC) || _MSC_VER >= 1900)
        #define EA_COMPILER_HAS_C99_FORMAT_MACROS
 #endif
`

**Comment by rparolin** [comment]
I did some googling but I couldn't find the anything about MS now including the inttypes.h file which is part of the C99 standard.
