### ISSUE TITLE
GCC 11 compilation error - "template-id not allowed for destructor"

### ISSUE THREAD

**Issue by nebularnoise** [electronicarts/EASTL#471]
https://github.com/electronicarts/EASTL/blob/29a805e4d83d7dd1d8fb03f303b132cc8c0a51c9/include/EASTL/internal/type_pod.h#L1724

Since the implementaiton of DR 2237 "disallow simple-template-id in cdtor", the line of code above is not longer valid, and throws the following compilation error:
`error: template-id not allowed for destructor`

I believe the fix is just to ommit the `<T>` after the dtor name.

**Comment by nicolasnoble** [comment]
This prevents compiling with gcc in C++20 mode fwiw.

**Comment by grojo-ea** [comment]
Hello, thanks for the report. This should be fixed after #477.
