### ISSUE TITLE
it can not be compile on gcc4.4.4

### ISSUE THREAD

**Issue by lilothar** [electronicarts/EASTL#48]
it it can not cmpile on gcc 4.4.4, some feature gcc4.4.4 not support, can it is may support that version?

**Comment by pmcmorris** [comment]
Given the weak support for modern C++ features on that version of gcc, I think its unlikely.

https://gcc.gnu.org/gcc-4.4/cxx0x_status.html

It would be significant work in working around issues and disabling features for little gain in terms of value as most of the platforms we support are either on newer versions of gcc or have already transitioned to clang.

Have you considered upgrading to gcc 4.7 or 4.8?

**Comment by rparolin** [comment]
I'd agree.  I haven't published an official platform and compiler support
matrix yet in an effort to see what the needs of the community are.  But I
will be aggressively moving towards modern compilers and techniques as much
as practical.

**Comment by lilothar** [comment]
I know gcc 4.4 weakly support c++ new feature, I also can compile it with clang with libcxx3.8 integrate it in peoject, for large scale server like 10000+ or more server to update gcc or install clang libs against may  applications already run on the server ,it is not a regular way to do that, and hav some dangous. for example ,we can use swap to instead of std::move to compitable the compiler,  I think, or I need to compile all the applications to upgrade compilers

**Comment by lilothar** [comment]
may be , I need to trans current version to fit gcc 4.4 myself ,but it is so comfusion on me, it seems worse time to do this

**Comment by DragoonX6** [comment]
If you have clang 3.8 as you said, you can just compile it with that and use it with clang.

**Comment by rparolin** [comment]
Since GCC 4.4.4 is now a 6 year old compiler its unlikely we will circle back.  If you wish to contribute fixes back that enable it to build I'll happily look at them.  I'll close this issue unless there is an objection.
