### ISSUE TITLE
Cannot build EASTL_ITC_NS::contiguous_iterator_tag with EASTL_STD_ITERATOR_CATEGORY_ENABLED on C++17 compiler

### ISSUE THREAD

**Issue by eugeneko** [electronicarts/EASTL#482]
Pretty much title. After commit #477 I cannot build with C++17 compiler and `EASTL_STD_ITERATOR_CATEGORY_ENABLED`, because `EASTL_ITC_NS::contiguous_iterator_tag` is resolved as `std::contiguous_iterator_tag` which is obviously undefined.
I would make a PR but I am not sure how the fix should look like.

**Comment by grojo-ea** [comment]
Thanks for bringing this up, we don't currently build internally with `EASTL_STD_ITERATOR_CATEGORY_ENABLED`. 

We'll look into what the correct way of fix this is and into setting up come CI coverage for when `EASTL_STD_ITERATOR_CATEGORY_ENABLED` is defined so things like this don't slip through.

**Comment by grojo-ea** [comment]
I think this has been fixed with https://github.com/electronicarts/EASTL/pull/493, we also now check we can build with/without these defines as part of our CI pipeline as of 7b2a478176efcfbf414b02f09b160b1c51ed925f so I'm closing this issue.
