### ISSUE TITLE
Figure out a fix for timing numbers in MingW

### ISSUE THREAD

**Issue by DragoonX6** [electronicarts/EASTL#50]
In the attached file [EASTLBenchmark output.txt](https://github.com/electronicarts/EASTL/files/417179/EASTLBenchmark.output.txt) you can see a lot of zeros and a lot of nans.
This is of course unacceptable when it comes to measuring any kind of performance.

An earlier [bug report on the GNU tracker](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63400) shows that this might be related to the chrono implementation with regards to pthreads. The OP points out that using steady_clock instead of high_resolution_clock yields more precise results and I can indeed confirm this, seen in the attached file: [EASTLBenchmark steady_clock output.txt](https://github.com/electronicarts/EASTL/files/417191/EASTLBenchmark.steady_clock.output.txt)
One other interesting thing is how this is 0.06 seconds faster too.

The OP also [links to the MingW mailing list](https://sourceforge.net/p/mingw-w64/mailman/message/31672495/) where somebody notes how this issue doesn't occur when using boost's chrono implementation.

So there are a few ways on how we can fix this:
- We simply switch to steady_clock on MingW builds.

   However this feels like a band-aid fix where I'm not sure the times recorded are as accurate as MS's implementation or on the other platforms.
- We use boost's chrono instead.

   This is an undesirable solution, as this introduces a huge dependency.
- We use boost's chrono, but rip it out of boost instead of introducing it as a dependency.

   This is less undesirable depending on the size of boost's chrono and could introduce licensing issues.
- We fall back to C API entirely.

   If this can be done with standard C code, it's perhaps the most desirable of the solutions, as it is guaranteed to work on all platforms. 
- We submit a patch to libstdc++.

   This is the most ideal solution in the long run, but this means the problem still remains, unless we combine it with one of the previous mentioned solutions.

Maybe an EASTL chrono is needed?
I think if we dig some deeper, the steady_clock switch might prove sufficient, if not, I think falling back to the C API might be the most desirable solution.

**Comment by rparolin** [comment]
I added chrono support to EASTL.  
https://github.com/electronicarts/EASTL/blob/master/include/EASTL/chrono.h

I believe you are refering to the EAStdC Stopwatch implementation that used the standard chrono.  EAStdC is a stub implementation that isn't used internally (fingers crossed that I can open source that soon)... We could definitely change that to use steady_clock instead of high_resolution_clock.

https://github.com/electronicarts/EASTL/blob/master/test/packages/EAStdC/include/EAStdC/EAStopwatch.h#L239

**Comment by DragoonX6** [comment]
I'm definitely willing to put in effort in official MingW support. I'm not sure how CI's work, but I don't think it's something I can't learn.

**Comment by DragoonX6** [comment]
Actually, would it be possible to use EASTL's chrono in EAStdC's stopwatch implementation? Or would that introduce a cyclic dependency?

**Comment by rparolin** [comment]
Yeah, that would be cyclic.

**Comment by DragoonX6** [comment]
Alright.
Can you hit me up on gitter so we can go over setting up the CI?

**Comment by rparolin** [comment]
Can we close this issue now?

**Comment by DragoonX6** [comment]
Not yet, I didn't include this in the PR to mainly keep it focused on appveyor.
I'll push another PR in a few minutes that includes the fix for MinGW.

**Comment by DragoonX6** [comment]
Fixed by PR #53.
