### ISSUE TITLE
Build with Clang15 results in warnings about deprecated builtins

### ISSUE THREAD

**Issue by mp-t** [electronicarts/EASTL#507]
Clang 15 emits the following warning:

> EASTL/internal/type_pod.h(194,74): error : builtin __has_trivial_constructor is deprecated; use __is_trivially_constructible instead [-Werror,-Wdeprecated-builtins] 32> struct has_trivial_constructor : public eastl::integral_constant<bool, __has_trivial_constructor(T) || eastl::is_pod<T>::value>{}; 32>

**Comment by grojo-ea** [comment]
Hello,

This issue should be resolved in version 3.21.12 (https://github.com/electronicarts/EASTL/pull/510). 

Please let us know if the issue persists.
