### ISSUE TITLE
compilation error due to `std::remove_reference`

### ISSUE THREAD

**Issue by toge** [electronicarts/EASTL#512]
I met compilation error on EASTL 3.21.12. 

```
In file included from include/EASTL/type_traits.h:1033,
                 from include/EASTL/internal/move_help.h:16,
                 from include/EASTL/functional.h:11,
                 from include/EASTL/internal/fixed_pool.h:28,
                 from source/fixed_pool.cpp:6:
include/EASTL/internal/type_transformations.h:500:74: error: 'remove_reference' in namespace 'std' does not name a template type
  500 |                 auto try_add_pointer(int) -> type_identity<typename std::remove_reference<T>::type*>;
      |                                                                          ^~~~~~~~~~~~~~~~
include/EASTL/internal/type_transformations.h:500:90: error: expected template-argument before '<' token
  500 |                 auto try_add_pointer(int) -> type_identity<typename std::remove_reference<T>::type*>;
```

Environments as follows:
- OS: Debian stretch
- Compiler: gcc 12.1.0
- EASTL: 3.21.12

I succeeded compilation on EASTL 3.17.03.

I think it is caused by modification of include/EASTL/internal/type_transformations.h.

https://github.com/electronicarts/EASTL/commit/1aa784643081404783ce6494eb2fcaba99d8f6a5#diff-6b653b7c05d254bf37fddd53af0feb52d423005e81fadbae783b1d8e6054d74e

I thknk `try_add_pointer(int)` should use `eastl::remove_reference`?

```
template <typename T>
auto try_add_pointer(int) -> type_identity<typename eastl::remove_reference<T>::type*>;
```

**Comment by jhopkins-ea** [comment]
Yes, you're right. I see there's references to std in array.h and span.h that shouldn't be there either.

**Comment by jhopkins-ea** [comment]
let me know if that branch fixes your issues and I'll merge if so.

**Comment by toge** [comment]
@jhopkins-ea 
Thanks for your quick action!
It works fine for me.

**Comment by RubenRBS** [comment]
@jhopkins-ea thanks a lot for fixing it so quickly :)

We're adding the latest release over at Conan (Thanks @toge for contributing it!) and as we were affected by this bug, I have just a few questions:
Is there a patch release in the future to pick this change up? Or if not, can you say if the next update is some time away still? We're currently considering applying the patch directly as a backport, but would much rather use a proper release.

Thanks a lot! :)

**Comment by jhopkins-ea** [comment]
EASTL releases are fairly ad hoc. I'd recommend backporting the fix for now.
