### ISSUE TITLE
Error of RBTreeDecrement function

### ISSUE THREAD

**Issue by KilluaAoki** [electronicarts/EASTL#522]
The implementation of this function does not account for the scenario where there is only a single node in the tree.

If this single node is passed to the RBTreeDecrement function at this point, according to the normal logic, it should return end(), which is the mAnchor node. But this function still returns the root node.

This could lead to some other errors, resulting in an infinite loop.

The link to the file: [red_black_tree.cpp](https://github.com/electronicarts/EASTL/blob/master/source/red_black_tree.cpp)

**Comment by KilluaAoki** [comment]
The implementation of this function does not account for the scenario where there is only a single node in the tree.

If this single node is passed to the RBTreeDecrement function at this point, according to the normal logic, it should return `end()`, which is the `mAnchor` node. But this function still returns the root node.

This could lead to some other errors, resulting in an infinite loop.

The link to the file: [https://github.com/electronicarts/EASTL/blob/master/source/red_black_tree.cpp](url)

**Comment by KilluaAoki** [comment]
The implementation of this function does not account for the scenario where there is only a single node in the tree.

If this single node is passed to the RBTreeDecrement function at this point, according to the normal logic, it should return end(), which is the mAnchor node. But this function still returns the root node.

This could lead to some other errors, resulting in an infinite loop.

The link to the file: [https://github.com/electronicarts/EASTL/blob/master/source/red_black_tree.cpp](https://github.com/electronicarts/EASTL/issues/url)

**Comment by KilluaAoki** [comment]
Furthermore, there is a mistake in the comment for the RBTreeDecrement function, where it is written as RBTreeIncrement function.

**Comment by jhopkins-ea** [comment]
You'll have to explain the issue you have further. RBTreeDecrement is an EASTL internal function - it shouldn't be called by users.

If you have a case that is calling RBTreeDecrement when there is no previous elements then it's likely that you are using the container/iterator incorrectly - such as calling decrement on an iterator that is equal to `begin()`. If you meeting the container & iterator requirements and believe there is an issue with rbtree please provide a small reproducible example of the issue.

**Comment by KilluaAoki** [comment]
Here is an example of what causes an infinite loop:
```c++
#include <iostream>

#include <map>

#include <EASTL/set.h>
#include <EASTL/map.h>

int main()
{
	eastl::map<int, int> map;

	map.insert(eastl::make_pair(100, 100));
	map.insert(eastl::make_pair(200, 200));

	for (auto it = map.lower_bound(200); it != map.end(); --it)
	{
		std::cout << "Key: " << (it->first) << "\n";
	}
}
```

For the above example, I briefly consulted the cppreference documentation on the lower_bound function, which states that it returns `end()` if the element cannot be found, for which I explicitly made a judgment call, but it still causes a dead loop.

Please point out if the above example does not satisfy the iterator requirements, as the documentation I consulted did not indicate undefined behavior related to this, and I apologize for that, but some standard libraries do avoid this.

**Comment by KilluaAoki** [comment]
ummm...., this is indeed discussing an undefined behavior, I'm very sorry about this and I will close this issues. But it may be avoidable, because there is no predecessor node to the root node of the tree structure, and it is more reasonable to return `end()` for this.
