### ISSUE TITLE
Deque implementation review

### ISSUE THREAD

**Issue by tschw** [electronicarts/EASTL#57]
Hi,

evaluating this promising library, I read into your implementation of `deque`. Here are some more or less random comments:
## 

As an easy to implement optimization:

Imagine we're backing a stack. Now we can run into that nasty situation where the structure fans out (push, pop, push, pop, push, pop... ) at a subarray boundary. In this case we will keep allocating and deallocating the topmost subarray.

To solve this problem we could make the deque less eager on freeing its subarrays; only freeing the second  once there are two spare subarrays.

With this optimization in place, we could further steal a spare subarray from one end when the other end needs it. This will allow for zero-allocation when backing a real queue and enqueue/dequeue happens in a balanced fashion. Arguably an even more interesting use case.
## 

I also read this
https://github.com/electronicarts/EASTL/blob/master/include/EASTL/deque.h#L2046-L2047
and it totally puzzles me. Why?!

A (standard STL) deque should guarantee pointer stability when growing at its ends. 

Also, I don't see where your implementation does otherwise, so I guess you might be just fine without that extra copy? I might be missing something. However, if this is really an issue, would probably be something worth fixing.

Online discussion on pointer stability:

http://stackoverflow.com/questions/23871677/stable-memory-addresses-using-a-std-container-like-vector-list-queue#23872017

http://stackoverflow.com/questions/3287801/pointers-to-elements-of-stdvector-and-stdlist#3287828
(standard reference given in David Rodriguez' comment).
## 

Constructor comment suggests you were struggling with an initialization scheme that doesn't need dynamic memory. I'm not really sure it's the tricky bit, but what has always worked for me is something like: 

```
intra_subarray_index_head := 0
// so push_front will step to the last element in "previous" (yet nonexistent) node,
// and

intra_subarray_index_tail := max_intra_subarray_index
// so push_back will step to the first element in "next" (yet nonexistent) node,
// this way stepping into a cold code path where checking for the special case
// of initialization won't hurt (and the counting scheme can be changed).
```

**Comment by tschw** [comment]
This post got the wrong qualifier. It's actually two suggested `enhancement`s and one `bug`:

Please re-read my post, or, if it's too long, just re-read your code I cited above and keep in mind that `deque::emplace_back` should never ever change the memory locations of elements already in the container.

**Comment by rparolin** [comment]
For emplace_back, its  not clear to me what change you are suggesting?  I'd agree this code is subtle and I'm not exactly sure what guarantee the standards for moving elements that originate from within the container.  I'd have to read up on that.

**Comment by tschw** [comment]
> I'm not exactly sure what guarantee standards give for moving elements that originate from within the container. I'd have to read up on that.

`<cite, from the second stackoverflow given above>`
§23.2.1.3 guarantees that while iterators into the dequeue are invalidated, pointers and references to the elements are still valid: An insert in the middle of the deque invalidates all the iterators and references to elements of the deque. An insert at either end of the deque invalidates all the iterators to the deque, but has no effect on the validity of references to elements of the deque.
`</cite>`

So there would be the paragraph to verify.

This means that `deque::emplace_back` must never reallocate the objects, it may have to do so for the bookkeeping data, but that's about how far it goes (other than `std::vector::emplace_back` which *will* eventually relocate the objects).

> For emplace_back, its not clear to me what change you are suggesting?

Get rid of that subtle and inefficient dance and just go
```
if need be {
   grow container
}
call placement new the reference which must still be valid, no matter what
```

In fact, I guess you can just delete the overload and let the variadic version do the right thing :-).

**Comment by sfinktah** [comment]
This reallocation issue has become even more relevant since C++17's `emplace_back` finally returns a reference to the inserted object.

```cpp
template< class... Args >
reference emplace_back( Args&&... args );
```

It is unfortunate that vagaries such as this (and I'm not referring to your library here, I had an issue with MSVC's std::unordered_map changing references) have led to me habitually a std::list to store data when I need to be sure the reference will remain unchanged, and using (e.g.) std::unordered_map as an index into std::list.

My only request would be that it be strongly documented that your class does not comply with (as phrased at http://en.cppreference.com/w/cpp/container/deque/emplace_back) - "No references are invalidated."

**Comment by rparolin** [comment]
It seems interest hasn't picked up on this ticket.  Please re-open with additional information and/or provide a PR for specific changes you would like to see.
