### ISSUE TITLE
CMake version mis-match between Travis and CMakeLists.txt

### ISSUE THREAD

**Issue by bowlofstew** [electronicarts/EASTL#58]
Any reason to specify [CMake version 3.1 or greater](https://github.com/electronicarts/EASTL/blob/master/CMakeLists.txt#L4) but have your Travis file using [3.4.3](https://github.com/electronicarts/EASTL/blob/master/.travis.yml#L27)?  I get that it should work well as expected.  Would there be any value in bumping the CMakeLists.txt to version 3.4.3?

**Comment by rparolin** [comment]
The requirement was originally 3.4.3 but other contributors mentioned that was too restricted mentioned that the features used only required CMake 3.1.  The travis-ci scripts were just never updated, we could do that but its not high on my priority list as its not causing any issues that I'm aware of.

**Comment by rparolin** [comment]
Just merged the PR.
