### ISSUE TITLE
LICENCE should be named LICENSE

### ISSUE THREAD

**Issue by underscorediscovery** [electronicarts/EASTL#6]
I'm not one to be pedantic about this kinda thing, but the readme has the correct spelling right by the incorrect spelling and it stands out :) Thanks for open sourcing this!

**Comment by NotBela** [comment]
#8 I opened a pull request.

**Comment by underscorediscovery** [comment]
It's the file itself too @NotBela, I personally felt a PR a bit overreaching for a quick rename though.

**Comment by Bo98** [comment]
It's not necessarily a "mistake" as it's the proper spelling outside US English. It depends on what variant @electronicarts prefer. Though there is inconsistency in the spelling in the last line of the README.

**Comment by underscorediscovery** [comment]
Ah, I was under the impression it was semantic regarding verbs and nouns (I am not US english grounded, btw).

**Comment by Bo98** [comment]
Yeah, outside US English, license is the verb while licence is the noun. I'd say it's applied as a noun here.

**Comment by underscorediscovery** [comment]
I understood it as a verb in software and copyright terms as licensed by the author, but it doesn't matter really! The consistency is what bothered me most :)

**Comment by rparolin** [comment]
I agree we should be consistent.

**Comment by Bo98** [comment]
It isn't yet because the LICENCE filename is still spelt that way.

**Comment by rparolin** [comment]
Renamed. :)
