### ISSUE TITLE
vector_multimap::count is not const qualified

### ISSUE THREAD

**Issue by xaxxon** [electronicarts/EASTL#64]
it seems like it should be and std::multimap::count is

http://en.cppreference.com/w/cpp/container/multimap/count

Looks like none of the vector_*::count methods are const.

https://github.com/electronicarts/EASTL/blob/e16f7712ec6f3857e769172c020441d358002d34/include/EASTL/vector_map.h#L260

https://github.com/electronicarts/EASTL/blob/e16f7712ec6f3857e769172c020441d358002d34/include/EASTL/vector_multimap.h#L259

https://github.com/electronicarts/EASTL/blob/e16f7712ec6f3857e769172c020441d358002d34/include/EASTL/vector_multiset.h#L226

https://github.com/electronicarts/EASTL/blob/e16f7712ec6f3857e769172c020441d358002d34/include/EASTL/vector_set.h#L228

I simply added const in the declaration/definition for vector_multimap and it seems happy..

any reason not to have these match the corresponding std:: types?

**Comment by rparolin** [comment]
This definitely seems incorrect and would prevent valid code from compiling.  eg.  calling count on a const container because its not guaranteed to not alter the state of the container.  Thanks for submitting this issue.

**Comment by xaxxon** [comment]
I just had to do a reinstall and remembered that I had hand-patched this.   Just wanted to make sure we were agreed on changing this in the next release, whenever that is.

**Comment by rparolin** [comment]
I agree with the proposed change.  I'd be happy to review the PR when its submitted.

**Comment by xaxxon** [comment]
Oh ok. It wasn't clear you were waiting on that.

**Comment by rparolin** [comment]
I have a fix for this coming in the next EASTL release.

**Comment by rparolin** [comment]
3.05.02 released
