### ISSUE TITLE
EASTL doesn't detect non-apple clang on MacOS properly - thinks modern clang versions are pre-C++11

### ISSUE THREAD

**Issue by xaxxon** [electronicarts/EASTL#68]
on clang 3.9 (and probably others), I have to make sure to have

#define EA_HAVE_CPP11_INITIALIZER_LIST

before I include any eastl headers or I get redefinition of initializer_list.  Is this normal?

Searching the eastl source on github for that string, I don't see anywhere it would be set automatically...

Thank you.

**Comment by rparolin** [comment]
The included EABase package is EASTL's only dependency.  It handles defining the necessary compiler and platform defines EASTL uses to configure itself.  The necessary EABase header files should be included implicitly by EASTL headers.

EA_HAVE_CPP11_INITIALIZER_LIST defined here:
https://github.com/electronicarts/EASTL/blob/e16f7712ec6f3857e769172c020441d358002d34/test/packages/EABase/include/Common/EABase/eahave.h#L461

FAQ entry on this:
https://github.com/electronicarts/EASTL/blob/e16f7712ec6f3857e769172c020441d358002d34/doc/EASTL%20FAQ.html#L780

Example of an EASTL header including EABase headers:
https://github.com/electronicarts/EASTL/blob/e16f7712ec6f3857e769172c020441d358002d34/include/EASTL/functional.h#L9

**Comment by xaxxon** [comment]
in eacompilers.h

                #elif defined(EA_COMPILER_CPP11_ENABLED) && defined(__clang__) && (EA_COMPILER_VERSION >= 301) && !defined(__APPLE__) // Clang 3.1+, not including Apple's Clang.                           


is what's killing me.   I'm running 3.9 (real clang version, not stupid apple clang version number) downloaded directly from clang's download site:  http://llvm.org/releases/download.html

Any thoughts on a workaround?  Either for my code or for eacompilers.h directly?

**Comment by rparolin** [comment]
Is your compiler not in at least C++11 mode? 

		#if (__cplusplus >= 201103L)    // Clang and GCC defines this like so in C++11 mode.
			#define EA_COMPILER_CPP11_ENABLED 1

**Comment by xaxxon** [comment]
If I'm reading this correctly, 

Because this isn't true:

		#elif defined(EA_COMPILER_CPP11_ENABLED) && defined(__clang__) && (EA_COMPILER_VERSION >= 301) && !defined(__APPLE__) // Clang 3.1+, not including Apple's Clang.


it sets: 

			#define EA_COMPILER_NO_INITIALIZER_LISTS 1


which then causes this:

	#elif defined(EA_HAVE_LIBCPP_LIBRARY) && (_LIBCPP_VERSION >= 1) && !defined(EA_COMPILER_NO_INITIALIZER_LISTS)

to set EA_NO_HAVE_CPP11_INITIALIZER_LIST instead of EA_HAVE_CPP11_INITIALIZER_LIST

which then causes this to be false:

#if defined(EA_HAVE_CPP11_INITIALIZER_LIST) // If the compiler can generate calls to std::initializer_list...


.. causing std::initializer_list to be redefined here:

	namespace std
	{
		// See the C++11 Standard, section 18.9.
		template<class E> 
		class initializer_list
		{
		public:

**Comment by xaxxon** [comment]
More to the point, I comment out the __APPLE__ test in eacompiler.h and things work as expected.

#elif defined(EA_COMPILER_CPP11_ENABLED) && defined(__clang__) && (EA_COMPILER_VERSION >= 301) // && !defined(__APPLE__) // Clang 3.1+, not including Apple's Clang.

**Comment by xaxxon** [comment]
I have reason to believe there is a __apple_build_version__ but am double checking.

**Comment by xaxxon** [comment]
zacs-MacBook-Pro:apb xaxxon$ cat >deleteme22.cpp
__apple_build_version__
zacs-MacBook-Pro:apb xaxxon$ /usr/bin/clang -E deleteme22.cpp 
# 1 "deleteme22.cpp"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 336 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "deleteme22.cpp" 2
8000038
zacs-MacBook-Pro:apb xaxxon$ /usr/bin/clang -v
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin



zacs-MacBook-Pro:apb xaxxon$ which clang
/Users/xaxxon/Downloads/clang+llvm-3.9.0-x86_64-apple-darwin/bin/clang
zacs-MacBook-Pro:apb xaxxon$ clang -E deleteme22.cpp
# 1 "deleteme22.cpp"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 335 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "deleteme22.cpp" 2
__apple_build_version__

**Comment by rparolin** [comment]
Ah, yes this makes sense.  

EABase figures you are on an Apple platform so you must be using an Apple version of clang.  Since you are using clang 3.9 on MacOS it figures you are on an older version of the Apple Clang compiler which doesn't have initializer_lists.  Preventing CMake from defining __APPLE__ would force EABase into the non-Apple Clang version checks and everything should work correctly.

This is the best document I've found for mapping between the version numbers:
https://trac.macports.org/wiki/XcodeVersionInfo

**Comment by xaxxon** [comment]
I think you could literally to do a text replace of \_\_APPLE__ and \_\_apple_build_version__ and be done.

**Comment by rparolin** [comment]
Potentially, I'm briefly looked at the Apple docs and they refer to __APPLE__ but not to __apple_build_version__.  We actually don't test this use case internally so if its a popular enough feature we could support it.  However we would have to setup the Travis CI infrastructure to validate this use case and ensure we don't regress as future development occurs.  Anyone is interested in doing the work I'd be interested in reviewing the PR.

**Comment by DragoonX6** [comment]
Potentially look at https://github.com/electronicarts/EASTL/blob/master/scripts/CMake/CommonCppFlags.cmake I might have screwed up the apple flags for clang as I don't have an apple machine.
