### ISSUE TITLE
Third party licenses maybe missing a STLPORT mention?

### ISSUE THREAD

**Issue by speeder** [electronicarts/EASTL#7]
I am currently studying some old EA games, from the era just before EASTL writing, they use STLPORT 4.something (my guess is 4.6.2)

I noticed EASTL and STLPORT have very similar file structure and calls, and the third party licenses file looks like it came from STLPORT (including the mention to HP STL).

Can I suggest then that STLPORT is mentioned in the third party licenses?

Or was EASTL made from scratch without ever using STLPORT code?

**Comment by rparolin** [comment]
This was before my time with EA but its my understanding that EASTL was made from scratch.

**Comment by speeder** [comment]
Yes, after posting this I found the explanation on one of the HTML docs.

They used part of HPSTL (that I think was something that was in STLPORT unchanged) with permission of EA Legal Team, and nothing else.

I think the similarities with STLPORT then an attempt to achieve interface compatibility with it (ie: so that old code using it could be easily recompiled when linked against EASTL).

**Comment by rparolin** [comment]
Thanks for the question.
