### ISSUE TITLE
character corruption in EASTL header files.

### ISSUE THREAD

**Issue by dAu6jARL** [electronicarts/EASTL#71]
Two character corruptions exist in EASTL header files.

- include/EASTL/optional.h
U+2019 UTF8 character "’" exists in line 15. I suggest replace U+2019 by 0x27.
`// object of type T, referred to as the optional object’s contained value, is allocated`
suggest: ’ to '

- include/EASTL\internal/type_pod.h
Illegal latin-1 tilde 0x98(U+02DC) is used in line 1670. Legal tilde is 0x7e.
C4819 warning will occurs in non latin-1 version Visual Studio. 
I see this warning in Japanese version VS2017RC.
`// test<T>::˜test() is not deleted (C++11 "= delete").`
suggest: ˜ to ~

**Comment by dAu6jARL** [comment]
Sorry, I am unfamiliar with Git and "pull request".
Instead of PR, I attach two corrected candidate files as a ZIP file "candidate.zip".
Thank you.

[candidate.zip](https://github.com/electronicarts/EASTL/files/624979/candidate.zip)

**Comment by rparolin** [comment]
Sorry, I'd prefer if you submitted a PR.  There are a ton of tutorials online.
