### ISSUE TITLE
ambiguous comparison in vector_multimap, std::multimap works fine

### ISSUE THREAD

**Issue by xaxxon** [electronicarts/EASTL#73]
```

#include <EASTL/vector_multimap.h>
#include <EASTL/string.h>
#include <string>

#include <map>

using namespace std;

#define USE_EASTL

int main(int argc, char **) {

#ifdef USE_EASTL
  eastl::vector_multimap</*eastl::*/string, int> a; // <== either std or eastl string,int cause failure, but int,int does not, all work with std::multimap
#else
  multimap<string,int> a;
#endif

  (void)(a==a);
}
```

Using eastl::vector_multimap, I get the following error when compiled with: /usr/bin/clang++ -std=c++14 deleteme.cpp -I/usr/local/include on os x sierra
```

/usr/local/include/EASTL/vector_multimap.h:779:36: error: call to 'equal' is ambiguous
                return (a.size() == b.size()) && equal(b.begin(), b.end(), a.begin());
                                                 ^~~~~
deleteme.cpp:20:11: note: in instantiation of function template specialization 'eastl::operator==<std::__1::basic_string<char>, int,
      eastl::less<std::__1::basic_string<char> >, eastl::allocator, eastl::vector<eastl::pair<std::__1::basic_string<char>, int>,
      eastl::allocator> >' requested here
  (void)(a==a);
          ^
/usr/local/include/EASTL/algorithm.h:1936:2: note: candidate function [with InputIterator1 = const
      eastl::pair<std::__1::basic_string<char>, int> *, InputIterator2 = const eastl::pair<std::__1::basic_string<char>, int> *]
        equal(InputIterator1 first1, InputIterator1 last1, InputIterator2 first2)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1201:1: note: 
      candidate function [with _InputIterator1 = const eastl::pair<std::__1::basic_string<char>, int> *, _InputIterator2 = const
      eastl::pair<std::__1::basic_string<char>, int> *]
equal(_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2)

```

**Comment by rparolin** [comment]
It looks like the compiler can't decide between calling eastl::equal and std::equal.  I thought ADL would have kicked in here and it would prefer the eastl::equal since the InputIterator is eastl::pair<string, int>.  In eastl container implementations we can't explicitly qualify the equal call because that prevents ADL from being used.  Ie.  you could never use 'your_namespace::equal' in containers.

The only fix that comes mind is not including both eastl::algorithms and std::algorithms headers at the same time.  EASTL does provide some std interop features but they not well tested since we don't use it internally.

**Comment by xaxxon** [comment]
But then how does std::multimap work?   It can see both as well, right?

**Comment by rparolin** [comment]
multimap and vector_multimap are different types so their implementations are completely different.  plus vector_multimap is custom container of EASTL so if there no spec in the iso standard for how operator== would be implemented.  So without looking at the code, I'd imagine std::multimap in the version of libcxx you are using doesn't call std::equal so its not ambiguous.

**Comment by rparolin** [comment]
https://github.com/google/libcxx/blob/master/include/map#L1365
Actually they fully qualify their equals calls, so libcxx doesn't allow you to provide a custom equals via ADL.

**Comment by xaxxon** [comment]
https://github.com/google/libcxx/blob/master/include/algorithm#L628

Eventually it calls down into this, though, and you can customize your type's operator== to change the behavior, right?

**Comment by rparolin** [comment]
I'd prefer to not break existing code unless there is a compelling reason.  std interop isn't a heavily used feature  (and is something that I'm looking at deprecating in the future) so even the smallest possibility of breaking users existing code in favor of a feature we don't use doesn't make sense in my mind.
