### ISSUE TITLE
move_iterator post inc/dec operator

### ISSUE THREAD

**Issue by csisy** [electronicarts/EASTL#79]
https://github.com/electronicarts/EASTL/blob/master/include/EASTL/iterator.h#L468
It should be ++/--mIterator instead of the ++/--tempMoveIterator

**Comment by rparolin** [comment]
Thanks for the info. These functions have also been updated to use constexpr which should also be done with this work.  http://en.cppreference.com/w/cpp/iterator/move_iterator

Would you consider submitting a PR with a test case?

**Comment by rparolin** [comment]
Thanks for reporting this issue.  I'll have a fix for it in the next release.

**Comment by rparolin** [comment]
3.05.02 released
