### ISSUE TITLE
Inconsistency between std::is_function and eastl::is_function

### ISSUE THREAD

**Issue by TheCodeInside** [electronicarts/EASTL#80]
While attempting to add an `is_function_pointer` type trait, I seem to have found an inconsistency between EASTL's `is_function` and the STL's `is_function` when a function pointer type has an MSVC calling convention such as `__stdcall`.

In Visual Studio 2015 (with Update 3), the following code produces expected results with function pointer types:

```c++
template <typename T>
struct is_function_pointer
    : std::integral_constant<bool, std::is_pointer<T>::value &&
                                   std::is_function<typename std::remove_pointer<T>::type>::value>
{
};
```

However, the equivalent code using EASTL's implementations does not work for function pointer types that have MSVC calling conventions, such as `__stdcall`, associated with them.

For example, when working with OpenGL on Windows the function signature for `glClearColor` would be `typedef void (APIENTRYP PFNGLCLEARCOLORPROC)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);` where `APIENTRYP` evaluates to `__stdcall *` (note: this only seems to be the case with 32-bit builds, as I can compile 64-bit with no warnings/errors). `is_function_pointer<PFNGLCLEARCOLORPROC>::value` using the STL's functions evaluates to true, whereas the value is false using EASTL's implementations.

**Comment by rparolin** [comment]
Thanks for reporting this issue.  Too speed up my investigation, could you provide a test case that doesn't depend on OpenGL types that I could iterate on?  Thanks.

**Comment by TheCodeInside** [comment]
Surely. Here's a code snippet that reproduces the issue:

```c++
#include <EASTL/type_traits.h>
#include <type_traits>

typedef void(__stdcall *TestFunction)();

namespace std
{
    template <typename T>
    struct is_function_pointer
        : integral_constant<bool, is_pointer<T>::value &&
                                  is_function<typename remove_pointer<T>::type>::value>
    {
    };
}

namespace eastl
{
    template <typename T>
    struct is_function_pointer
        : integral_constant<bool, is_pointer<T>::value &&
                                  is_function<typename remove_pointer<T>::type>::value>
    {
    };
}

static_assert(std::is_function_pointer<TestFunction>::value, "std::is_function_pointer is incorrect");
static_assert(eastl::is_function_pointer<TestFunction>::value, "eastl::is_function_pointer is incorrect");
```

**Comment by rparolin** [comment]
Thanks!  I'll give that a try.

**Comment by rparolin** [comment]
That's interesting. Your test case works for me across vs2013 and vs2015 (update 3).

**Comment by TheCodeInside** [comment]
Were you compiling for 32- or 64-bit? The error only seems to exist with the former.

**Comment by rparolin** [comment]
That was my issue.  I see the error now.  Thanks.

**Comment by rparolin** [comment]
I believe I have a fix.

--- a/include/EASTL/type_traits.h
+++ b/include/EASTL/type_traits.h
@@ -629,13 +629,35 @@ namespace eastl
                struct is_function
                        : public eastl::false_type {};

-               template <typename ReturnValue, typename... ArgPack>
-               struct is_function<ReturnValue /*FunctionName*/(ArgPack...)>
-                       : public eastl::true_type {};
-
-               template <typename ReturnValue, typename... ArgPack>
-               struct is_function<ReturnValue /*FunctionName*/(ArgPack..., ...)>    // The second ellipsis handles the case of a function that takes ellipsis, like printf.
-                       : public eastl::true_type {};
+               #if EA_PLATFORM_PTR_SIZE == 4 && defined(EA_PLATFORM_MICROSOFT) && defined(_MSC_EXTENSIONS)
+                       // __cdecl specialization
+                       template <typename ReturnValue, typename... ArgPack>
+                       struct is_function<ReturnValue __cdecl (ArgPack...)>
+                               : public eastl::true_type {};
+
+                       template <typename ReturnValue, typename... ArgPack>
+                       struct is_function<ReturnValue __cdecl (ArgPack..., ...)>    // The second ellipsis handles the case of a function that takes ellipsis, like printf.
+                               : public eastl::true_type {};
+
+                       // __stdcall specialization
+                       template <typename ReturnValue, typename... ArgPack>
+                       struct is_function<ReturnValue __stdcall (ArgPack...)>
+                               : public eastl::true_type {};
+
+                       // When functions use a variable number of arguments, it is the caller that cleans the stack (cf. cdecl).
+                       //
+                       // template <typename ReturnValue, typename... ArgPack>
+                       // struct is_function<ReturnValue __stdcall (ArgPack..., ...)>    // The second ellipsis handles the case of a function that takes ellipsis, like printf.
+                       //     : public eastl::true_type {};
+               #else
+                       template <typename ReturnValue, typename... ArgPack>
+                       struct is_function<ReturnValue (ArgPack...)>
+                               : public eastl::true_type {};
+
+                       template <typename ReturnValue, typename... ArgPack>
+                       struct is_function<ReturnValue (ArgPack..., ...)>    // The second ellipsis handles the case of a function that takes ellipsis, like printf.
+                               : public eastl::true_type {};
+               #endif

**Comment by TheCodeInside** [comment]
I'll be able to check this tonight, but it may also be necessary to add specializations for [`__fastcall`](https://msdn.microsoft.com/en-us/library/6xa169sk.aspx) and [`__vectorcall`](https://msdn.microsoft.com/en-us/library/dn375768.aspx). I don't know about [`__thiscall`](https://msdn.microsoft.com/en-us/library/ek8tkfbw.aspx) and [`__clrcall`](https://msdn.microsoft.com/en-us/library/ec7sfckb.aspx), though.

**Comment by TheCodeInside** [comment]
Just tried it, and your solution works. 👍

**Comment by rparolin** [comment]
I can add those as use-cases are encountered.  Thanks.  I'll include this fix in the next EASTL release.

**Comment by rparolin** [comment]
3.05.02 released
