### ISSUE TITLE
string_view class not useable with VC140

### ISSUE THREAD

**Issue by michaeldkroener** [electronicarts/EASTL#83]
Im getting a error C2440 when trying to use eastl::string_view

>include\eastl/string_view.h(66):  error C2440: "<function-style-cast>": "const char *const " cannot be converted to "eastl::reverse_iterator<char *>"

It points me to
```c++
EA_CONSTEXPR const_reverse_iterator crend() const EA_NOEXCEPT { return reverse_iterator(mpBegin); }
```
and after that to

```c++
const unsigned char* p = (const unsigned char*)x.data(); // To consider: limit p to at most 256 chars.
```

it also tells me the error appears when compiling the class template
```c++
eastl::reverse_iterator<const char *> eastl::basic_string_view<char>::crend(void) noexcept const
```

Commenting the reverse iterators resolves the issue the same does using const_cast before on the values 
```c++
		EA_CONSTEXPR reverse_iterator rbegin() const EA_NOEXCEPT { return reverse_iterator(const_cast<pointer>(mpBegin + mnCount)); }
		EA_CONSTEXPR const_reverse_iterator crbegin() const EA_NOEXCEPT { return reverse_iterator(const_cast<pointer>(mpBegin + mnCount)); }
		EA_CONSTEXPR reverse_iterator rend() const EA_NOEXCEPT { return reverse_iterator(const_cast<pointer>(mpBegin)); }
		EA_CONSTEXPR const_reverse_iterator crend() const EA_NOEXCEPT { return reverse_iterator(const_cast<pointer>(mpBegin)); }
````

also
CharTypeStringRSearch
is not defined in string_view.h

**Comment by rparolin** [comment]
Do you have a test-case or snippet to speed up the reproduction?

**Comment by michaeldkroener** [comment]
I could create a test-case but well, it happens when just normally using string_view or even including it im using the latest public version of eastl.
For example the rfind method cannot work it's the same code taken from string.h  before I had this I commented the code inside rfind because the method CharTypeStringRSearch is undefined in string_view.h

**Comment by rparolin** [comment]
I have fixes for the issues you've highlighted in the following work branch:
https://github.com/electronicarts/EASTL/tree/stringview_fixes

These fixes will be included in the next EASTL release.

**Comment by rparolin** [comment]
3.05.02 released
