### ISSUE TITLE
hash_map linker error on 3.05.00

### ISSUE THREAD

**Issue by pjohalloran** [electronicarts/EASTL#84]
Hi,
I am using release 3.05.00 and I am seeing a linker error when i try to use hash_map on OSX platform, in xcode 8.2.1 using default compiler Apple LLVM 8.0. This is likely due to something I have done wrong as i have built EASTL and run the unit tests and all is good.

I have used vector and map containers so far with no problems but when I try to include and use hash_map in a project, I get linker error:
> Undefined symbols for architecture x86_64:
  "eastl::gpEmptyBucketArray", referenced from:

I looked at usage in the unit tests and I noticed that the code was included to force compilation:
`// Template instantations.`
`// These tell the compiler to compile all the functions for the given class.`
`template class eastl::hash_map<int, int>;`

When i try adding the template instantation above in my project, I get more linker errors (I can post full error trace if helpful):
>  "eastl::gpEmptyBucketArray", referenced from:
> "eastl::prime_rehash_policy::GetBucketCount(unsigned int) const", referenced from:
> "eastl::prime_rehash_policy::GetNextBucketCount(unsigned int) const", referenced from:

I would really appreciate if anybody could give me a hint of what I am doing wrong please. Thank you!

**Comment by rparolin** [comment]
Hi,

EASTL is mostly a header library but it doesn't have a few cpp files that need to built in your project.  You're using a hash_map which is an eastl::hashtable backed container, so the hashtable.cpp needs to be built.  I'd imagine that's the problem you are seeing.

source/hashtable.cpp:20:        /// gpEmptyBucketArray
source/hashtable.cpp:26:        EASTL_API void* gpEmptyBucketArray[2] = { NULL, (void*)uintptr_t(~0) };

**Comment by pjohalloran** [comment]
Oh god, I did not include the lib properly in my premake config files. Thanks and sorry to waste your time!

**Comment by rparolin** [comment]
No worries.  Good luck.
