### ISSUE TITLE
"We're way faster because we cut and paste our code"

### ISSUE THREAD

**Issue by DragoonX6** [electronicarts/EASTL#89]
This was said in the talk at cppcon 2015 from Scott Wardle, where he mentioned EASTL and why it's faster in debug mode.
After which he mentions that you basically hope for the best and that you didn't introduce that many bugs.
I'm not sure how much of this is still true today, but if it is, I was thinking about a way that could get us best of both worlds.
We could set up a preprocessor that scans for a custom set of macros that would do the inlining for us.
So I was thinking that we then would end up with something comparable to this in the generated source code:
```
// Pre-Inlined eastl::vector<T>::push_back
// At EASTL/vector.h:123
/* insert code here*/
// End of Pre-Inlined eastl::vector<T>::push_back
```
So whenever you would run into a bug at one place, you can be sure you fixed it everywhere.
The obvious downside of this is that you have to generate the source code, but I think it could be worth it in the long run looking at it from a stability standpoint.

**Comment by swardle** [comment]
This is true I said that.  There are lots of other solutions. 

We could remove the duplication with Marcos for sure but this would be harder to debug for our users. 

It is possible with generated code maybe we can have the best of both worlds.  But it is one more tool to break. 

Other stl use lots of inline functions.  That do not get inlined in debug or in some cases optimized code. 

I think having simple maybe some what duplicated code is not so bad.  Long as you have adequate testing. But really Rob's the guy here he owns the lib and it is his job to find the right balance here. 

Scott

**Comment by DragoonX6** [comment]
With macros I meant not one that is handled by the c++ compiler, I meant one that is processed by an external tool, sorry if that wasn't clear.
And I think having a generator "manually" inline the code is not a bad solution, especially if it were to insert comments like what I've suggested. You're right in that it can break though, it's a trade off you have to think about, but I think it can be worth it considering the growing size of EASTL.

Offtopic: I really enjoyed your talk, lots to learn from it :)

**Comment by rparolin** [comment]
I'd agree with @swardle.

EASTL is indeed growing but I believe the growth has been manageable thus far with not that much duplicated code.  I'd say most of the recently duplicated code I have a strategy to centralize it but I avoided doing so to prevent breaking users of our most commonly used types (eg. strings and vectors).  It wasn't done for any kind of runtime or compile-time performance.  I will be doing that work in the future as I bring other implementations online designed for that purpose, for example of eastl::char_traits.

The thought of preprocessing our code with an external tool (despite its popularity within the games industry) doesn't thrill me.  I really wouldn't even consider a solution that involved the preprocessor.  I'd rather deal with standards conforming C++ code being given to a compiler and not obscure the EASTL implementations at all unless there is really a compelling reason to do so.  This is a feature that the community has told us they really appreciate about our implementation and I would hate to make contributing code/fixes to the library more difficult.

**Comment by DragoonX6** [comment]
Alright, I can respect that. Maybe this would be something to think about again later down the road.

**Comment by rparolin** [comment]
Absolutely.  The standard is growing and we should keep this in the back of our minds.  Thanks for starting the discussion.

**Comment by swardle** [comment]
Thanks I think I understand what you are thinking now.  More like a separate preprocessor/code generator.  But when it came to debugging it the might be tricky because of the extra level of indirection.  Or the code might look strange because it's generated. 

Also the build system for such a change is kind of annoying.  We support 2 build systems for EASTL code adding complexity here probably not as easy as it might look too. 

But thanks for the comment.  It is always nice to hear what other people think.  

Scott
