### ISSUE TITLE
Visual Studio project generation not including appropriate headers

### ISSUE THREAD

**Issue by Nuclearfossil** [electronicarts/EASTL#9]
After generating a Visual Studio solution using the following:

```
cmake.exe -G "Visual Studio 14 2015 Win64"
```

Visual studio fails in compilation with the following:

```
1>------ Build started: Project: EASTL, Configuration: Debug x64 ------
1>  allocator_eastl.cpp
1>C:\Code\Research\EASTL\include\EASTL/internal/config.h(61): fatal error C1083: Cannot open include file: 'EABase/eabase.h': No such file or directory
1>  assert.cpp
1>C:\Code\Research\EASTL\include\EASTL/internal/config.h(61): fatal error C1083: Cannot open include file: 'EABase/eabase.h': No such file or directory
1>  fixed_pool.cpp
1>C:\Code\Research\EASTL\include\EASTL/internal/fixed_pool.h(22): fatal error C1083: Cannot open include file: 'EABase/eabase.h': No such file or directory
1>  hashtable.cpp
1>C:\Code\Research\EASTL\include\EASTL/internal/hashtable.h(30): fatal error C1083: Cannot open include file: 'EABase/eabase.h': No such file or directory
1>  intrusive_list.cpp
1>C:\Code\Research\EASTL\include\EASTL/internal/config.h(61): fatal error C1083: Cannot open include file: 'EABase/eabase.h': No such file or directory
1>  numeric_limits.cpp
1>C:\Code\Research\EASTL\include\EASTL/internal/config.h(61): fatal error C1083: Cannot open include file: 'EABase/eabase.h': No such file or directory
1>  red_black_tree.cpp
1>C:\Code\Research\EASTL\include\EASTL/internal/config.h(61): fatal error C1083: Cannot open include file: 'EABase/eabase.h': No such file or directory
1>  string.cpp
1>C:\Code\Research\EASTL\include\EASTL/internal/config.h(61): fatal error C1083: Cannot open include file: 'EABase/eabase.h': No such file or directory
1>  thread_support.cpp
1>C:\Code\Research\EASTL\include\EASTL/internal/config.h(61): fatal error C1083: Cannot open include file: 'EABase/eabase.h': No such file or directory
1>  Generating Code...
2>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
```

**Comment by Nuclearfossil** [comment]
Just submitted a PR to resolve this.

**Comment by rparolin** [comment]
Thank you.  I'll review it.

**Comment by Nuclearfossil** [comment]
My cmake-fu is not particularly strong, so feel free to update it as necessary.

**Comment by rparolin** [comment]
Neither is mine. :)  I'm delaying any code/script changes until I get travis up then I can verify the changes work on all platforms.  Stay tuned.

**Comment by rparolin** [comment]
Are you running your cmake command from the test folder?

**Comment by Nuclearfossil** [comment]
No, this was in the root - where cmakefikes.txt lives.

**Comment by Nuclearfossil** [comment]
Sorry for the tyoos. On sky train typing on phone.

**Comment by c6burns** [comment]
The test folder is calling add_subdirectory on the parent which threw me off as well

**Comment by Klaim** [comment]
You need to check this CMake function: target_include_directories()
It lets you associate include paths to targets so that the target user have automatically include directories set for it's dependencies (aka your target)

**Comment by Nuclearfossil** [comment]
Yeah, I've actually put this into the associated PR.

**Comment by c6burns** [comment]
The PR is crafted under the assumption that this project should be built from the top level directory. In fact it is designed to be built from the test. The CMakeLists.txt there declares the min cmake version, calls the project command, and calls add_subdirectory on the directory where you are modifying CMakeLists.txt

If you build from the top level directory like it appears you are trying, you are not going to have an EAStdC target

**Comment by Nuclearfossil** [comment]
As stated in the PR, where is this documented?

**Comment by c6burns** [comment]
It isn't documented, but I guess it should be. I always assume a CMake project builds out from the top level directory so I made this same mistake until checking through the subfolders

**Comment by rparolin** [comment]
That's correct the test folder is the unit test project.  EASTL unit tests are intended to be built from the test folder.  I was lead to believe (due to discussions I had before releasing) that this would not be confusing.  Oh well.  I'm open to suggestions on how to improve this.

**Comment by c6burns** [comment]
Personally, I think it's fine. If anything Instead of re-structuring the project just put note in the readme for the people who play it fast and loose (like me) and didn't read the contributing notes

**Comment by rparolin** [comment]
I think that's a good idea.  Thanks.

**Comment by Nuclearfossil** [comment]
That's a little out of the norm; most oss projects have you create some "build" folder where you can generate said projects. Additionally I would say that putting the "how to build" instructions in the "contributing" document is counter intuitive. Adding a single note of "for build instructions see the 'contributing' documentation" would be a minimal option.

**Comment by rparolin** [comment]
I accepted your merge request @Nuclearfossil.  Thank you.  That should resolve this issue.  Reopen or create a new issue if that didn't work.
