### ISSUE TITLE
Undefined reinterpret_cast behavior in char_traits.h

### ISSUE THREAD

**Issue by DragoonX6** [electronicarts/EASTL#90]
I've been busy setting up a local copy of EASTL mainly to have it compiled with waf, but as I compile with a really high warning level I came across this potential bug.
At https://github.com/electronicarts/EASTL/blob/master/include/EASTL/internal/char_traits.h#L60 a `const wchar_t*&` is cast to a `const char16_t*&,` this is undefined behavior according to clang.

I fixed it by making a local temporary in the form of: `const char16_t** localPSrc = reinterpret_cast<const char16_t**>(&pSrc);` and passing it as `*localPSrc`,
it retains the behavior and silences the clang warning, although I'm honestly not sure if this is undefined behavior either (type punning aside).

**Comment by rparolin** [comment]
I'm not sure why clang would prefer a cast of  char16_t** vs char16_t&*.  Could you provide more details about what Clang is figuring is undefined behaviour.

Out of curiousity, what is waf?

**Comment by DragoonX6** [comment]
It seems you forgot, but I've explained it before when I made the issue report about unity builds [here](https://github.com/electronicarts/EASTL/issues/77#issuecomment-265507580).
And as much as it embarrasses me to say it, I cannot get clang to output that warning again, even after rolling back char_traits.h and going over my flags to see if I'm not ignoring it.

**Comment by rparolin** [comment]
Ah, yes.  I remember waf now.  Apologises.

Well if you can provide a PR or a failing test case, we can keep the issue open.  If its going to take time we can reopen it or create a new issue when that happens.

**Comment by DragoonX6** [comment]
I'm able to reproduce the warning in an isolated environment, you can view it [here](http://coliru.stacked-crooked.com/a/98e34d68516e3d9c), I have no idea why it's not popping up in my builds now though.

**Comment by DragoonX6** [comment]
I found out why it wasn't popping up in my builds, and got it to reproduce.
I'm pretty sure the actual undefined behaviour here is casting to a reference, likely due to the need of a temporary to write to.
I'll see if I can provide a PR tomorrow.

**Comment by rparolin** [comment]
I want to avoid long standing issues in the issue tracker.  I'm going to close this.  Please reopen or file a new issue when a PR is ready.

**Comment by DragoonX6** [comment]
I'll reopen this issue once I have access to a working computer again, my laptop unexpectedly died so I couldn't get back to you.
