### ISSUE TITLE
ensure eastl::string and eastl::vector are noexcept correct

### ISSUE THREAD

**Issue by DragoonX6** [electronicarts/EASTL#93]
When exceptions are enabled you will miss out on possible optimizations when moving functions aren't noexcept.
This causes the compiler will complain about defaulted move constructors/move assignment operators not matching the calculated one. I'm not sure if ignoring this warning will still emit the optimizations, but I don't want to ignore it for cases where I do want the warning emitted and not litter my code full of static asserts.

I have done some work locally to add the noexcept specifications, but I haven't made sure to check if both eastl::string and eastl::vector are noexcept correct.

**Comment by DragoonX6** [comment]
@rparolin Would you be interested in my changes? Or do you prefer to do this kind of work yourself?  
Also what level of support is there for exceptions? I vaguely remember something about them being untested for a while.

**Comment by rparolin** [comment]
Yes, I'd definitely be interested in these changes.  EASTL supports enabling/disabling of exceptions; this work would help with optimal codegen in environments where EASTL is used with exceptions enabled.

**Comment by rparolin** [comment]
I did this work in the latest release.

**Comment by DragoonX6** [comment]
Sorry I couldn't find the time to contribute it myself, I haven't had the time for personal/open source projects for quite a while now.  
Anyway, your work is much appreciated!
