### ISSUE TITLE
How to track memory deallocation?

### ISSUE THREAD

**Issue by swaption** [electronicarts/EASTL#94]
Following [SampleNewAndDelete.cpp](https://github.com/electronicarts/EASTL/blob/master/doc/SampleNewAndDelete.cpp), `void* operator new[]` accepts argument `const char* name`, so it is possible to total track memory allocation grouped by named containers. However, `void operator delete` only as one argument (`void* p`), so I am confused about how memory deallocation is intended be tracked?

**Comment by rparolin** [comment]
EA has defined a custom operator new signature so we can pass debug information for each allocation.  We have custom allocators that aren't part of the open source repository that handle the memory allocation meta-data.  Unfortunately, if you wish to track memory allocations this will be an something you will have to integrate into your existing environment or something you have to implement from scratch.
