### ISSUE TITLE
Hashtable.emplace() SFINAE is broken in 3.05.03

### ISSUE THREAD

**Issue by jvidziunas** [electronicarts/EASTL#96]
Code that uses `hashtable.emplace()` (via `unordered_map<>` and `unordered_set<>`) will fail to compile or work differently from expected due to SFINAE-related changes going from 3.05.02 -> 3.05.03. The flaw is pretty easy to see with illustration, so here goes.
```
#include <eastl/unordered_set.h>

struct TestClass {
	TestClass ( int, TestClass ) {}
	TestClass () = default;
};

// Hash implementation omitted for brevity...

void main(char** argv, int argc) {
	eastl::hash_set<TestClass> set;

	set.emplace( 5, TestClass() );
}
```
The variadic overload of `DoInsertValue()` won't match in this case since there's a trailing `void*` in the parameter list, which cannot be constructed from a `TestClass`. Likewise, the additional overload taking a `TestClass&&` will also balk for essentially the same reason. Changing the number of constructor parameters/arguments passed here will result in different errors, though from testing on my end the single-argument version does work the way I think the author intended.

I'm not sure a fix on my end is necessary, as the code that existed for `DoInsertValue()` as of 3.05.02 worked correctly; it looks like someone made what they thought were stylistic changes and broke stuff. Just reverting the signature back should be enough to fix the problem and probably stands to reduce debug symbol size due to the smaller number of templates.

**Comment by rparolin** [comment]
It is indeed broken, we discovered this internally and I have a fix ready to go.  I'll post a new release ASAP next week.

**Comment by jvidziunas** [comment]
Cool. Leave this open until release, then.

**Comment by rparolin** [comment]
Released 3.05.04.

**Comment by jvidziunas** [comment]
Provided fix is incomplete, while the initial issue has been resolved MSVC2013 is unable to associate the implementation of DoInsertValue() with the declaration in the class in 3.05.04. Is this considered a supported compiler?

**Comment by rparolin** [comment]
Investment in VS2013 is winding down, but it is still considered a supported compiler for the time being.  We will be officially deprecating internally in the near future.  Can you provide a test that highlights the error?

**Comment by jvidziunas** [comment]
Simply including the file was enough, but after doing some work to move over to VS2017 I can no longer reproduce the issue on my end. I'll create a separate ticket if I run into the issue again.
